Repository space-wizards/RobustToolbox, pull requests merged in 2018-07, with the labels that each got.

#611 VFS Features
  SS14.Client/Console/Commands/Debug.cs
  SS14.Client/GameController.cs
  SS14.Client/GameController/GameController.IoC.cs
  SS14.Client/GameObjects/Components/Light/PointLightComponent.cs
  SS14.Client/GameObjects/EntitySystems/AudioSystem.cs
  SS14.Client/GameObjects/EntitySystems/EffectSystem.cs
  SS14.Client/Graphics/Lighting/LightManager.cs
  SS14.Client/Graphics/RSI/RSI.cs
  SS14.Client/Input/InputManager.cs
  SS14.Client/Interfaces/ResourceManagement/IResourceCache.cs
  SS14.Client/Map/ClientTileDefinitionManager.cs
  SS14.Client/Placement/PlacementManager.cs
  SS14.Client/Placement/PlacementMode.cs
  SS14.Client/ResourceManagement/BaseResource.cs
  SS14.Client/ResourceManagement/ResourceCache.cs
  SS14.Client/ResourceManagement/ResourceTypes/TextureResource.cs
  SS14.Client/UserInterface/CustomControls/DebugCoordsPanel.cs
  SS14.Client/UserInterface/CustomControls/NetDebugPanel.cs
  SS14.Server/BaseServer.cs
  SS14.Server/Chat/ChatManager.cs
  SS14.Server/Maps/MapLoader.cs
  SS14.Server/Program.cs
  SS14.Shared/ContentPack/AssemblyLoader.cs
  SS14.Shared/ContentPack/ResourceManager.cs
  SS14.Shared/ContentPack/WritableDirProvider.cs
  SS14.Shared/GameStates/GameState.cs
  SS14.Shared/Interfaces/Resources/IResourceManager.cs
  SS14.Shared/Interfaces/Resources/IWritableDirProvider.cs
  SS14.Shared/Map/MapManager.cs
  SS14.Shared/Prototypes/PrototypeManager.cs
  SS14.Shared/Reflection/ReflectionManager.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.Shared/Utility/PlatformTools.cs
  SS14.Shared/Utility/ResourcePath.cs
  SS14.UnitTesting/SS14UnitTest.cs
  SS14.UnitTesting/Shared/Utility/ResourcePath_Test.cs
Labels: Project: Shared, Type: Feature, W: In Progress

#610 Public access modifiers for YAMLEntitySerializer
  SS14.Shared/GameObjects/Serialization/YamlEntitySerializer.cs
Labels: W: Review

#616 Server Console - Cumulative Feature Update
  Resources/Groups/groups.yml
  SS14.Server/BaseServer.cs
  SS14.Server/ClientConsoleHost/ClientConsoleHost.cs
  SS14.Server/ClientConsoleHost/Commands/DrugsCommand.cs
  SS14.Server/ClientConsoleHost/Commands/ListCommands.cs
  SS14.Server/ClientConsoleHost/Commands/MapCommands.cs
  SS14.Server/ClientConsoleHost/Commands/SysCommands.cs
  SS14.Server/Console/Commands/ChatCommands.cs
  SS14.Server/Console/Commands/ListCommands.cs
  SS14.Server/Console/Commands/LogCommands.cs
  SS14.Server/Console/Commands/MapCommands.cs
  SS14.Server/Console/Commands/PlayerCommands.cs
  SS14.Server/Console/Commands/RoundCommands.cs
  SS14.Server/Console/Commands/SpawnCommand.cs
  SS14.Server/Console/Commands/SysCommands.cs
  SS14.Server/Console/ConGroup.cs
  SS14.Server/Console/ConGroupContainer.cs
  SS14.Server/Console/ConGroupController.cs
  SS14.Server/Console/ConGroupIndex.cs
  SS14.Server/Console/ConsoleShell.cs
  SS14.Server/Console/SessionGroupContainer.cs
  SS14.Server/Console/SystemConsoleManager.cs
  SS14.Server/Interfaces/ClientConsoleHost/IClientCommand.cs
  SS14.Server/Interfaces/ClientConsoleHost/IClientConsoleHost.cs
  SS14.Server/Interfaces/Console/IClientCommand.cs
  SS14.Server/Interfaces/Console/IConsoleShell.cs
  SS14.Server/Interfaces/Console/ISystemConsoleManager.cs
  SS14.Server/Interfaces/IBaseServer.cs
  SS14.Server/Interfaces/ServerConsole/IConsoleCommand.cs
  SS14.Server/Interfaces/ServerConsole/IConsoleManager.cs
  SS14.Server/Program.cs
  SS14.Server/SS14.Server.csproj
  SS14.Server/ServerConsole/Commands/HelpCommand.cs
  SS14.Server/ServerConsole/Commands/ListCommands.cs
  SS14.Server/ServerConsole/Commands/ListPlayers.cs
  SS14.Server/ServerConsole/Commands/SaveConfig.cs
  SS14.Server/ServerConsole/Commands/ServerManagement.cs
  SS14.Server/ServerConsole/Commands/TestCommand.cs
  SS14.Server/ServerConsole/Commands/ThrowException.cs
  SS14.Server/packages.config
  SS14.Shared/ContentPack/WritableDirProvider.cs
  SS14.Shared/Interfaces/Resources/IWritableDirProvider.cs
  SS14.UnitTesting/SS14.UnitTesting.csproj
  SS14.UnitTesting/SS14UnitTest.cs
Labels: W: In Progress

#620 ECS - ComponentManager Restructure
  SS14.Client/Debugging/DebugDrawing.cs
  SS14.Client/GameObjects/ClientEntityManager.cs
  SS14.Client/GameObjects/Components/Appearance/AppearanceComponent.cs
  SS14.Client/GameObjects/EntitySystems/AppearanceSystem.cs
  SS14.Client/GameObjects/EntitySystems/AppearanceTestSystem.cs
  SS14.Client/GameObjects/EntitySystems/SpriteSystem.cs
  SS14.Client/SS14.Client.csproj
  SS14.Client/State/States/GameScreen.cs
  SS14.Server/BaseServer.cs
  SS14.Server/GameObjects/Components/Mover/PlayerInputMoverComponent.cs
  SS14.Server/GameObjects/EntitySystems/AiSystem.cs
  SS14.Server/GameObjects/EntitySystems/InputSystem.cs
  SS14.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  SS14.Server/GameObjects/ServerEntityManager.cs
  SS14.Server/Interfaces/GameObjects/IServerEntityManager.cs
  SS14.Server/Maps/MapLoader.cs
  SS14.Server/SS14.Server.csproj
  SS14.Shared/GameObjects/Component.cs
  SS14.Shared/GameObjects/ComponentManager.cs
  SS14.Shared/GameObjects/Entity.cs
  SS14.Shared/GameObjects/EntityManager.cs
  SS14.Shared/GameObjects/EntityQuery.cs
  SS14.Shared/GameObjects/EntitySystemManager.cs
  SS14.Shared/GameObjects/EntityUid.cs
  SS14.Shared/GameObjects/IncomingEntityComponentMessage.cs
  SS14.Shared/Interfaces/GameObjects/IComponent.cs
  SS14.Shared/Interfaces/GameObjects/IComponentManager.cs
  SS14.Shared/Interfaces/GameObjects/IEntity.cs
  SS14.Shared/Interfaces/GameObjects/IEntityManager.cs
  SS14.Shared/Prototypes/EntityPrototype.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.UnitTesting/SS14.UnitTesting.csproj
  SS14.UnitTesting/Shared/GameObjects/ComponentManager_Test.cs
Labels: Project: Shared, System: Entities, Type: Performance, W: In Progress

#621 Entity Data Refactor
  Resources/Maps/Demo/DemoGrid.yaml
  SS14.Client.Godot/SS14Loader.cs
  SS14.Client/Console/Commands/Debug.cs
  SS14.Client/GameObjects/Components/Appearance/AppearanceComponent.cs
  SS14.Client/GameObjects/Components/BoundingBox/BoundingBoxComponent.cs
  SS14.Client/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Client/GameObjects/Components/Icon/IconComponent.cs
  SS14.Client/GameObjects/Components/Light/PointLightComponent.cs
  SS14.Client/GameObjects/Components/Occluder/OccluderComponent.cs
  SS14.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  SS14.Client/Placement/PlacementManager.cs
  SS14.Client/SS14.Client.csproj
  SS14.Server/GameObjects/Components/BoundingBox/BoundingBoxComponent.cs
  SS14.Server/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Server/GameObjects/Components/Light/PointLightComponent.cs
  SS14.Server/GameObjects/Components/Mover/AiControllerComponent.cs
  SS14.Server/GameObjects/Components/Physics/PhysicsComponent.cs
  SS14.Server/GameObjects/Components/Renderable/SpriteComponent.cs
  SS14.Server/GameObjects/Components/Transform/TransformComponent.cs
  SS14.Server/GameObjects/ServerEntityManager.cs
  SS14.Server/Interfaces/GameObjects/IServerEntityManager.cs
  SS14.Server/Interfaces/GameObjects/IServerEntityManagerInternal.cs
  SS14.Server/Interfaces/Maps/IMapLoader.cs
  SS14.Server/Maps/MapLoader.cs
  SS14.Server/Maps/YamlGridSerializer.cs
  SS14.Server/Program.cs
  SS14.Server/SS14.Server.csproj
  SS14.Shared/GameObjects/Component.cs
  SS14.Shared/GameObjects/Components/Renderable/SharedSpriteComponent.cs
  SS14.Shared/GameObjects/Entity.cs
  SS14.Shared/GameObjects/EntityManager.cs
  SS14.Shared/GameObjects/Serialization/EntitySerializer.cs
  SS14.Shared/GameObjects/Serialization/YamlEntitySerializer.cs
  SS14.Shared/Interfaces/GameObjects/IComponent.cs
  SS14.Shared/Interfaces/GameObjects/IEntity.cs
  SS14.Shared/Interfaces/GameObjects/IEntityFinishContext.cs
  SS14.Shared/Interfaces/GameObjects/IEntityManager.cs
  SS14.Shared/Interfaces/Serialization/IExposeData.cs
  SS14.Shared/Map/Tile.cs
  SS14.Shared/Maths/Color.cs
  SS14.Shared/Properties/AssemblyInfo.cs
  SS14.Shared/Prototypes/EntityPrototype.cs
  SS14.Shared/Prototypes/PrototypeManager.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.Shared/Serialization/ObjectSerializer.cs
  SS14.Shared/Serialization/YamlObjectSerializer.cs
  SS14.Shared/Utility/CollectionExtensions.cs
  SS14.Shared/Utility/YamlHelpers.cs
  SS14.UnitTesting/SS14.UnitTesting.csproj
  SS14.UnitTesting/Shared/Serialization/YamlObjectSerializer_Test.cs
  docs/Map Format.md
Labels: Priority: 1-high, System: Entities, System: Prototypes, Topic: Architecture, Type: Refactor, W: Review

#624 DebugTools.Assert
  SS14.Client/BaseClient.cs
  SS14.Client/GameObjects/Components/Icon/IconComponent.cs
  SS14.Client/Player/PlayerManager.cs
  SS14.Server/Player/PlayerManager.cs
  SS14.Shared/Map/MapManager.Network.cs
  SS14.Shared/Map/TileDefinition.cs
  SS14.Shared/Network/NetManager.cs
  SS14.Shared/Network/StringTable.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.Shared/Utility/DebugTools.cs
Labels: W: In Progress

#635 Ah shit I did the thing I said I wouldn't do and I just forgot to com…
  SS14.Client/SS14.Client.csproj
Labels: W: In Progress
