Repository space-wizards/RobustToolbox, pull requests merged in 2018-03, with the labels that each got.

#531 InputSystem Messages
  SS14.Client/GameObjects/ClientComponentFactory.cs
  SS14.Client/GameObjects/Components/Input/ClickableComponent.cs
  SS14.Client/GameObjects/Components/Input/KeyBindingInputComponent.cs
  SS14.Client/GameObjects/EntitySystems/InputSystem.cs
  SS14.Client/Input/BoundKeyEventArgs.cs
  SS14.Client/Input/KeyBindingManager.cs
  SS14.Client/Interfaces/GameObjects/Components/IClientClickableComponent.cs
  SS14.Client/Interfaces/Input/IKeyBindingManager.cs
  SS14.Client/Player/LocalPlayer.cs
  SS14.Client/State/States/GameScreen.cs
  SS14.Server/GameObjects/Components/ClickableComponent.cs
  SS14.Server/GameObjects/Components/Input/KeyBindingInputComponent.cs
  SS14.Server/GameObjects/Components/Mover/PlayerInputMoverComponent.cs
  SS14.Server/GameObjects/EntitySystems/InputSystem.cs
  SS14.Server/GameObjects/Events/InputEvents.cs
  SS14.Server/GameObjects/Exceptions/MissingImplementationException.cs
  SS14.Server/GameObjects/Exceptions/NoPublicConstructorException.cs
  SS14.Server/GameObjects/MessageEnums.cs
  SS14.Server/SS14.Server.csproj
  SS14.Shared/GameObjects/ComponentMessages/Messages.cs
  SS14.Shared/GameObjects/EntityEvents.cs
  SS14.Shared/GameObjects/EntityManager.cs
  SS14.Shared/GameObjects/EntitySystemManager.cs
  SS14.Shared/GameObjects/EntitySystemMessage/EntitySystemMessage.cs
  SS14.Shared/GameObjects/EntitySystemMessages/ClickedOnEntityMessage.cs
  SS14.Shared/GameObjects/EntitySystemMessages/EntitySystemMessage.cs
  SS14.Shared/GameObjects/EntitySystemMessages/InputMessages.cs
  SS14.Shared/GameObjects/EntitySystemMessages/InventorySystemMessages.cs
  SS14.Shared/GameObjects/Events/InputEvents.cs
  SS14.Shared/GameObjects/System/EntitySystem.cs
  SS14.Shared/Input/ClickType.cs
  SS14.Shared/Input/KeyFunctions.cs
  SS14.Shared/Input/UserCmd.cs
  SS14.Shared/Interfaces/GameObjects/Components/IClickableComponent.cs
  SS14.Shared/Interfaces/GameObjects/IEntityManager.cs
  SS14.Shared/Interfaces/GameObjects/IEntitySystemManager.cs
  SS14.Shared/Interfaces/GameObjects/System/IEntitySystem.cs
  SS14.Shared/SS14.Shared.csproj
Labels: Project: Shared, System: Entities, Type: Feature, W: In Progress

#534 Full interaction system
  SS14.Client/GameObjects/EntitySystems/InputSystem.cs
  SS14.Client/State/States/GameScreen.cs
  SS14.Shared/GameObjects/EntitySystemMessages/InputMessages.cs
Labels: Status: Requesting Merge

#533 Directional Placement Manager Fix
  SS14.Client/Placement/PlacementManager.cs
  SS14.Client/Placement/PlacementMode.cs
Labels: Status: Requesting Merge

#535 Fix Travis and code analysis compiler warnings on Unix.
  .travis.yml
  BuildChecker/BuildChecker.csproj
  Sandbox.Client/Sandbox.Client.csproj
  Sandbox.Server/Sandbox.Server.csproj
  Sandbox.Shared/Sandbox.Shared.csproj
Labels: Platform: Linux, Platform: MacOS, W: In Progress

#532 Raycasting + Turret AI
  SS14.Client.Graphics/Lighting/ILight.cs
  SS14.Client.Graphics/Lighting/Light.cs
  SS14.Client.Graphics/Lighting/ShadowMapResolver.cs
  SS14.Client/GameObjects/ClientComponentFactory.cs
  SS14.Client/GameObjects/Components/Light/PointLightComponent.cs
  SS14.Server/AI/AiLogicProcessor.cs
  SS14.Server/AI/AiLogicProcessorAttribute.cs
  SS14.Server/GameObjects/Components/Mover/AiControllerComponent.cs
  SS14.Server/GameObjects/Components/Transform/TransformComponent.cs
  SS14.Server/GameObjects/EntitySystems/AiSystem.cs
  SS14.Server/GameObjects/ServerComponentFactory.cs
  SS14.Server/GameObjects/ServerEntityManager.cs
  SS14.Server/SS14.Server.csproj
  SS14.Shared/GameObjects/Entity.cs
  SS14.Shared/Interfaces/GameObjects/IEntity.cs
  SS14.Shared/Interfaces/Physics/ICollidable.cs
  SS14.Shared/Interfaces/Physics/ICollisionManager.cs
  SS14.Shared/Maths/Angle.cs
  SS14.Shared/Maths/Box2.cs
  SS14.Shared/Maths/FloatMath.cs
  SS14.Shared/Maths/Quaternion.cs
  SS14.Shared/Maths/Ray.cs
  SS14.Shared/Maths/Vector2.cs
  SS14.Shared/Network/NetChannel.cs
  SS14.Shared/Network/NetManager.cs
  SS14.Shared/Physics/CollisionManager.cs
  SS14.Shared/Physics/RayCastResults.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.UnitTesting/SS14.UnitTesting.csproj
  SS14.UnitTesting/Server/GameObjects/ServerEntityManager_Test.cs
  SS14.UnitTesting/Shared/Maths/Ray_Test.cs
  SS14.UnitTesting/Shared/Physics/CollisionManager_Test.cs
  SS14.UnitTesting/packages.config
Labels: Status: Requesting Merge, Status: Under Review, W: In Progress

#542 GetAllPlayers() doesn't return nulls
  SS14.Server/ClientConsoleHost/Commands/PlayerCommands.cs
  SS14.Server/Player/PlayerManager.cs
Labels: W: In Progress

#538 GameLoop Refactor
  SS14.Client/GameController.cs
  SS14.Server/BaseServer.cs
  SS14.Shared/Interfaces/Timing/IGameTiming.cs
  SS14.Shared/Properties/AssemblyInfo.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.Shared/Timing/FrameEventArgs.cs
  SS14.Shared/Timing/GameLoop.cs
  SS14.Shared/Timing/GameTiming.cs
  SS14.Shared/Timing/IStopwatch.cs
  SS14.Shared/Timing/Stopwatch.cs
  SS14.UnitTesting/SS14.UnitTesting.csproj
  SS14.UnitTesting/SS14UnitTest.cs
  SS14.UnitTesting/Shared/Timing/GameLoop_Test.cs
  SS14.UnitTesting/Shared/Timing/GameTiming_Test.cs
Labels: Project: Shared, Review, Type: Refactor

#539 Serializer Improvements
  SS14.Shared/GameObjects/Serialization/EntitySerializer.cs
  SS14.Shared/GameObjects/Serialization/YamlEntitySerializer.cs
  SS14.UnitTesting/SS14.UnitTesting.csproj
  SS14.UnitTesting/Shared/GameObjects/Serialization/YamlEntitySerializer_Test.cs
Labels: Project: Shared, Review, Type: Feature

#540 MapLoader - Catch Entity Error
  SS14.Server/Maps/MapLoader.cs
Labels: Project: Shared, Review, Type: Feature

#541 BaseServer - Kick Players On Shutdown
  SS14.Server/BaseServer.cs
Labels: Project: Server, Type: Feature
