Repository space-wizards/RobustToolbox, pull requests merged in 2018-12, with the labels that each got.

#719 Unparent transform fix.
  SS14.Server/GameObjects/Components/Container/Container.cs
  SS14.Shared/GameObjects/Components/Transform/TransformComponent.cs
  SS14.UnitTesting/Server/GameObjects/Components/Container_Test.cs
Labels: Project: Shared, System: Entities, Type: Bug, W: Review

#718 Convert PushInheritance to iteration in EntityPrototype
  SS14.Shared/Prototypes/EntityPrototype.cs
Labels: W: Review

#722 Fix Travis
  .travis.yml
Labels: Priority: 1-high, W: In Progress
