Repository space-wizards/RobustToolbox, pull requests merged in 2018-05, with the labels that each got.

#578 Click modifiers
  SS14.Client/Input/Events.cs
  SS14.Client/State/States/GameScreen.cs
  SS14.Shared/Input/ClickType.cs
Labels: W: In Progress

#581 Debug monitor system & UI improvements.
  SS14.Client.Godot/Scenes/DebugCoordsPanel/DebugCoordsPanel.tscn
  SS14.Client/Console/Commands/Debug.cs
  SS14.Client/Graphics/Drawing/StyleBox.cs
  SS14.Client/Graphics/Font.cs
  SS14.Client/Interfaces/UserInterface/IDebugMonitors.cs
  SS14.Client/Interfaces/UserInterface/IUserInterfaceManager.cs
  SS14.Client/ResourceManagement/ResourceTypes/FontResource.cs
  SS14.Client/SS14.Client.csproj
  SS14.Client/UserInterface/Control.cs
  SS14.Client/UserInterface/Controls/HBoxContainer.cs
  SS14.Client/UserInterface/Controls/VBoxContainer.cs
  SS14.Client/UserInterface/CustomControls/DebugCoordsPanel.cs
  SS14.Client/UserInterface/CustomControls/DebugMonitors.cs
  SS14.Client/UserInterface/CustomControls/FPSCounter.cs
  SS14.Client/UserInterface/CustomControls/NetDebugPanel.cs
  SS14.Client/UserInterface/CustomControls/SS14Window.cs
  SS14.Client/UserInterface/UserInterfaceManager.cs
  SS14.UnitTesting/Client/DummyUserInterfaceManager.cs
Labels: Project: Client, W: Review

#583 Fixing some crashes and errors.
  SS14.Client/GameController.cs
  SS14.Client/GameObjects/ClientEntityManager.cs
  SS14.Client/UserInterface/Control.cs
  SS14.Shared/GameObjects/Entity.cs
  SS14.Shared/GameObjects/EntityManager.cs
  SS14.Shared/GameObjects/EntitySystemManager.cs
Labels: Project: Client, System: Entities, System: UI, Type: Bug, W: Review

#585 Logging API cleanup.
  SS14.Client/Console/Commands/LogCommands.cs
  SS14.Server/BaseServer.cs
  SS14.Server/Program.cs
  SS14.Server/ServerConsole/Commands/LogCommands.cs
  SS14.Server/Signals.cs
  SS14.Shared/Interfaces/Log/ISawmill.cs
  SS14.Shared/Log/LogManager.Sawmill.cs
  SS14.Shared/Log/Logger.cs
Labels: Type: Refactor, W: Review

#584 Rename IEntity.GetComponents to GetAllComponents.
  SS14.Client/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Server/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Shared/GameObjects/Entity.cs
  SS14.Shared/Interfaces/GameObjects/IEntity.cs
  SS14.Shared/Physics/CollisionManager.cs
Labels: System: Entities, Type: Refactor, W: Review

#588 Fix GodotSignalSubscriber leakage.
  SS14.Client.Godot/SignalSubscriber/BaseGodotSignalSubscriber.cs
Labels: Dependency: Godot, Project: Client, Type: Bug, W: Review

#590 Input Refactor
  Resources/keybinds.yml
  SS14.Client/GameController.cs
  SS14.Client/GameController/GameController.Input.cs
  SS14.Client/GameObjects/Components/Input/KeybindingInputComponent.cs
  SS14.Client/GameObjects/EntitySystems/InputSystem.cs
  SS14.Client/GameObjects/PlayerMessages.cs
  SS14.Client/Input/BoundKeyEventArgs.cs
  SS14.Client/Input/Events.cs
  SS14.Client/Input/InputDevices.cs
  SS14.Client/Input/InputManager.cs
  SS14.Client/Interfaces/Input/IInputManager.cs
  SS14.Client/Interfaces/Input/IKeyBinding.cs
  SS14.Client/Interfaces/State/IStateManager.cs
  SS14.Client/Interfaces/UserInterface/IUserInterfaceManager.cs
  SS14.Client/KeyBindings.xml
  SS14.Client/Player/LocalPlayer.cs
  SS14.Client/SS14.Client.csproj
  SS14.Client/State/State.cs
  SS14.Client/State/StateManager.cs
  SS14.Client/State/States/GameScreen.cs
  SS14.Client/UserInterface/Control.Input.cs
  SS14.Client/UserInterface/UserInterfaceManager.cs
  SS14.Server/GameObjects/Components/Actor/BasicActorComponent.cs
  SS14.Server/GameObjects/Components/Input/KeyBindingInputComponent.cs
  SS14.Server/GameObjects/Components/Mover/PlayerInputMoverComponent.cs
  SS14.Server/GameObjects/EntitySystems/InputSystem.cs
  SS14.Server/GameObjects/ServerComponentFactory.cs
  SS14.Server/Interfaces/Player/IPlayerInput.cs
  SS14.Server/Interfaces/Player/IPlayerSession.cs
  SS14.Server/Player/PlayerInput.cs
  SS14.Server/Player/PlayerManager.cs
  SS14.Server/Player/PlayerSession.cs
  SS14.Server/SS14.Server.csproj
  SS14.Shared/GameObjects/ComponentMessages/Messages.cs
  SS14.Shared/GameObjects/Components/BoundingBox/BoundingBoxComponentState.cs
  SS14.Shared/GameObjects/Components/Collidable/CollidableComponentState.cs
  SS14.Shared/GameObjects/Components/Light/PointLightComponentState.cs
  SS14.Shared/GameObjects/Components/Particles/ParticleSystemComponentState.cs
  SS14.Shared/GameObjects/Components/Physics/PhysicsComponentState.cs
  SS14.Shared/GameObjects/Components/Renderable/SpriteComponentState.cs
  SS14.Shared/GameObjects/Components/Transform/TransformComponentState.cs
  SS14.Shared/GameObjects/EntitySystemMessages/ClickedOnEntityMessage.cs
  SS14.Shared/GameObjects/EntitySystemMessages/EffectMessage.cs
  SS14.Shared/GameObjects/EntitySystemMessages/InputMessages.cs
  SS14.Shared/GameObjects/EntitySystemMessages/InventorySystemMessages.cs
  SS14.Shared/GameStates/GameState.cs
  SS14.Shared/Input/BoundKeyEventArgs.cs
  SS14.Shared/Input/BoundKeyMap.cs
  SS14.Shared/Input/InputCommand.cs
  SS14.Shared/Input/KeyFunctions.cs
  SS14.Shared/Network/Messages/MsgKeyFunctionChangeState.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.Shared/Serialization/NetSerializableAttribute.cs
Labels: Type: Refactor, W: In Progress

#591 Some entity improvements to work on power code.
  SS14.Server/Player/PlayerManager.cs
  SS14.Shared/GameObjects/Component.cs
  SS14.Shared/GameObjects/Entity.cs
  SS14.Shared/GameObjects/Serialization/YamlEntitySerializer.cs
  SS14.Shared/Interfaces/GameObjects/IEntity.cs
Labels: W: In Progress
