Repository space-wizards/RobustToolbox, pull requests merged in 2018-04, with the labels that each got.

#537 Arbitrary Effects System
  SS14.Client/GameController.cs
  SS14.Client/GameObjects/ClientEntityManager.cs
  SS14.Client/GameObjects/EntitySystems/EffectSystem.cs
  SS14.Client/SS14.Client.csproj
  SS14.Client/State/States/GameScreen.cs
  SS14.Server/GameObjects/EntitySystems/EffectSystem.cs
  SS14.Server/SS14.Server.csproj
  SS14.Server/packages.config
  SS14.Shared/GameObjects/EntityManager.cs
  SS14.Shared/GameObjects/EntitySystemMessages/EffectMessage.cs
  SS14.Shared/Interfaces/Physics/ICollisionManager.cs
  SS14.Shared/Physics/CollisionManager.cs
  SS14.Shared/SS14.Shared.csproj
Labels: Project: Client, Project: Server, Review, System: Rendering

#544 Adds getentititiesinarc
  SS14.Server/GameObjects/ServerEntityManager.cs
  SS14.Server/Interfaces/GameObjects/IServerEntityManager.cs
Labels: W: In Progress

#543 Changes physics and collidables
  SS14.Client/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Server/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Server/GameObjects/Components/Physics/PhysicsComponent.cs
  SS14.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  SS14.Shared/Interfaces/GameObjects/Components/ICollidableComponent.cs
  SS14.Shared/Interfaces/Physics/ICollidable.cs
  SS14.Shared/Physics/CollisionManager.cs
Labels: W: In Progress

#547 Remove broken particle editor.
  SS14.Tools.ParticleEditor/CluwneSprite.cs
  SS14.Tools.ParticleEditor/ColorRangeControl.Designer.cs
  SS14.Tools.ParticleEditor/ColorRangeControl.cs
  SS14.Tools.ParticleEditor/ColorRangeControl.resx
  SS14.Tools.ParticleEditor/ColorSwatch.Designer.cs
  SS14.Tools.ParticleEditor/ColorSwatch.cs
  SS14.Tools.ParticleEditor/ColorSwatch.resx
  SS14.Tools.ParticleEditor/FloatRangeControl.Designer.cs
  SS14.Tools.ParticleEditor/FloatRangeControl.cs
  SS14.Tools.ParticleEditor/FloatRangeControl.resx
  SS14.Tools.ParticleEditor/ParticleConfigurator.Designer.cs
  SS14.Tools.ParticleEditor/ParticleConfigurator.cs
  SS14.Tools.ParticleEditor/ParticleConfigurator.resx
  SS14.Tools.ParticleEditor/ParticleDisplay.Designer.cs
  SS14.Tools.ParticleEditor/ParticleDisplay.cs
  SS14.Tools.ParticleEditor/ParticleDisplay.resx
  SS14.Tools.ParticleEditor/ParticleEditor.resx
  SS14.Tools.ParticleEditor/ParticleEditorMainForm.Designer.cs
  SS14.Tools.ParticleEditor/ParticleEditorMainForm.cs
  SS14.Tools.ParticleEditor/ParticleEditorMainForm.resx
  SS14.Tools.ParticleEditor/Program.cs
  SS14.Tools.ParticleEditor/Properties/AssemblyInfo.cs
  SS14.Tools.ParticleEditor/Properties/DataSources/ParticleSettings.datasource
  SS14.Tools.ParticleEditor/Properties/Resources.Designer.cs
  SS14.Tools.ParticleEditor/Properties/Resources.resx
  SS14.Tools.ParticleEditor/Properties/Settings.Designer.cs
  SS14.Tools.ParticleEditor/Properties/Settings.settings
  SS14.Tools.ParticleEditor/Resources.Designer.cs
  SS14.Tools.ParticleEditor/Resources.resx
  SS14.Tools.ParticleEditor/Resources/cellbackground.bmp
  SS14.Tools.ParticleEditor/SS14.Tools.ParticleEditor.csproj
  SS14.Tools.ParticleEditor/VariedFloatControl.Designer.cs
  SS14.Tools.ParticleEditor/VariedFloatControl.cs
  SS14.Tools.ParticleEditor/VariedFloatControl.resx
  SS14.Tools.ParticleEditor/VariedFloatRangeControl.Designer.cs
  SS14.Tools.ParticleEditor/VariedFloatRangeControl.cs
  SS14.Tools.ParticleEditor/VariedFloatRangeControl.resx
  SS14.Tools.ParticleEditor/VariedVector2Control.Designer.cs
  SS14.Tools.ParticleEditor/VariedVector2Control.cs
  SS14.Tools.ParticleEditor/VariedVector2Control.resx
  SS14.Tools.ParticleEditor/Vector2Control.Designer.cs
  SS14.Tools.ParticleEditor/Vector2Control.cs
  SS14.Tools.ParticleEditor/Vector2Control.resx
  SS14.Tools.ParticleEditor/app.config
  SS14.Tools.ParticleEditor/config.xml
  SS14.Tools.ParticleEditor/star1.png
  star1.png
Labels: Review, Type: Cleanup

#551 Stop building the resource pack on Travis and AppVeyor.
  .appveyor.yml
  .travis.yml
Labels: Review

#549 New logo courtesy of @outbools.
  SS14.Client.Godot/Art/bootsplash.png
  SS14.Client.Godot/Scenes/MainMenu/MainMenu.tscn
Labels: Review

#548 Unit test improvements.
  SS14.Shared/Maths/Angle.cs
  SS14.Shared/Maths/FloatMath.cs
  SS14.Shared/Maths/IApproxEquatable.cs
  SS14.Shared/Maths/Matrix3.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.UnitTesting/ApproxEqualityConstraint.cs
  SS14.UnitTesting/Client/GameObjects/Components/Transform_Test.cs
  SS14.UnitTesting/Client/Utility/GodotConversionsTest.cs
  SS14.UnitTesting/SS14.UnitTesting.csproj
  SS14.UnitTesting/Server/GameObjects/Components/Container_Test.cs
  SS14.UnitTesting/Server/GameObjects/Components/Transform_Test.cs
  SS14.UnitTesting/Shared/ColorUtils_Test.cs
  SS14.UnitTesting/Shared/GameObjects/Serialization/YamlEntitySerializer_Test.cs
  SS14.UnitTesting/Shared/IoC/IoCManager_Test.cs
  SS14.UnitTesting/Shared/Maths/Angle_Test.cs
  SS14.UnitTesting/Shared/Maths/Direction_Test.cs
  SS14.UnitTesting/Shared/Maths/Matrix3_Test.cs
  SS14.UnitTesting/Shared/Maths/Ray_Test.cs
  SS14.UnitTesting/Shared/Maths/Vector2_Test.cs
  SS14.UnitTesting/Shared/Utility/CollectionExtensions_Test.cs
  SS14.UnitTesting/Shared/Utility/YamlHelpers_Test.cs
Labels: Misc: Quality of Life, Review, Type: Feature

#556 Update all NuGet packages.
  SS14.Client/SS14.Client.csproj
  SS14.Client/packages.config
  SS14.Server/Properties/AssemblyInfo.cs
  SS14.Server/SS14.Server.csproj
  SS14.Server/packages.config
  SS14.Shared/Configuration/ConfigurationManager.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.Shared/packages.config
  SS14.UnitTesting/SS14.UnitTesting.csproj
  SS14.UnitTesting/packages.config
Labels: W: In Progress

#562 Remove usage of PitchScale.
  SS14.Client/GameObjects/EntitySystems/AudioSystem.cs
Labels: Project: Client, Type: Bug, W: In Progress

#561 Make handle message use optional arguments
  SS14.Client/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Server/GameObjects/Components/ClickableComponent.cs
  SS14.Server/GameObjects/Components/Container/Container.cs
  SS14.Server/GameObjects/Components/Input/KeyBindingInputComponent.cs
  SS14.Server/GameObjects/Components/Mover/PlayerInputMoverComponent.cs
  SS14.Shared/GameObjects/Component.cs
  SS14.Shared/GameObjects/Entity.cs
  SS14.Shared/Interfaces/GameObjects/IComponent.cs
Labels: W: In Progress

#563 Implements a network function
  SS14.Client/GameObjects/ClientEntityNetworkManager.cs
Labels: W: In Progress

#564 Gridcontainer Wrapper
  SS14.Client/UserInterface/Controls/GridContainer.cs
Labels: Dependency: Godot, Status: Requesting Merge

#574 Companion PR
  SS14.Client/KeyBindings.xml
  SS14.Client/UserInterface/Controls/TextureRect.cs
  SS14.Shared/Input/KeyFunctions.cs
Labels: W: In Progress

#573 PJB will love this
  SS14.Server/GameObjects/Components/Container/Container.cs
  SS14.Server/GameObjects/Components/Container/ContainerManagerComponent.cs
  SS14.Shared/Interfaces/GameObjects/Components/IContainer.cs
  SS14.UnitTesting/Server/GameObjects/Components/Container_Test.cs
Labels: System: Entities, Type: Refactor, W: In Progress
