Repository space-wizards/RobustToolbox, pull requests merged in 2019-11, with the labels that each got.

#884 Code smell for loop braces
  Robust.Client/Console/Commands/Debug.cs
  Robust.Server/Maps/YamlGridSerializer.cs
  Robust.Shared/Map/MapChunk.cs
  Robust.Shared/Map/MapManager.Network.cs
Labels: Type: Cleanup

#892 Add a DebugDrawingManager for drawing server side events like Ra…
  Robust.Client/BaseClient.cs
  Robust.Client/ClientIoC.cs
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/Debugging/DebugDrawingManager.cs
  Robust.Client/Interfaces/Debugging/IDebugDrawingManager.cs
  Robust.Server/BaseServer.cs
  Robust.Server/Debugging/DebugDrawingManager.cs
  Robust.Server/Interfaces/Debugging/IDebugDrawingManager.cs
  Robust.Server/Robust.Server.csproj
  Robust.Server/ServerIoC.cs
  Robust.Shared/Network/Messages/MsgRay.cs
  Robust.Shared/Physics/PhysicsManager.cs
Labels: Misc: Quality of Life, Type: Feature

#904 Shared IMap/Map class removal
  Robust.Client/Graphics/ClientEye/EyeManager.cs
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Placement/Modes/AlignTileAny.cs
  Robust.Client/Placement/PlacementManager.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/Console/Commands/PlayerCommands.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/Interfaces/Maps/IMapLoader.cs
  Robust.Server/Interfaces/Timing/IPauseManager.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Server/Maps/YamlGridSerializer.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Server/Timing/PauseManager.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/Interfaces/Map/IMap.cs
  Robust.Shared/Interfaces/Map/IMapManager.cs
  Robust.Shared/Map/Coordinates.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapManager.Map.cs
  Robust.Shared/Map/MapManager.Network.cs
  Robust.Shared/Map/MapManager.cs
  Robust.UnitTesting/Client/GameObjects/Components/Transform_Test.cs
  Robust.UnitTesting/Server/GameObjects/Components/Transform_Test.cs
Labels: Project: Shared, Type: Refactor
