Repository space-wizards/RobustToolbox, pull requests merged in 2019-03, with the labels that each got.

#743 Fix viewport size on window creation for OS-imposed sizes
  SS14.Client/Graphics/Clyde/Clyde.cs
Labels: W: In Progress

#759 Runtime Log & Exception Catching.
  SS14.Client/GameController/GameController.IoC.cs
  SS14.Server/BaseServer.cs
  SS14.Server/Program.cs
  SS14.Shared/Exceptions/RuntimeLog.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.Shared/Timing/GameLoop.cs
  SS14.UnitTesting/SS14UnitTest.cs
Labels: Type: Feature, W: In Progress

#760 Error/Hint when using RSIs as texture in SpriteComponent
  SS14.Client/GameObjects/Components/Renderable/SpriteComponent.cs
Labels: W: In Progress

#761 [Ready] Fix server runtimes log exception
  SS14.Server/BaseServer.cs
Labels: W: In Progress

#762 Remove SS14.Shared.Bsdiff from submodules.
  .gitmodules
Labels: W: In Progress

#763 Expose a readonly version of YamlObjectSerializer's TypeSerializer dict.
  SS14.Shared/Serialization/YamlObjectSerializer.cs
Labels: W: In Progress

#765 Implements move disabler
  SS14.Server/GameObjects/Components/Mover/PlayerInputMoverComponent.cs
  SS14.Server/GameObjects/EntitySystems/MoverSystem.cs
Labels: W: In Progress

#768 AudioParams can be defined in YAML now
  SS14.Shared/Audio/AudioParams.cs
Labels: W: In Progress

#767 Establish standard format for runtime log naming and future-proof it until the human race perishes
  SS14.Server/BaseServer.cs
Labels: W: In Progress

#769 Adds a frame counter to timing debug monitor
  SS14.Client/GameController/GameController.Godot.cs
  SS14.Client/GameController/GameController.Standalone.cs
  SS14.Client/UserInterface/CustomControls/DebugTimePanel.cs
  SS14.Shared/Interfaces/Timing/IGameTiming.cs
  SS14.Shared/Timing/GameTiming.cs
Labels: W: In Progress

#773 NetManager connection handshake improvement.
  Lidgren.Network/NetUtility.cs
  Resources/Scenes/MainMenu/MainMenu.tscn
  SS14.Client/State/States/MainMenu.cs
  SS14.Shared/Interfaces/Network/IClientNetManager.cs
  SS14.Shared/Network/NetChannelArgs.cs
  SS14.Shared/Network/NetManager.ClientConnect.cs
  SS14.Shared/Network/NetManager.cs
  SS14.Shared/SS14.Shared.csproj
Labels: Priority: 3-low, System: Networking, Type: Refactor, W: In Progress

#774 Fix lights going weird when resizing the window
  SS14.Client/Graphics/Clyde/Clyde.cs
Labels: Priority: 1-high, Project: Client, System: Rendering, Type: Bug, W: In Progress

#775 Fixes server exceptions from #773
  SS14.Shared/Network/NetManager.cs
Labels: Priority: 1-high, Project: Server, System: Networking, Type: Bug, W: In Progress
