Repository space-wizards/RobustToolbox, pull requests merged in 2019-04, with the labels that each got.

#778 Refactor tile IDs.
  SS14.Client/GameController.cs
  SS14.Client/Map/GodotTileDefinitionManager.cs
  SS14.Client/UserInterface/CustomControls/TileSpawnWindow.cs
  SS14.Server/BaseServer.cs
  SS14.Server/Maps/MapLoader.cs
  SS14.Server/Maps/YamlGridSerializer.cs
  SS14.Shared/Interfaces/Map/ITileDefinition.cs
  SS14.Shared/Interfaces/Map/ITileDefinitionManager.cs
  SS14.Shared/Map/DefaultTileDefinitions.cs
  SS14.Shared/Map/TileDefinition.cs
  SS14.Shared/Map/TileDefinitionManager.cs
  SS14.Shared/SS14.Shared.csproj
  docs/Map Format.md
Labels: W: In Progress

#777 Prettyfying README.MD
  readme.md
Labels: W: Review

#779 Rework entity initialization.
  SS14.Client/GameObjects/ClientEntityManager.cs
  SS14.Server/BaseServer.cs
  SS14.Server/GameObjects/ServerEntityManager.cs
  SS14.Server/Interfaces/GameObjects/IServerEntityManagerInternal.cs
  SS14.Server/Maps/MapLoader.cs
  SS14.Shared/GameObjects/EntityManager.cs
  SS14.Shared/Interfaces/GameObjects/IEntityFinishContext.cs
  SS14.Shared/Interfaces/GameObjects/IEntityLoadContext.cs
  SS14.Shared/Interfaces/GameObjects/IEntityManager.cs
  SS14.Shared/Prototypes/EntityPrototype.cs
  SS14.Shared/SS14.Shared.csproj
Labels: W: In Progress

#776 Initial Discord Rich presence
  SS14.Client/BaseClient.cs
  SS14.Client/GameController.cs
  SS14.Client/GameController/GameController.IoC.cs
  SS14.Client/Interfaces/Utility/IDiscordRichPresence.cs
  SS14.Client/SS14.Client.csproj
  SS14.Client/Utility/DiscordRichPresence.cs
  SS14.UnitTesting/SS14UnitTest.cs
Labels: W: Review

#781 Implement ItemLists.
  SS14.Client/UserInterface/Controls/ItemList.cs
Labels: W: In Progress

#782 Implemented IEquatable on Angle
  SS14.Shared.Maths/Angle.cs
Labels: W: Review

#783 Entitiy Queries & TypeFactory
  SS14.Client/Console/Commands/Debug.cs
  SS14.Client/GameController/GameController.IoC.cs
  SS14.Server/Program.cs
  SS14.Shared/GameObjects/ComponentManager.cs
  SS14.Shared/GameObjects/Entity.cs
  SS14.Shared/GameObjects/EntityManager.cs
  SS14.Shared/GameObjects/EntityQuery.cs
  SS14.Shared/GameObjects/EntitySystemManager.cs
  SS14.Shared/Interfaces/GameObjects/IComponentManager.cs
  SS14.Shared/Interfaces/GameObjects/IEntity.cs
  SS14.Shared/Interfaces/GameObjects/IEntityManager.cs
  SS14.Shared/Interfaces/GameObjects/IEntityQuery.cs
  SS14.Shared/IoC/DependencyCollection.cs
  SS14.Shared/IoC/DynamicTypeFactory.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.UnitTesting/SS14UnitTest.cs
Labels: Project: Shared, System: Entities, Type: Feature, Type: Performance, W: Review

#786 Rendering order now done by who was last dirty instead of Uid
  SS14.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  SS14.Client/Graphics/Clyde/Clyde.GridRendering.cs
  SS14.Client/Graphics/Clyde/Clyde.Rendering.cs
  SS14.Server/GameObjects/Components/Renderable/SpriteComponent.cs
  SS14.Shared.Maths/RandomExtensions.cs
  SS14.Shared/GameObjects/Components/Renderable/SharedSpriteComponent.cs
Labels: W: In Progress

#785 Locker shoving
  SS14.Server/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Server/GameObjects/Components/Physics/PhysicsComponent.cs
  SS14.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  SS14.Server/SS14.Server.csproj
  SS14.Shared/Interfaces/Map/ITileDefinition.cs
  SS14.Shared/Interfaces/Physics/IPhysicsManager.cs
  SS14.Shared/Physics/PhysicsManager.cs
  SS14.UnitTesting/Shared/Physics/CollisionManager_Test.cs
Labels: W: Review

#790 Remove chat from the engine.
  Resources/Scenes/ChatBox/ChatBox.tscn
  SS14.Client/Console/ClientChatConsole.cs
  SS14.Client/Console/ClientConsole.cs
  SS14.Client/Console/Commands/ConsoleCommands.cs
  SS14.Client/Console/Commands/Debug.cs
  SS14.Client/Console/IClientChatConsole.cs
  SS14.Client/GameController.cs
  SS14.Client/GameController/GameController.IoC.cs
  SS14.Client/Input/EngineContexts.cs
  SS14.Client/Interfaces/Console/IDebugConsole.cs
  SS14.Client/SS14.Client.csproj
  SS14.Client/UserInterface/CustomControls/Chatbox.cs
  SS14.Client/UserInterface/CustomControls/DebugConsole.cs
  SS14.Server/BaseServer.cs
  SS14.Server/Chat/ChatManager.cs
  SS14.Server/Console/Commands/ChatCommands.cs
  SS14.Server/Interfaces/Chat/IChatCommand.cs
  SS14.Server/Interfaces/Chat/IChatManager.cs
  SS14.Server/Program.cs
  SS14.Server/SS14.Server.csproj
  SS14.Shared/Console/ChatChannel.cs
  SS14.Shared/GameObjects/ComponentMessages/Messages.cs
  SS14.Shared/Input/KeyFunctions.cs
  SS14.Shared/Network/Messages/MsgChat.cs
  SS14.Shared/Network/NetMessageExt.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.UnitTesting/SS14UnitTest.cs
Labels: W: In Progress

#791 Change config system so you can get notified on config changes.
  SS14.Client/Console/Commands/ConfigurationCommands.cs
  SS14.Client/Graphics/Clyde/Clyde.cs
  SS14.Client/Graphics/DisplayManager.cs
  SS14.Client/Graphics/DisplayManagerGodot.cs
  SS14.Client/Graphics/DisplayManagerHeadless.cs
  SS14.Client/Interfaces/Graphics/IDisplayManager.cs
  SS14.Client/SS14.Client.csproj
  SS14.Client/UserInterface/CustomControls/OptionsMenu.cs
  SS14.Server/Console/Commands/CVarCommand.cs
  SS14.Server/SS14.Server.csproj
  SS14.Shared/Configuration/ConfigurationCommands.cs
  SS14.Shared/Configuration/ConfigurationManager.cs
  SS14.Shared/Interfaces/Configuration/IConfigurationManager.cs
  SS14.Shared/Network/NetManager.cs
  SS14.Shared/SS14.Shared.csproj
Labels: W: In Progress

#787 Actual lockers
  SS14.Client/GameObjects/ClientComponentFactory.cs
  SS14.Client/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Server/GameObjects/Components/Collidable/CollidableComponent.cs
  SS14.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  SS14.Shared.Maths/SS14.Shared.Maths.csproj
  SS14.Shared/GameObjects/ComponentMessages/Messages.cs
  SS14.Shared/GameObjects/EntityQuery.cs
  SS14.Shared/Interfaces/Physics/ICollidable.cs
  SS14.Shared/Physics/PhysicsManager.cs
  SS14.Shared/Physics/Ray.cs
  SS14.Shared/SS14.Shared.csproj
  SS14.UnitTesting/Shared/Maths/Ray_Test.cs
  SS14.UnitTesting/Shared/Physics/CollisionManager_Test.cs
Labels: W: In Progress

#792 Quick fix for wall draw depth being above the player
  SS14.Shared/GameObjects/ComponentEnums.cs
Labels: W: In Progress

#794 ECS Event Bus Queue
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/Systems/EntitySystem.cs
  Robust.Shared/Interfaces/GameObjects/IEntityManager.cs
Labels: W: In Progress

#795 Tick Logic Timing and Bandwidth Improvements
  Robust.Client/GameObjects/Components/Physics/PhysicsComponent.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Server/GameObjects/Components/Physics/PhysicsComponent.cs
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Shared/GameObjects/Components/Physics/PhysicsComponentState.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/Map/MapManager.Network.cs
  Robust.Shared/Timing/GameTiming.cs
  Robust.UnitTesting/ApproxEqualityConstraint.cs
  Robust.UnitTesting/Server/GameObjects/Components/Transform_Test.cs
  Robust.UnitTesting/Shared/Timing/GameLoop_Test.cs
Labels: W: In Progress

#796 Map System Code Refactor
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Client/GameObjects/EntitySystems/EffectSystem.cs
  Robust.Client/Map/ClydeTileDefinitionManager.cs
  Robust.Client/Map/GodotMapManager.cs
  Robust.Client/Placement/Modes/AlignSimilar.cs
  Robust.Client/Placement/Modes/AlignSnapgridBorder.cs
  Robust.Client/Placement/Modes/AlignSnapgridCenter.cs
  Robust.Client/Placement/Modes/AlignTileAny.cs
  Robust.Client/Placement/Modes/AlignTileDense.cs
  Robust.Client/Placement/Modes/AlignTileEmpty.cs
  Robust.Client/Placement/Modes/AlignTileNonDense.cs
  Robust.Client/Placement/Modes/AlignWall.cs
  Robust.Client/Placement/Modes/PlaceFree.cs
  Robust.Client/Placement/Modes/PlaceNearby.cs
  Robust.Client/Placement/PlacementManager.cs
  Robust.Client/Placement/PlacementMode.cs
  Robust.Client/Player/PlayerManager.cs
  Robust.Client/State/States/GameScreen.cs
  Robust.Client/UserInterface/CustomControls/DebugCoordsPanel.cs
  Robust.Client/UserInterface/CustomControls/DebugMonitors.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/Console/Commands/PlayerCommands.cs
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/Maps/YamlGridSerializer.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Server/Player/PlayerManager.cs
  Robust.Server/Timing/PauseManager.cs
  Robust.Shared.Maths/Box2.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/Interfaces/Map/IMapGrid.cs
  Robust.Shared/Map/Coordinates.cs
  Robust.Shared/Map/MapIndices.cs
  Robust.Shared/Map/MapManager.Chunk.cs
  Robust.Shared/Map/MapManager.Map.cs
  Robust.Shared/Map/MapManager.MapGrid.cs
  Robust.Shared/Map/MapManager.Network.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Map/Tile.cs
  Robust.Shared/Map/TileRef.cs
  Robust.UnitTesting/Shared/Maths/Box2_Test.cs
Labels: Project: Shared, Type: Cleanup, Type: Refactor, W: In Progress

#797 ItemLists now have a scrollbar and can be scrolled with the mouse wheel as well.
  Robust.Client/UserInterface/Controls/ItemList.cs
Labels: W: In Progress

#798 EntityStates
  Robust.Client/BaseClient.cs
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/Interfaces/GameStates/IClientGameStateManager.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Interfaces/GameState/IServerGameStateManager.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
  Robust.Shared/GameObjects/Components/NetIDs.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/EntityState.cs
  Robust.Shared/Interfaces/GameObjects/IComponent.cs
  Robust.Shared/Interfaces/GameObjects/IEntity.cs
  Robust.Shared/Prototypes/EntityPrototype.cs
  Robust.Shared/Robust.Shared.csproj
  Robust.UnitTesting/Robust.UnitTesting.csproj
  Robust.UnitTesting/RobustUnitTest.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
Labels: W: In Progress

#799 MetaDataComponent and the ExposeData Bug
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
Labels: W: In Progress

#800 Grid Bounds
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameObjects/EntitySystems/EffectSystem.cs
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Placement/Modes/AlignSimilar.cs
  Robust.Client/Placement/Modes/AlignTileAny.cs
  Robust.Client/Placement/Modes/AlignTileDense.cs
  Robust.Client/Placement/Modes/AlignTileEmpty.cs
  Robust.Client/Placement/Modes/AlignTileNonDense.cs
  Robust.Client/Placement/Modes/AlignWall.cs
  Robust.Client/Placement/Modes/PlaceFree.cs
  Robust.Client/Placement/Modes/PlaceNearby.cs
  Robust.Client/Placement/PlacementManager.cs
  Robust.Client/Placement/PlacementMode.cs
  Robust.Client/State/States/GameScreen.cs
  Robust.Client/UserInterface/CustomControls/DebugCoordsPanel.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/Maps/YamlGridSerializer.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Shared.Maths/Box2.cs
  Robust.Shared.Maths/Box2i.cs
  Robust.Shared/Interfaces/Map/IMapChunk.cs
  Robust.Shared/Map/IMapChunk.cs
  Robust.Shared/Map/IMapChunkInternal.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/IMapGridInternal.cs
  Robust.Shared/Map/IMapManagerInternal.cs
  Robust.Shared/Map/MapChunk.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapIndices.cs
  Robust.Shared/Map/MapManager.Chunk.cs
  Robust.Shared/Map/MapManager.Map.cs
  Robust.Shared/Map/MapManager.MapGrid.cs
  Robust.Shared/Map/MapManager.Network.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Map/TileRef.cs
  Robust.Shared/Prototypes/EntityPrototype.cs
  Robust.Shared/Robust.Shared.csproj
  Robust.UnitTesting/Client/GameObjects/Components/Transform_Test.cs
  Robust.UnitTesting/Robust.UnitTesting.csproj
  Robust.UnitTesting/Shared/Map/MapChunk_Tests.cs
  Robust.UnitTesting/Shared/Map/MapGrid_Tests.cs
  Robust.UnitTesting/Shared/Maths/Box2i_Test.cs
Labels: Project: Shared, Type: Refactor, W: In Progress

#801 Map Init & Map Loading improvements.
  Robust.Client/Placement/PlacementManager.cs
  Robust.Client/Player/LocalPlayer.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/Interfaces/GameObjects/IMapInit.cs
  Robust.Server/Interfaces/Timing/IPauseManager.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Server/Robust.Server.csproj
  Robust.Server/Timing/PauseManager.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
  Robust.Shared/Interfaces/Map/IMapManager.cs
  Robust.Shared/Map/MapManager.cs
  docs/Map Format.md
Labels: W: In Progress
