Repository space-wizards/RobustToolbox, pull requests merged in 2019-09, with the labels that each got.

#847 Physics Shapes
  Robust.Client/Debugging/DebugDrawing.cs
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameObjects/Components/BoundingBox/BoundingBoxComponent.cs
  Robust.Client/GameObjects/Components/Collidable/CollidableComponent.cs
  Robust.Client/GameObjects/Components/Input/ClickableComponent.cs
  Robust.Client/GameObjects/Components/Physics/PhysicsComponent.cs
  Robust.Client/GameStates/NetInterpOverlay.cs
  Robust.Client/Interfaces/Debugging/IDebugDrawing.cs
  Robust.Client/Interfaces/GameObjects/Components/IClientClickableComponent.cs
  Robust.Client/State/States/GameScreen.cs
  Robust.Server/GameObjects/Components/ClickableComponent.cs
  Robust.Server/GameObjects/Components/Collidable/CollidableComponent.cs
  Robust.Server/GameObjects/Components/Physics/PhysicsComponent.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Shared.Maths/Box2Rotated.cs
  Robust.Shared/GameObjects/Components/BoundingBox/BoundingBoxComponent.cs
  Robust.Shared/GameObjects/Components/ClickableComponentState.cs
  Robust.Shared/GameObjects/Components/Collidable/CollidableComponentState.cs
  Robust.Shared/GameObjects/Components/NetIDs.cs
  Robust.Shared/Interfaces/GameObjects/Components/ICollidableComponent.cs
  Robust.Shared/Interfaces/Physics/IPhysicsManager.cs
  Robust.Shared/Interfaces/Reflection/IReflectionManager.cs
  Robust.Shared/Physics/BodyType.cs
  Robust.Shared/Physics/IPhysBody.cs
  Robust.Shared/Physics/IPhysShape.cs
  Robust.Shared/Physics/PhysShapeAabb.cs
  Robust.Shared/Physics/PhysShapeRect.cs
  Robust.Shared/Physics/PhysicsManager.cs
  Robust.Shared/Reflection/ReflectionManager.cs
  Robust.Shared/Serialization/YamlObjectSerializer.cs
  Robust.UnitTesting/Shared/Physics/CollisionManager_Test.cs
Labels: Project: Shared, Type: Feature, Type: Refactor

#860 ClientEye Refactor
  Robust.Client/GameObjects/Components/Eye/EyeComponent.cs
  Robust.Client/GameObjects/EntitySystems/EyeUpdateSystem.cs
  Robust.Client/Graphics/ClientEye/Eye.cs
  Robust.Client/Graphics/ClientEye/EyeManager.cs
  Robust.Client/Interfaces/Graphics/ClientEye/IEye.cs
  Robust.Client/Interfaces/Graphics/ClientEye/IEyeManager.cs
Labels: Area: Rendering, Project: Client, Type: Cleanup

#864 Use DynamicMethod for dependency injection.
  Robust.Shared/IoC/DependencyCollection.cs
  Robust.Shared/IoC/IDependencyCollection.cs
  Robust.UnitTesting/Shared/IoC/IoCManager_Test.cs
Labels: Type: Performance

#863 Improved ItemLists
  Robust.Client/UserInterface/Controls/ItemList.cs
  Robust.Client/UserInterface/CustomControls/TileSpawnWindow.cs
Labels: Area: UI, Type: Refactor

#866 Implemented SpinBox and added a filter to LineEdit
  Robust.Client/UserInterface/Controls/LineEdit.cs
  Robust.Client/UserInterface/Controls/SpinBox.cs
Labels: Area: UI, Type: Feature

#867 Property animations track
  Robust.Client/Animations/Animation.cs
  Robust.Client/Animations/AnimationTrack.cs
  Robust.Client/Animations/AnimationTrackComponentProperty.cs
  Robust.Client/Animations/AnimationTrackPlaySound.cs
  Robust.Client/Animations/AnimationTrackProperty.cs
  Robust.Client/Animations/AnimationTrackSpriteFlick.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/Interfaces/GameObjects/Components/ISpriteComponent.cs
  Robust.Client/Robust.Client.csproj
  Robust.Shared.Maths/FloatMath.cs
  Robust.Shared.Maths/Vector2.cs
  Robust.Shared.Maths/Vector3.cs
  Robust.Shared.Maths/Vector4.cs
  Robust.Shared/Animations/AnimatableAttribute.cs
  Robust.Shared/Animations/AnimationHelper.cs
  Robust.Shared/Animations/AnimationInterpolationMode.cs
  Robust.Shared/Animations/IAnimationProperties.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/Interfaces/GameObjects/Components/ITransformComponent.cs
Labels: Type: Feature

#871 Remove some unecessary NuGet dependencies.
  Robust.Client/Graphics/Clyde/Clyde.cs
  Robust.Client/Robust.Client.csproj
  Robust.Server/Robust.Server.csproj
  Robust.Shared.Maths/Robust.Shared.Maths.csproj
  Robust.Shared/Robust.Shared.csproj
  Robust.UnitTesting/Robust.UnitTesting.csproj
Labels: Type: Cleanup
