Repository space-wizards/RobustToolbox, pull requests merged in 2019-05, with the labels that each got.

#803 Disable Extrapolation
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/GameStates/GameStateProcessor.cs
  Robust.Client/GameStates/IGameStateProcessor.cs
  Robust.Client/Robust.Client.csproj
  Robust.UnitTesting/Client/GameStates/GameStateProcessor_Tests.cs
  Robust.UnitTesting/Robust.UnitTesting.csproj
Labels: W: In Progress

#804 Integration Testing Framework.
  Robust.Client/GameController/GameController.Godot.cs
  Robust.Client/GameController/GameController.Standalone.cs
  Robust.Client/ResourceManagement/ResourceCache.cs
  Robust.Client/Utility/DiscordRichPresence.cs
  Robust.Server/BaseServer.cs
  Robust.Server/CommandLineArgs.cs
  Robust.Server/Console/SystemConsoleManager.cs
  Robust.Server/Interfaces/IBaseServer.cs
  Robust.Server/Interfaces/ICommandLineArgs.cs
  Robust.Server/Program.cs
  Robust.Shared/Exceptions/RuntimeLog.cs
  Robust.Shared/IoC/IoCManager.cs
  Robust.Shared/Robust.Shared.csproj
  Robust.Shared/Timing/GameLoop.cs
  Robust.Shared/Timing/GameTiming.cs
  Robust.Shared/Utility/ManualResetEventExt.cs
  Robust.UnitTesting/Robust.UnitTesting.csproj
  Robust.UnitTesting/RobustIntegrationTest.cs
  Robust.UnitTesting/RobustUnitTest.cs
  Robust.UnitTesting/Shared/Timing/GameLoop_Test.cs
  Robust.UnitTesting/Shared/Timing/GameTiming_Test.cs
Labels: W: In Progress

#808 Tile Placement Improvements
  Robust.Client/Graphics/ClientEye/EyeManager.cs
  Robust.Client/Placement/Modes/AlignSimilar.cs
  Robust.Client/Placement/Modes/AlignSnapgridBorder.cs
  Robust.Client/Placement/Modes/AlignSnapgridCenter.cs
  Robust.Client/Placement/Modes/AlignTileAny.cs
  Robust.Client/Placement/Modes/AlignTileDense.cs
  Robust.Client/Placement/Modes/AlignTileEmpty.cs
  Robust.Client/Placement/Modes/AlignTileNonDense.cs
  Robust.Client/Placement/Modes/AlignWall.cs
  Robust.Client/Placement/Modes/PlaceFree.cs
  Robust.Client/Placement/Modes/PlaceNearby.cs
  Robust.Client/Placement/PlacementMode.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/MapGrid.cs
Labels: Type: Feature

#814 Deleting AttachedEntity Crash Fix
  Robust.Server/GameObjects/Components/Actor/BasicActorComponent.cs
  Robust.Server/Player/PlayerSession.cs
Labels: Project: Client, Type: Bug

#815 Create Entities Without Prototypes
  Robust.Shared/GameObjects/ComponentManager.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/Interfaces/GameObjects/IComponentManager.cs
  Robust.Shared/Interfaces/GameObjects/IEntityManager.cs
  Robust.Shared/Prototypes/EntityPrototype.cs
  Robust.UnitTesting/Robust.UnitTesting.csproj
  Robust.UnitTesting/Shared/GameObjects/ComponentManager_Tests.cs
Labels: Project: Shared, System: Entities, Type: Feature
