Repository space-wizards/RobustToolbox, pull requests merged in 2019-10, with the labels that each got.

#877 Add BufferedAudioSource to Clyde.Audio
  Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Interfaces/Graphics/IClyde.cs
Labels: Area: Clyde, Type: Feature

#876 Delete some dead code.
  Robust.Client/Interfaces/GameObjects/IParticleSystemComponent.cs
  Robust.Server/GameObjects/Components/Particles/ParticleSystemComponent.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Server/Interfaces/GameObjects/IParticleSystemComponent.cs
  Robust.Shared/GameObjects/Components/NetIDs.cs
  Robust.Shared/GameObjects/Components/Particles/ParticleSystemComponentState.cs
  Robust.Shared/GameObjects/ParticleSettings.cs
  Robust.Shared/Utility/ManualResetEventExt.cs
  Robust.Shared/Utility/NetParamsPacker.cs
  Robust.Shared/Utility/PlatformDetector.cs
  Robust.Shared/Utility/RandomString.cs
  Robust.Shared/Utility/Range.cs
  Robust.Shared/Utility/unZipString.cs
Labels: Type: Cleanup

#881 Scrollbars properly handle clicks
  Robust.Client/UserInterface/Controls/ScrollBar.cs
Labels: Type: Bug
