Repository space-wizards/RobustToolbox, pull requests merged in 2020-02, with the labels that each got.

#954 Makes spawnlist use prototype ID if prototype name is null or empty
  Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs
Labels: Area: UI, Misc: Quality of Life, Type: Feature

#963 Physics fixes
  Robust.Shared/GameObjects/Components/Collidable/CollidableComponent.cs
  Robust.Shared/GameObjects/Components/Collidable/ICollidableComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/Interfaces/Physics/IPhysicsManager.cs
  Robust.Shared/Physics/DynamicTree.cs
  Robust.Shared/Physics/PhysicsManager.cs
Labels: Type: Bug

#978 Game state netcode improvements
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
  Robust.Shared/Network/Messages/MsgState.cs
  Robust.Shared/Network/NetManager.cs
  Robust.Shared/Network/NetMessage.cs
Labels: Area: Networking, Type: Performance

#975 Implement ContainerButton and refactor buttons
  Robust.Client/State/States/MainMenu.cs
  Robust.Client/UserInterface/Control.Styling.cs
  Robust.Client/UserInterface/Controls/BaseButton.cs
  Robust.Client/UserInterface/Controls/Button.cs
  Robust.Client/UserInterface/Controls/CheckBox.cs
  Robust.Client/UserInterface/Controls/ContainerButton.cs
  Robust.Client/UserInterface/Controls/Label.cs
  Robust.Client/UserInterface/Controls/MenuBar.cs
  Robust.Client/UserInterface/Controls/OptionButton.cs
  Robust.Client/UserInterface/Controls/Popup.cs
  Robust.Client/UserInterface/Controls/TextureRect.cs
  Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs
  Robust.Client/UserInterface/CustomControls/OptionsMenu.cs
  Robust.Client/ViewVariables/Instances/ViewVariablesInstanceEntity.cs
Labels: Area: UI, Project: Client, Type: Feature, Type: Refactor

#985 Key name API, slight input manager cleanup.
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Input/ClydeInputManager.cs
  Robust.Client/Input/InputDevices.cs
  Robust.Client/Input/InputManager.cs
  Robust.Client/Interfaces/Graphics/IClydeInternal.cs
  Robust.Client/Interfaces/Input/IInputManager.cs
  Robust.Client/Interfaces/Input/IKeyBinding.cs
  Robust.Shared/Utility/FormattedMessage.cs
Labels: Type: Feature

#989 EntitySystem Event Refactor
  Robust.Client/GameObjects/ClientEntityNetworkManager.cs
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Client/GameObjects/EntitySystems/EffectSystem.cs
  Robust.Client/GameObjects/EntitySystems/InputSystem.cs
  Robust.Client/Player/LocalPlayer.cs
  Robust.Server/GameObjects/Components/Container/Container.cs
  Robust.Server/GameObjects/EntitySystems/ContainerSystem.cs
  Robust.Server/GameObjects/EntitySystems/InputSystem.cs
  Robust.Server/GameObjects/ServerEntityNetworkManager.cs
  Robust.Server/Player/PlayerSession.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityEventBus.cs
  Robust.Shared/GameObjects/EntityEvents.cs
  Robust.Shared/GameObjects/EntitySystemManager.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EntitySystemMessage.cs
  Robust.Shared/GameObjects/Systems/EntitySystem.cs
  Robust.Shared/Interfaces/GameObjects/IEntity.cs
  Robust.Shared/Interfaces/GameObjects/IEntitySystemManager.cs
  Robust.Shared/Interfaces/GameObjects/Systems/IEntitySystem.cs
  Robust.Shared/Network/Messages/MsgEntity.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBus_Tests.cs
Labels: Area: Entities, Project: Shared, Type: Refactor
