Repository space-wizards/RobustToolbox, pull requests merged in 2020-07, with the labels that each got.

#1163 Merged Client and Server PhysicsComponent
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Client/GameObjects/Components/Physics/PhysicsComponent.cs
  Robust.Client/Physics/PhysicsSystem.cs
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Shared/GameObjects/Components/Collidable/CollidableComponent.cs
  Robust.Shared/GameObjects/Components/Physics/PhysicsComponent.cs
  Robust.Shared/GameObjects/Components/Physics/PhysicsComponentState.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/Interfaces/Physics/IPhysicsManager.cs
  Robust.Shared/Physics/SharedPhysicsComponent.cs
  Robust.Shared/Physics/VirtualController.cs
  Robust.Shared/Robust.Shared.csproj.DotSettings
Labels: Project: Shared, Type: Refactor

#1132 Input Handling + other cleanups to support click drag functionality
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/GameObjects/EntitySystems/InputSystem.cs
  Robust.Client/Graphics/RSI/RSI.cs
  Robust.Client/Input/InputManager.cs
  Robust.Client/Interfaces/Input/IInputManager.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
  Robust.Server/Interfaces/Player/IPlayerInput.cs
  Robust.Shared/Input/Binding/InputCmdHandler.cs
Labels: Type: Feature

#1189 Allow one VirtualController in CollidableComponent per individual type
  Robust.Shared/GameObjects/Components/Collidable/CollidableComponent.Collision.cs
  Robust.Shared/GameObjects/Components/Collidable/CollidableComponent.Physics.cs
  Robust.Shared/GameObjects/Components/Physics/PhysicsComponent.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/Physics/VirtualController.cs
Labels: Area: Entities, Type: Refactor

#1188 Refactor DetachParent
  Robust.Server/Console/Commands/PlayerCommands.cs
  Robust.Server/GameObjects/Components/Container/Container.cs
  Robust.Shared/Containers/ContainerHelpers.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/Interfaces/GameObjects/Components/ITransformComponent.cs
  Robust.UnitTesting/Server/GameObjects/Components/Container_Test.cs
  Robust.UnitTesting/Server/GameObjects/Components/Transform_Test.cs
Labels: Area: Entities, Type: Refactor
