Repository space-wizards/RobustToolbox, pull requests merged in 2020-08, with the labels that each got.

#1211 Fix OpenCentered by setting size before position
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/Console/Commands/Scripting.cs
  Robust.Client/UserInterface/CustomControls/BaseWindow.cs
  Robust.Client/UserInterface/CustomControls/SS14Window.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
Labels: Feature: UI, Project: Client, Type: Bug

#1217 Change BaseWindow and SS14Window to open where they previously closed
  Robust.Client/UserInterface/CustomControls/BaseWindow.cs
  Robust.Client/UserInterface/CustomControls/SS14Window.cs
Labels: Feature: UI, Type: Bug

#1216 Add ContainerHelpers IsInSameOrNoContainer method
  Robust.Shared/Containers/ContainerHelpers.cs
Labels: Feature: Entities, Type: Feature

#1212 Added Console Tab Completion
  Robust.Client/UserInterface/CustomControls/DebugConsole.cs
Labels: Feature: UI, Misc: Quality of Life, Type: Feature

#1213 Add NetSerializer HashSet test
  Robust.UnitTesting/Shared/Serialization/NetSerializer_Test.cs
Labels: Feature: Networking

#1214 Add NetSerializer dictionary test
  Robust.UnitTesting/Shared/Serialization/NetSerializer_Test.cs
Labels: Feature: Networking

#1192 Fix melee audio on entity destruction
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
Labels: Type: Bug

#1222 Fix input handling and stop input when a cmd returns true
  Robust.Client/GameObjects/EntitySystems/InputSystem.cs
  Robust.Shared/Input/Binding/InputCmdHandler.cs
Labels: Type: Bug

#1235 Fix physics bodies not being woken up when changing a controller's velocity
  Robust.Shared/Physics/VirtualController.cs
Labels: Type: Bug

#1242 Replace not null assert in basic actor component with an operator
  Robust.Server/GameObjects/Components/Actor/BasicActorComponent.cs
Labels: Type: Bug

#1219 Admin Menu Engine PR
  Robust.Client/Console/ClientConGroupController.cs
  Robust.Client/Console/IClientConGroupController.cs
  Robust.Server/Console/ConGroupContainer.cs
  Robust.Server/Console/ConGroupController.cs
  Robust.Server/Console/IConGroupController.cs
  Robust.Shared/Console/ConGroup.cs
  Robust.Shared/Console/MsgConGroupUpdate.cs
Labels: Feature: UI, Type: Feature

#1260 Make a Windows message box if the game window can't be opened
  Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
  Robust.Client/Utility/LiterallyJustMessageBox.cs
Labels: Feature: Clyde, Platform: Windows

#1254 IsIntersecting method for EntityManager
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/Interfaces/GameObjects/IEntityManager.cs
Labels: Feature: Entities, Type: Feature

#1265 Deterministic RobustMappedStringSerializer
  Robust.Server/BaseServer.cs
  Robust.Shared/Interfaces/Serialization/IRobustMappedStringSerializer.cs
  Robust.Shared/Localization/LocalizationManager.cs
  Robust.Shared/Network/Messages/MsgMapStrClientHandshake.cs
  Robust.Shared/Network/Messages/MsgMapStrServerHandshake.cs
  Robust.Shared/Network/Messages/MsgMapStrStrings.cs
  Robust.Shared/Robust.Shared.csproj
  Robust.Shared/Serialization/RobustMappedStringSerializer.MappedStringDict.cs
  Robust.Shared/Serialization/RobustMappedStringSerializer.cs
  Robust.Shared/Serialization/RobustSerializer.cs
  Robust.Shared/SharedIoC.cs
  Robust.Shared/Utility/Base64Helpers.cs
  Robust.Shared/Utility/HasherStream.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
Labels: Feature: Networking, Type: Bug, Type: Performance, Type: Refactor

#1263 Fix Button Labels not updating styles when Button is disabled/enabled
  Robust.Client/UserInterface/Control.Styling.cs
  Robust.Client/UserInterface/Controls/Button.cs
Labels: Feature: UI, Priority: 3-low, Type: Bug

#1267 Make more light properties animatable
  Robust.Client/Animations/AnimationTrackProperty.cs
  Robust.Client/GameObjects/Components/Light/PointLightComponent.cs
Labels: Type: Feature
