Repository space-wizards/RobustToolbox, pull requests merged in 2020-10, with the labels that each got.

#1291 Add HashSet YAML serialization
  Robust.Shared/Serialization/YamlObjectSerializer.cs
  Robust.UnitTesting/Shared/Serialization/YamlObjectSerializer_Test.cs
Labels: Feature: Entities, Type: Feature

#1299 Add YAML serialization for nullable primitive types
  Robust.Shared/Serialization/YamlObjectSerializer.cs
  Robust.UnitTesting/Shared/Serialization/YamlObjectSerializer_Test.cs
Labels: Feature: Prototypes, Type: Feature

#1303 Add component references for SpriteComponent
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
Labels: Feature: Entities

#1306 Things needed for singulo
  Robust.Client/UserInterface/Controls/SpinBox.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Shared.Maths/Direction.cs
Labels: Feature: UI, Type: Feature, Type: Performance

#1310 Fix ScrollBar overshot when frame time is long
  Robust.Client/UserInterface/Controls/ScrollBar.cs
Labels: Feature: UI, Type: Bug

#1317 Remove obsolete physics component
  Robust.Shared/GameObjects/Components/Collidable/CollidableComponent.Physics.cs
  Robust.Shared/GameObjects/Components/Physics/PhysicsComponent.cs
Labels: Type: Refactor

#1311 Componentdependency
  Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyAttribute.cs
  Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
  Robust.Shared/GameObjects/ComponentManager.cs
  Robust.Shared/Interfaces/GameObjects/Components/IComponentDependencyManager.cs
  Robust.Shared/SharedIoC.cs
  Robust.Shared/Utility/NullableHelper.cs
  Robust.UnitTesting/Shared/GameObjects/ComponentDependencies_Tests.cs
  Robust.UnitTesting/Shared/GameObjects/ComponentManager_Tests.cs
  Robust.UnitTesting/Shared/Utility/NullableHelper_Test.cs
Labels: Feature: Entities, Type: Feature

#1332 Expose EntitySystemManager.AllSystems property
  Robust.Shared/GameObjects/EntitySystemManager.cs
  Robust.Shared/Interfaces/GameObjects/IEntitySystemManager.cs
Labels: Feature: Entities, Type: Refactor

#1333 Rename last usages of Collidable to Physics
  Robust.Client/Debugging/DebugDrawing.cs
  Robust.Client/Placement/PlacementManager.cs
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponent.Collision.cs
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponent.Physics.cs
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponentState.cs
  Robust.Shared/GameObjects/Components/NetIDs.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/EntityQuery.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/Interfaces/GameObjects/Components/ITransformComponent.cs
  Robust.Shared/Interfaces/Map/ITileDefinition.cs
  Robust.Shared/Physics/IPhysBody.cs
  Robust.UnitTesting/Server/Maps/MapLoaderTest.cs
Labels: Type: Refactor

#1340 Add debug assert for transform self parenting
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
Labels: Type: Bug

#1330 Change cvar usages to use CVarDef and define them in CVars
  Robust.Client/BaseClient.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
  Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
  Robust.Client/Graphics/Clyde/Clyde.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Graphics/ClydeBase.cs
  Robust.Client/Graphics/FontManager.cs
  Robust.Client/Interfaces/UserInterface/IUserInterfaceManager.cs
  Robust.Client/Player/PlayerManager.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
  Robust.Client/Utility/DiscordRichPresence.cs
  Robust.Server/BaseServer.cs
  Robust.Server/Console/ConGroupController.cs
  Robust.Server/Console/ConsoleShell.cs
  Robust.Server/Console/SessionGroupContainer.cs
  Robust.Server/DataMetrics/MetricsManager.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/GameObjects/ServerEntityNetworkManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/ServerStatus/StatusHost.Handlers.cs
  Robust.Server/ServerStatus/StatusHost.cs
  Robust.Server/ServerStatus/WatchdogApi.cs
  Robust.Shared/CVars.cs
  Robust.Shared/Configuration/ConfigurationManager.cs
  Robust.Shared/Network/NetManager.ServerAuth.cs
  Robust.Shared/Network/NetManager.cs
  Robust.Shared/SignalHandler.cs
  Robust.UnitTesting/RobustUnitTest.cs
  RobustToolbox.sln.DotSettings
Labels: Type: Refactor

#1357 Fix map deserialized entities not being included in OccluderSystem
  Robust.Shared/GameObjects/Components/Light/OccluderComponent.cs
  Robust.Shared/GameObjects/Systems/OccluderSystem.cs
Labels: Feature: Entities, Type: Bug

#1356 Add shared and server eye components
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Client/GameObjects/Components/Eye/EyeComponent.cs
  Robust.Server/GameObjects/Components/Eye/EyeComponent.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Shared/GameObjects/Components/Eye/SharedEyeComponent.cs
  Robust.Shared/GameObjects/Components/NetIDs.cs
Labels: Feature: Entities, Type: Feature

#1358 Add timer component
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
  Robust.Shared/GameObjects/Components/Timers/TimerExtensions.cs
  Robust.Shared/GameObjects/Systems/TimerSystem.cs
Labels: Feature: Entities, Type: Feature
