Repository space-wizards/RobustToolbox, pull requests merged in 2020-04, with the labels that each got.

#1026 Add visibility masks to IPlayerSession, add Visibility component (layers)
  Robust.Server/GameObjects/Components/VisibilityComponent.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/Interfaces/Player/IPlayerSession.cs
  Robust.Server/Player/PlayerSession.cs
Labels: Type: Feature

#1027 Prediction
  Robust.Client/BaseClient.cs
  Robust.Client/GameController.cs
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameObjects/ClientEntityNetworkManager.cs
  Robust.Client/GameObjects/EntityManagerExt.cs
  Robust.Client/GameObjects/EntitySystems/InputSystem.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/GameStates/GameStateProcessor.cs
  Robust.Client/GameStates/IGameStateProcessor.cs
  Robust.Client/Input/InputManager.cs
  Robust.Client/Interfaces/GameObjects/IClientEntityManager.cs
  Robust.Client/Interfaces/GameStates/IClientGameStateManager.cs
  Robust.Client/Player/LocalPlayer.cs
  Robust.Client/Player/PlayerManager.cs
  Robust.Client/Player/PlayerSession.cs
  Robust.Client/UserInterface/CustomControls/DebugMonitors.cs
  Robust.Client/UserInterface/CustomControls/DebugTimePanel.cs
  Robust.Server/BaseServer.cs
  Robust.Server/GameObjects/EntitySystems/InputSystem.cs
  Robust.Server/GameObjects/ServerEntityNetworkManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Interfaces/GameObjects/IServerEntityNetworkManager.cs
  Robust.Server/Interfaces/Player/IPlayerSession.cs
  Robust.Server/ServerIoC.cs
  Robust.Shared/GameObjects/Components/Collidable/CollidableComponent.cs
  Robust.Shared/GameObjects/EntityEventBus.cs
  Robust.Shared/GameObjects/EntityEvents.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/EntityState.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EntitySystemMessage.cs
  Robust.Shared/GameObjects/EventBusExt.cs
  Robust.Shared/GameObjects/IEntityNetworkManager.cs
  Robust.Shared/GameObjects/Systems/EntitySystem.cs
  Robust.Shared/GameObjects/Systems/SharedInputSystem.cs
  Robust.Shared/GameStates/GameState.cs
  Robust.Shared/Input/InputCmdHandler.cs
  Robust.Shared/Input/InputCmdMessage.cs
  Robust.Shared/Interfaces/Timing/IGameTiming.cs
  Robust.Shared/Interfaces/Timing/PredictionGuard.cs
  Robust.Shared/Network/Messages/MsgEntity.cs
  Robust.Shared/Network/Messages/MsgSetTickRate.cs
  Robust.Shared/Network/NetManager.cs
  Robust.Shared/Network/NetMessageExt.cs
  Robust.Shared/Players/ICommonSession.cs
  Robust.Shared/Timing/GameTick.cs
  Robust.Shared/Timing/GameTiming.cs
  Robust.UnitTesting/Client/GameStates/GameStateProcessor_Tests.cs
Labels: Area: Networking, Priority: 1-high

#1030 ServerEntityNetworkManager doesn't dispatch messages if the client got disconnected
  Robust.Server/GameObjects/ServerEntityNetworkManager.cs
  Robust.Shared/Interfaces/Network/INetChannel.cs
  Robust.Shared/Network/NetChannel.cs
  Robust.UnitTesting/RobustIntegrationTest.NetManager.cs
Labels: Type: Bug
