Repository space-wizards/RobustToolbox, pull requests merged in 2020-11, with the labels that each got.

#1335 (Attempt to) draw world overlays inbetween entities
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
Labels: Feature: Clyde, Feature: Entities, Type: Feature

#1389 Make ContainerHelpers methods extensions
  Robust.Shared/Containers/ContainerHelpers.cs
Labels: Feature: Entities, Type: Refactor

#1367 Allow multiple module testing callbacks
  Robust.Shared/ContentPack/GameShared.cs
  Robust.Shared/ContentPack/IModLoader.cs
  Robust.Shared/ContentPack/ModLoader.cs
Labels: Type: Feature

#1371 ConGroups are gone. Long live admin flags in content.
  Robust.Client/Console/ClientConGroupController.cs
  Robust.Client/Console/Commands/HelpCommands.cs
  Robust.Client/Console/IClientConGroupController.cs
  Robust.Client/Console/IClientConGroupImplementation.cs
  Robust.Client/GameController.cs
  Robust.Server/BaseServer.cs
  Robust.Server/Console/ConGroupContainer.cs
  Robust.Server/Console/ConGroupController.cs
  Robust.Server/Console/ConsoleShell.cs
  Robust.Server/Console/IConGroupController.cs
  Robust.Server/Console/IConGroupControllerImplementation.cs
  Robust.Server/Console/SessionGroupContainer.cs
  Robust.Server/Interfaces/Console/IConsoleShell.cs
  Robust.Shared/CVars.cs
  Robust.Shared/Console/ConGroup.cs
  Robust.Shared/Console/ConGroupIndex.cs
  Robust.Shared/Console/MsgConGroupUpdate.cs
Labels: Type: Refactor

#1401 EntityPrototypeIcon SpriteSpecifier
  Robust.Client/UserInterface/Controls/TextureRect.cs
  Robust.Client/Utility/SpriteSpecifierExt.cs
  Robust.Server/GameObjects/Components/Container/ContainerManagerComponent.cs
  Robust.Shared/Utility/SpriteSpecifier.cs
Labels: Type: Feature

#1409 Add TryGet methods for component registrations
  Robust.Shared/GameObjects/ComponentFactory.cs
  Robust.Shared/Interfaces/GameObjects/IComponentFactory.cs
Labels: Feature: Prototypes, Type: Feature

#1380 Numerics Helpers: SIMD accelerated array math methods
  Robust.Shared.Maths/NumericsHelpers.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.UnitTesting/Robust.UnitTesting.csproj
  Robust.UnitTesting/Shared/Maths/NumericsHelpers_Test.cs
  nuget.config
Labels: Misc: Quality of Life, Type: Feature, Type: Performance

#1417 Add searching by component name to View Variables
  Robust.Client/ViewVariables/Instances/ViewVariablesInstanceEntity.cs
Labels: Feature: UI, Type: Feature
