Repository space-wizards/RobustToolbox, pull requests merged in 2020-09, with the labels that each got.

#1266 GLES2 users, assemble!
  Resources/Shaders/Internal/default-sprite.swsl
  Resources/Shaders/Internal/depth-debug.swsl
  Resources/Shaders/Internal/fov-lighting.swsl
  Resources/Shaders/Internal/fov.swsl
  Resources/Shaders/Internal/light.swsl
  Resources/Shaders/Internal/shadow_cast_shared.swsl
  Resources/Shaders/Internal/wall-bleed-blur.swsl
  Resources/Shaders/Internal/wall-merge.swsl
  Robust.Client/Graphics/Clyde/Clyde.Constants.cs
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Graphics/Clyde/Clyde.Helpers.cs
  Robust.Client/Graphics/Clyde/Clyde.Layout.cs
  Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
  Robust.Client/Graphics/Clyde/Clyde.RenderTargets.cs
  Robust.Client/Graphics/Clyde/Clyde.Rendering.cs
  Robust.Client/Graphics/Clyde/Clyde.Shaders.cs
  Robust.Client/Graphics/Clyde/Clyde.Textures.cs
  Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
  Robust.Client/Graphics/Clyde/Clyde.cs
  Robust.Client/Graphics/Clyde/GLObjects/Clyde.ShaderProgram.cs
  Robust.Client/Graphics/Clyde/GLObjects/Clyde.UniformBuffer.cs
  Robust.Client/Graphics/Clyde/Shaders/base-default.frag
  Robust.Client/Graphics/Clyde/Shaders/base-default.vert
  Robust.Client/Graphics/Clyde/Shaders/base-raw.frag
  Robust.Client/Graphics/Clyde/Shaders/base-raw.vert
  Robust.Client/Graphics/Clyde/Shaders/shadow-depth.frag
  Robust.Client/Graphics/Clyde/Shaders/shadow-depth.vert
  Robust.Client/Graphics/Clyde/Shaders/z-library.glsl
  Robust.Client/Graphics/Shaders/ParsedShader.cs
  Robust.Client/Graphics/Shaders/ShaderParser.Tokenizer.cs
  Robust.Client/Graphics/Shaders/ShaderParser.cs
  Robust.Client/Graphics/Shaders/ShaderPrototype.cs
  Robust.Client/UserInterface/CustomControls/BaseWindow.cs
Labels: Area: Rendering, Feature: Clyde, Type: Feature, Type: Refactor

#1271 Make HighestMapID and HighestGridID public for content to read
  Robust.Shared/Map/MapManager.cs
Labels: Type: Refactor

#1277 EntityCoordinates
  Robust.Client/UserInterface/CustomControls/DebugCoordsPanel.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/Interfaces/GameObjects/Components/ITransformComponent.cs
  Robust.Shared/Map/Coordinates.cs
  Robust.UnitTesting/Shared/Map/EntityCoordinates_Tests.cs
Labels: Feature: Entities, Misc: Quality of Life, Type: Feature

#1281 Grid tile lookup system
  Robust.Server/GameObjects/EntitySystemMessages/EntityDeletedMessage.cs
  Robust.Server/GameObjects/EntitySystemMessages/EntityTileMessage.cs
  Robust.Server/GameObjects/EntitySystems/TileLookup/GridTileLookupChunk.cs
  Robust.Server/GameObjects/EntitySystems/TileLookup/GridTileLookupNode.cs
  Robust.Server/GameObjects/EntitySystems/TileLookup/GridTileLookupSystem.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EntityInitializedMessage.cs
Labels: Feature: Entities, Type: Performance

#1280 Replace every usage of GridCoordinates with EntityCoordinates
  Robust.Client/Audio/Midi/MidiManager.cs
  Robust.Client/Audio/Midi/MidiRenderer.cs
  Robust.Client/Console/Commands/ClientSpawnCommand.cs
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Client/GameObjects/EntitySystems/EffectSystem.cs
  Robust.Client/Graphics/ClientEye/EyeManager.cs
  Robust.Client/Interfaces/Graphics/ClientEye/IEyeManager.cs
  Robust.Client/Placement/Modes/AlignSimilar.cs
  Robust.Client/Placement/Modes/AlignSnapgridBorder.cs
  Robust.Client/Placement/Modes/AlignSnapgridCenter.cs
  Robust.Client/Placement/Modes/AlignTileAny.cs
  Robust.Client/Placement/Modes/AlignTileDense.cs
  Robust.Client/Placement/Modes/AlignTileEmpty.cs
  Robust.Client/Placement/Modes/AlignTileNonDense.cs
  Robust.Client/Placement/Modes/AlignWall.cs
  Robust.Client/Placement/Modes/AlignWallProper.cs
  Robust.Client/Placement/Modes/PlaceFree.cs
  Robust.Client/Placement/Modes/PlaceNearby.cs
  Robust.Client/Placement/PlacementHijack.cs
  Robust.Client/Placement/PlacementManager.cs
  Robust.Client/Placement/PlacementMode.cs
  Robust.Client/UserInterface/CustomControls/DebugCoordsPanel.cs
  Robust.Client/ViewVariables/Editors/ViewVariablesPropertyEditorEntityCoordinates.cs
  Robust.Client/ViewVariables/ViewVariablesManager.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/Console/Commands/PlayerCommands.cs
  Robust.Server/Console/Commands/SpawnCommand.cs
  Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Server/GameObjects/EntitySystems/TileLookup/GridTileLookupSystem.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/Interfaces/Player/IPlayerManager.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Server/Player/PlayerManager.cs
  Robust.Shared.Scripting/ScriptGlobalsShared.cs
  Robust.Shared/GameObjects/Components/Collidable/CollidableComponent.Physics.cs
  Robust.Shared/GameObjects/Components/Transform/SnapGridComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/EntitySystemMessages/AudioMessages.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EffectMessage.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/Input/Binding/InputCmdHandler.cs
  Robust.Shared/Input/InputCmdMessage.cs
  Robust.Shared/Interfaces/GameObjects/Components/ITransformComponent.cs
  Robust.Shared/Interfaces/GameObjects/IEntityManager.cs
  Robust.Shared/Interfaces/Physics/IPhysicsManager.cs
  Robust.Shared/Map/Coordinates.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapIndices.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Network/Messages/MsgPlacement.cs
  Robust.Shared/Network/NetMessageExt.cs
  Robust.Shared/Physics/PhysicsManager.cs
  Robust.UnitTesting/Client/GameObjects/Components/Transform_Test.cs
  Robust.UnitTesting/Server/GameObjects/Components/Container_Test.cs
  Robust.UnitTesting/Server/GameObjects/Components/Transform_Test.cs
  Robust.UnitTesting/Shared/Map/EntityCoordinates_Tests.cs
Labels: Feature: Entities, Type: Refactor

#1274 More configurable lighting (also, "Rounded" mode for Range)
  Resources/Shaders/Internal/light-hard.swsl
  Resources/Shaders/Internal/light-soft.swsl
  Resources/Shaders/Internal/light_shared.swsl
  Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
  Robust.Client/Graphics/Clyde/Clyde.cs
  Robust.Client/Graphics/ClydeBase.cs
  Robust.Client/UserInterface/Controls/Range.cs
  Robust.Client/UserInterface/CustomControls/OptionsMenu.cs
Labels: Feature: Clyde, Type: Feature

#1286 Make GetTilesIntersecting translate from world to local to tile
  Robust.Shared/Map/MapGrid.cs
Labels: Feature: Entities, Type: Bug

#1284 Make more fields VV and editable
  Robust.Client/GameObjects/Components/Appearance/AppearanceComponent.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Server/GameObjects/Components/Renderable/SpriteComponent.cs
Labels: Feature: Entities

#1287 Make the tile spawner search bar autofocus
  Robust.Client/UserInterface/CustomControls/TileSpawnWindow.cs
Labels: Feature: UI, Type: Bug

#1297 Fix build
  Robust.Server/ServerStatus/WatchdogApi.cs
  Robust.Shared/Configuration/ConfigurationManager.cs
  Robust.Shared/Interfaces/Configuration/IConfigurationManager.cs
Labels: Type: Bug

#1298 Fix build
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
Labels: Type: Bug

#1289 Auth
  Robust.Client/BaseClient.cs
  Robust.Client/Graphics/Clyde/Clyde.cs
  Robust.Client/Player/IPlayerManager.cs
  Robust.Client/Player/LocalPlayer.cs
  Robust.Client/Player/PlayerManager.cs
  Robust.Client/Player/PlayerSession.cs
  Robust.Server/Console/Commands/PlayerCommands.cs
  Robust.Server/GameObjects/ServerEntityNetworkManager.cs
  Robust.Server/Interfaces/Player/IPlayerData.cs
  Robust.Server/Interfaces/Player/IPlayerManager.cs
  Robust.Server/Interfaces/Player/IPlayerSession.cs
  Robust.Server/Player/PlayerData.cs
  Robust.Server/Player/PlayerManager.cs
  Robust.Server/Player/PlayerSession.cs
  Robust.Server/Robust.Server.csproj
  Robust.Server/ServerStatus/StatusHost.Handlers.cs
  Robust.Server/ServerStatus/StatusHost.cs
  Robust.Server/ServerStatus/WatchdogApi.cs
  Robust.Server/ViewVariables/ViewVariablesHost.cs
  Robust.Server/ViewVariables/ViewVariablesSession.cs
  Robust.Shared/CVars.cs
  Robust.Shared/Configuration/CVar.cs
  Robust.Shared/Configuration/ConfigurationManager.cs
  Robust.Shared/GameStates/PlayerState.cs
  Robust.Shared/Interfaces/Configuration/IConfigurationManagerInternal.cs
  Robust.Shared/Interfaces/Network/INetChannel.cs
  Robust.Shared/Interfaces/Network/INetManager.cs
  Robust.Shared/Interfaces/Network/IServerNetManager.cs
  Robust.Shared/Interfaces/Network/NetApproval.cs
  Robust.Shared/Interfaces/Network/NetApprovalEventArgs.cs
  Robust.Shared/Network/AuthMode.cs
  Robust.Shared/Network/LoginType.cs
  Robust.Shared/Network/Messages/Handshake/MsgEncryptionRequest.cs
  Robust.Shared/Network/Messages/Handshake/MsgEncryptionResponse.cs
  Robust.Shared/Network/Messages/Handshake/MsgLoginStart.cs
  Robust.Shared/Network/Messages/Handshake/MsgLoginSuccess.cs
  Robust.Shared/Network/Messages/MsgPlayerList.cs
  Robust.Shared/Network/Messages/MsgServerInfo.cs
  Robust.Shared/Network/NetChannel.cs
  Robust.Shared/Network/NetChannelArgs.cs
  Robust.Shared/Network/NetManager.ClientConnect.cs
  Robust.Shared/Network/NetManager.Docs.md
  Robust.Shared/Network/NetManager.ServerAuth.cs
  Robust.Shared/Network/NetManager.cs
  Robust.Shared/Network/NetMessage.cs
  Robust.Shared/Network/NetMessageExt.cs
  Robust.Shared/Network/NetSessionId.cs
  Robust.Shared/Network/NetUserId.cs
  Robust.Shared/Players/IBaseSession.cs
  Robust.Shared/Serialization/RobustMappedStringSerializer.cs
  Robust.Shared/SharedIoC.cs
  Robust.UnitTesting/RobustIntegrationTest.NetManager.cs
  Robust.UnitTesting/Shared/Configuration/ConfigurationManagerTest.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
Labels: Type: Refactor
