Repository space-wizards/RobustToolbox, pull requests merged in 2020-06, with the labels that each got.

#1110 Map Loading
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Prototypes/EntityPrototype.cs
Labels: Area: Entities, Project: Server, Type: Feature

#1079 Add distance to AudioSystem
  Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
Labels: Type: Discussion

#1117 Have RobustSerializer use a shared string dictionary
  Robust.Client/GameController.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Server/Player/PlayerManager.cs
  Robust.Shared/ContentPack/DirLoader.cs
  Robust.Shared/ContentPack/IContentRoot.cs
  Robust.Shared/ContentPack/IModLoader.cs
  Robust.Shared/ContentPack/PackLoader.cs
  Robust.Shared/ContentPack/ResourceManager.SingleStreamLoader.cs
  Robust.Shared/ContentPack/ResourceManager.cs
  Robust.Shared/GameObjects/ComponentFactory.cs
  Robust.Shared/Interfaces/GameObjects/IComponentFactory.cs
  Robust.Shared/Interfaces/Serialization/IRobustSerializer.cs
  Robust.Shared/Localization/LocalizationManager.cs
  Robust.Shared/Network/NetChannel.cs
  Robust.Shared/Network/NetManager.cs
  Robust.Shared/Network/StringTable.cs
  Robust.Shared/Prototypes/PrototypeManager.cs
  Robust.Shared/Robust.Shared.csproj
  Robust.Shared/Serialization/RobustSerializer.Handshake.cs
  Robust.Shared/Serialization/RobustSerializer.MappedStringSerializer.MsgClientHandshake.cs
  Robust.Shared/Serialization/RobustSerializer.MappedStringSerializer.MsgServerHandshake.cs
  Robust.Shared/Serialization/RobustSerializer.MappedStringSerializer.MsgStrings.cs
  Robust.Shared/Serialization/RobustSerializer.MappedStringSerializer.cs
  Robust.Shared/Serialization/RobustSerializer.cs
  Robust.Shared/Serialization/YamlObjectSerializer.cs
  Robust.Shared/Utility/TypeAbbreviation.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
Labels: Area: Networking

#1133 Improved click detection supporting features:
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Client/GameObjects/Components/Input/ClickableComponent.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/Graphics/Clyde/Clyde.Textures.cs
  Robust.Client/Interfaces/GameObjects/Components/IClientClickableComponent.cs
  Robust.Client/Interfaces/GameObjects/Components/ISpriteComponent.cs
  Robust.Client/Interfaces/GameObjects/IClickTargetComponent.cs
  Robust.Client/Interfaces/ResourceManagement/IResourceCache.cs
  Robust.Client/ResourceManagement/ResourceCache.cs
  Robust.Client/ResourceManagement/ResourceTypes/RSIResource.cs
  Robust.Client/ResourceManagement/ResourceTypes/TextureResource.cs
  Robust.Client/ResourceManagement/RsiLoadedEventArgs.cs
  Robust.Client/ResourceManagement/TextureLoadedEventArgs.cs
  Robust.Server/GameObjects/Components/ClickableComponent.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Shared/Interfaces/GameObjects/Components/IClickableComponent.cs
  Robust.UnitTesting/Shared/Prototypes/PrototypeManager_Test.cs
Labels: Type: Feature, Type: Refactor

#1139 Dynamically Manage Collision Solver Iterations
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
Labels: Priority: 4-Wishlist

#1140 Make Lidgren Use Spans & Shared Pool
  .github/workflows/build-test.yml
  Lidgren.Network.UnitTests/Lidgren.Network.UnitTests.csproj
  Lidgren.Network.UnitTests/ReadWriteTests.cs
  Lidgren.Network.UnitTests/TestsBase.cs
  Lidgren.Network/Encryption/NetAESEncryption.cs
  Lidgren.Network/Encryption/NetBlockEncryptionBase.cs
  Lidgren.Network/Encryption/NetCryptoProviderBase.cs
  Lidgren.Network/Encryption/NetCryptoProviderEncryption.cs
  Lidgren.Network/Encryption/NetEncryption.cs
  Lidgren.Network/Encryption/NetXorEncryption.cs
  Lidgren.Network/Encryption/NetXteaEncryption.cs
  Lidgren.Network/Lidgren.Network.csproj
  Lidgren.Network/NetBigInteger.cs
  Lidgren.Network/NetBitWriter.cs
  Lidgren.Network/NetBuffer.Peek.cs
  Lidgren.Network/NetBuffer.Read.cs
  Lidgren.Network/NetBuffer.Write.cs
  Lidgren.Network/NetBuffer.cs
  Lidgren.Network/NetConnection.Handshake.cs
  Lidgren.Network/NetConnection.MTU.cs
  Lidgren.Network/NetConnectionStatistics.cs
  Lidgren.Network/NetFragmentationHelper.cs
  Lidgren.Network/NetOutgoingMessage.cs
  Lidgren.Network/NetPeer.Fragmentation.cs
  Lidgren.Network/NetPeer.Internal.cs
  Lidgren.Network/NetPeer.LatencySimulation.cs
  Lidgren.Network/NetPeer.MessagePools.cs
  Lidgren.Network/NetPeerStatistics.cs
  Lidgren.Network/NetSRP.cs
  Lidgren.Network/NetUtility.cs
  Lidgren.Network/Platform/NativeSocket.Structs.cs
  Lidgren.Network/Platform/NativeSockets.cs
  Lidgren.Network/Platform/PlatformConstrained.cs
  Lidgren.Network/Platform/PlatformWin32.cs
  Lidgren.Network/Properties/AssemblyInfo.cs
  Lidgren.Network/RobustToolbox/Lidgren.Network/NetBuffer.Streams.cs
  Robust.Server/GameObjects/Components/Appearance/AppearanceComponent.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Shared/Network/Messages/MsgEntity.cs
  Robust.Shared/Network/Messages/MsgScriptResponse.cs
  Robust.Shared/Network/Messages/MsgState.cs
  Robust.Shared/Network/Messages/MsgViewVariablesModifyRemote.cs
  Robust.Shared/Network/Messages/MsgViewVariablesRemoteData.cs
  Robust.Shared/Network/Messages/MsgViewVariablesReqData.cs
  Robust.Shared/Network/Messages/MsgViewVariablesReqSession.cs
  Robust.Shared/Serialization/Messages/MsgRobustMappedStringsSerializerServerHandshake.cs
  Robust.Shared/Serialization/Messages/MsgRobustMappedStringsSerializerStrings.cs
Labels: Area: Networking, Dependency: Lidgren, Priority: 3-low, Type: Performance

#1143 ComponentManager Rework
  Robust.Client/GameObjects/EntitySystems/OccluderSystem.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Shared/GameObjects/ComponentEventArgs.cs
  Robust.Shared/GameObjects/ComponentManager.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/Interfaces/GameObjects/IComponentManager.cs
  Robust.Shared/Interfaces/Utility/Internal/IUniqueIndex.cs
  Robust.Shared/Physics/PhysicsManager.cs
  Robust.Shared/Properties/AssemblyInfo.cs
  Robust.Shared/Utility/UniqueIndex.cs
  Robust.Shared/Utility/UniqueIndexExtensions.cs
  Robust.Shared/Utility/UniqueIndexHkm.cs
Labels: Type: Performance

#1146 Implement MultipleTypeEntityQuery
  Robust.Shared/GameObjects/EntityQuery.cs
Labels: Type: Feature

#1144 Movement prediction work.
  Robust.Client/Console/WatchWindow.cs
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Client/GameObjects/Components/Physics/PhysicsComponent.cs
  Robust.Client/GameObjects/EntitySystems/EyeUpdateSystem.cs
  Robust.Client/GameObjects/EntitySystems/InputSystem.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/GameStates/GameStateProcessor.cs
  Robust.Client/GameStates/IGameStateProcessor.cs
  Robust.Client/Physics/PhysicsSystem.cs
  Robust.Server/GameObjects/Components/Physics/PhysicsComponent.cs
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Server/GameObjects/ServerEntityNetworkManager.cs
  Robust.Shared/GameObjects/Components/Collidable/CollidableComponent.cs
  Robust.Shared/GameObjects/Components/Map/MapGridComponent.cs
  Robust.Shared/GameObjects/Components/Physics/PhysicsComponentState.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/Input/InputCmdMessage.cs
  Robust.Shared/Interfaces/Timing/IGameTiming.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Physics/SharedPhysicsComponent.cs
  Robust.UnitTesting/Server/GameObjects/ServerEntityNetworkManagerTest.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
Labels: Area: Entities, Area: Networking, Priority: 1-high, Status: DO NOT MERGE, Type: Feature

#1156 Logging Tweaks
  Robust.Server/Program.cs
  Robust.Shared/Log/ConsoleLogHandler.cs
Labels: Type: Performance
