Repository space-wizards/RobustToolbox, pull requests merged in 2020-12, with the labels that each got.

#1433 Fixed handling keybinds.yml with no binds
  Robust.Client/Input/InputManager.cs
Labels: Type: Bug

#1431 Add EnsureComponentWarn methods
  Robust.Shared/GameObjects/ComponentExt.cs
Labels: Type: Feature

#1360 Rotatable bounding boxes
  Robust.Client/Debugging/DebugDrawing.cs
  Robust.Shared.Maths/Angle.cs
  Robust.Shared.Maths/Box2.cs
  Robust.Shared.Maths/Box2Rotated.cs
  Robust.Shared.Maths/Properties/AssemblyInfo.cs
  Robust.Shared.Maths/SimdHelpers.cs
  Robust.Shared/Physics/DebugDrawingHandle.cs
  Robust.Shared/Physics/PhysShapeCircle.cs
  Robust.Shared/Physics/PhysShapeRect.cs
  Robust.UnitTesting/Shared/Maths/Box2Rotated_Test.cs
Labels: Feature: Entities, Priority: 2-medium, Type: Feature

#1442 Fix the server not setting IsConnected to false for disconnecting clients in integration tests
  Robust.UnitTesting/RobustIntegrationTest.NetManager.cs
Labels: Project: Tests, Type: Bug

#1453 Defer MoveEvent out of TransformComponent.HandleComponentState
  Robust.Client/GameObjects/EntitySystems/TransformSystem.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.cs
  Robust.UnitTesting/Client/GameObjects/Components/Transform_Test.cs
Labels: Feature: Entities, Feature: Networking, Type: Bug

#1456 Add YamlObjectSerializer.NodeToType with generic argument
  Robust.Shared/Serialization/YamlObjectSerializer.cs
Labels: Feature: Prototypes, Type: Feature
