Repository space-wizards/RobustToolbox, pull requests merged in 2020-05, with the labels that each got.

#1045 Midi optimizations.
  Robust.Client/Audio/Midi/MidiRenderer.cs
Labels: Type: Performance

#1055 Replaces noSprite.png with Gmod Error Sprite
  Resources/Textures/error.rsi/error.png
  Resources/Textures/error.rsi/meta.json
  Resources/Textures/noSprite.png
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
Labels: Type: Feature

#1062 Better MIDI
  Robust.Client/Audio/Midi/MidiManager.cs
  Robust.Client/Audio/Midi/MidiRenderer.cs
  Robust.Client/Robust.Client.csproj
  Robust.Shared/Audio/Midi/MidiEvent.cs
  Robust.Shared/Robust.Shared.csproj
Labels: Type: Feature, Type: Performance

#1068 Implement audio occlusion and upgrade to OpenTK 4
  MSBuild/Robust.Properties.targets
  Robust.Client/Audio/Midi/MidiManager.cs
  Robust.Client/Audio/Midi/MidiRenderer.cs
  Robust.Client/GameObjects/Components/Appearance/AppearanceComponent.cs
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/Graphics/Clyde/Audio/Clyde.Audio.cs
  Robust.Client/Graphics/Clyde/Clyde.DllMap.cs
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Graphics/Clyde/Clyde.Helpers.cs
  Robust.Client/Graphics/Clyde/Clyde.LightRendering.cs
  Robust.Client/Graphics/Clyde/Clyde.RenderTargets.cs
  Robust.Client/Graphics/Clyde/Clyde.Rendering.cs
  Robust.Client/Graphics/Clyde/Clyde.Shaders.cs
  Robust.Client/Graphics/Clyde/Clyde.Textures.cs
  Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
  Robust.Client/Graphics/Clyde/Clyde.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Graphics/Clyde/GLObjects/Clyde.Buffer.cs
  Robust.Client/Graphics/Clyde/GLObjects/Clyde.Shader.cs
  Robust.Client/Graphics/Clyde/GLObjects/Clyde.ShaderProgram.cs
  Robust.Client/Interfaces/Graphics/IClydeAudioSource.cs
  Robust.Client/Interfaces/Graphics/IClydeBufferedAudioSource.cs
  Robust.Client/Robust.Client.csproj
  Robust.Client/Utility/OpenTKConversions.cs
  Robust.Shared/Physics/PhysicsManager.cs
Labels: Type: Feature, Type: Refactor
