Repository space-wizards/RobustToolbox, pull requests merged in 2021-07, with the labels that each got.

#1851 Add Contains Vector2 method to Box2Rotated
  Robust.Shared.Maths/Box2Rotated.cs
  Robust.UnitTesting/Shared/Maths/Box2Rotated_Test.cs
Labels: Area: Physics

#1861 some misc serv3 fixes
  Robust.Shared/Serialization/Manager/Result/DeserializationResult.cs
  Robust.Shared/Serialization/Manager/SerializationManager.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/TypeSerializer.cs
Labels: Area: Serialization, Type: Bug

#1830 Remove NetMessage deprecated boilerplate entirely
  Robust.Shared/Network/INetManager.cs
  Robust.Shared/Network/Messages/MsgPlayerListReq.cs
  Robust.Shared/Network/NetManager.cs
  Robust.Shared/Network/NetMessage.cs
  Robust.Shared/Serialization/RobustMappedStringSerializer.cs
  Robust.UnitTesting/RobustIntegrationTest.NetManager.cs
Labels: Area: Networking, Type: Cleanup

#1860 ITileDefinition now has a Path string that ClydeTileDefinitionManager uses to load textures from
  Robust.Client/Map/ClydeTileDefinitionManager.cs
  Robust.Shared/Map/ITileDefinition.cs
Labels: Size: 2 - Small, Type: Cleanup

#1849 Make entitylookup grid-relative
  Robust.Client/BaseClient.cs
  Robust.Client/GameObjects/Components/RenderingTreeComponent.cs
  Robust.Client/GameObjects/EntitySystems/RenderingTreeSystem.cs
  Robust.Shared/CVars.cs
  Robust.Shared/GameObjects/Components/EntityLookupComponent.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameObjects/Systems/EntityLookup.cs
  Robust.UnitTesting/RobustUnitTest.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
Labels: Area: Physics, Status: Needs Review, Type: Performance

#1862 Deprecate PhysShapeGrid
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  Robust.Server/Physics/GridFixtureSystem.cs
  Robust.Shared.Maths/Box2.cs
  Robust.Shared.Maths/Box2i.cs
  Robust.Shared/CVars.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/Map/GridChunkPartition.cs
  Robust.Shared/Map/IMapChunkInternal.cs
  Robust.Shared/Map/IMapGridInternal.cs
  Robust.Shared/Map/MapChunk.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Physics/Collision/DistanceProxy.cs
  Robust.Shared/Physics/Collision/Shapes/EdgeShape.cs
  Robust.Shared/Physics/Collision/Shapes/IPhysShape.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeAabb.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeCircle.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeGrid.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeRect.cs
  Robust.Shared/Physics/Collision/Shapes/PolygonShape.cs
  Robust.Shared/Physics/Dynamics/Contacts/Contact.cs
  Robust.Shared/Physics/Dynamics/Fixture.cs
  Robust.Shared/Physics/Transform.cs
  Robust.UnitTesting/Server/Maps/MapLoaderTest.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
  Robust.UnitTesting/Shared/GameObjects/Systems/AnchoredSystemTests.cs
  Robust.UnitTesting/Shared/Map/GridChunkPartition_Tests.cs
  Robust.UnitTesting/Shared/Map/GridFixtures_Tests.cs
Labels: Area: Physics, Status: Needs Review, Type: Cleanup

#1848 Broadphase refactor
  Robust.Client/Audio/Midi/MidiManager.cs
  Robust.Client/Debugging/DebugDrawing.cs
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Client/Physics/BroadPhaseSystem.cs
  Robust.Client/Placement/PlacementMode.cs
  Robust.Client/Placement/PlacementOverlay.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Server/Maps/YamlGridSerializer.cs
  Robust.Server/Physics/BroadPhaseSystem.cs
  Robust.Server/Physics/GridFixtureSystem.cs
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponent.Physics.cs
  Robust.Shared/GameObjects/Systems/OccluderSystem.cs
  Robust.Shared/GameObjects/Systems/SharedGridTraversalSystem.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Physics/B2DynamicTree.cs
  Robust.Shared/Physics/BroadPhase/DynamicTreeBroadPhase.cs
  Robust.Shared/Physics/BroadPhase/SharedBroadPhaseSystem.cs
  Robust.Shared/Physics/BroadphaseComponent.cs
  Robust.Shared/Physics/Collision/Shapes/PolygonShape.cs
  Robust.Shared/Physics/Dynamics/ContactManager.cs
  Robust.Shared/Physics/Dynamics/Contacts/Contact.cs
  Robust.Shared/Physics/Dynamics/Fixture.cs
  Robust.Shared/Physics/Dynamics/PhysicsMap.cs
  Robust.Shared/Physics/IBroadPhase.cs
  Robust.Shared/Physics/IPhysBody.cs
  Robust.Shared/Physics/SharedBroadphaseSystem.cs
  Robust.UnitTesting/Client/GameObjects/Components/TransformComponentTests.cs
  Robust.UnitTesting/Server/GameObjects/Components/Transform_Test.cs
  Robust.UnitTesting/Server/Maps/MapLoaderTest.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
  Robust.UnitTesting/Shared/GameObjects/Systems/AnchoredSystemTests.cs
  Robust.UnitTesting/Shared/Map/EntityCoordinates_Tests.cs
  Robust.UnitTesting/Shared/Map/MapGrid_Tests.cs
  Robust.UnitTesting/Shared/Map/MapManager_Tests.cs
  Robust.UnitTesting/Shared/Physics/Stack_Test.cs
Labels: Area: Physics, Status: Needs Review, Type: Refactor

#1894 Improve RSI error messages
  Robust.Client/ResourceManagement/ResourceTypes/RSIResource.cs
Labels: Type: Feature

#1900 Adds ViewSubscriberComponent and ViewSubscriberSystem
  Robust.Server/GameObjects/Components/Eye/ViewSubscriberComponent.cs
  Robust.Server/GameObjects/EntitySystems/ViewSubscriberSystem.cs
  Robust.Server/GameStates/EntityViewCulling.cs
  Robust.Server/Player/IPlayerSession.cs
  Robust.Server/Player/PlayerSession.cs
Labels: Area: Networking, Type: Feature

#1907 RaiseLocalEvent non-generic overload that checks for GetType()
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameObjects/EntitySystem.cs
Labels: Area: ECS, Misc: Quality of Life

#1915 Fix serv warnings
  Robust.Shared/Physics/Collision/Shapes/EdgeShape.cs
  Robust.Shared/Physics/Dynamics/Joints/DistanceJoint.cs
  Robust.Shared/Physics/Dynamics/Joints/FrictionJoint.cs
  Robust.Shared/Physics/Dynamics/Joints/Joint.cs
Labels: Size: 1 - Tiny, Type: Cleanup
