Repository space-wizards/RobustToolbox, pull requests merged in 2021-05, with the labels that each got.

#1735 Cleanup serialization code
  Robust.Shared/Serialization/ConstantsForAttribute.cs
  Robust.Shared/Serialization/Manager/Attributes/AlwaysPushInheritanceAttribute.cs
  Robust.Shared/Serialization/Manager/Attributes/CopyByRefAttribute.cs
  Robust.Shared/Serialization/Manager/Attributes/DataDefinition.cs
  Robust.Shared/Serialization/Manager/Attributes/ImplicitDataDefinitionForInheritorsAttribute.cs
  Robust.Shared/Serialization/Manager/Attributes/MeansDataDefinition.cs
  Robust.Shared/Serialization/Manager/Attributes/NeverPushInheritanceAttribute.cs
  Robust.Shared/Serialization/Manager/Attributes/TypeSerializerAttribute.cs
  Robust.Shared/Serialization/Manager/DataDefinition/DataDefinition.Delegates.cs
  Robust.Shared/Serialization/Manager/DataDefinition/DataDefinition.Emitters.cs
  Robust.Shared/Serialization/Manager/DataDefinition/DataDefinition.cs
  Robust.Shared/Serialization/Manager/DataDefinition/FieldDefinition.cs
  Robust.Shared/Serialization/Manager/DataDefinition/InheritanceBehavior.cs
  Robust.Shared/Serialization/Manager/ISerializationContext.cs
  Robust.Shared/Serialization/Manager/RequiredDataFieldNotProvidedException.cs
  Robust.Shared/Serialization/Manager/Result/DeserializedArray.cs
  Robust.Shared/Serialization/Manager/Result/DeserializedCollection.cs
  Robust.Shared/Serialization/Manager/Result/DeserializedComponentRegistry.cs
  Robust.Shared/Serialization/Manager/Result/DeserializedDefinition.cs
  Robust.Shared/Serialization/Manager/Result/DeserializedFieldEntry.cs
  Robust.Shared/Serialization/Manager/Result/DeserializedValue.cs
  Robust.Shared/Serialization/Manager/SerializationDataDefinition.cs
  Robust.Shared/Serialization/Manager/SerializationManager.CustomSerializers.cs
  Robust.Shared/Serialization/Manager/SerializationManager.TypeCopiers.cs
  Robust.Shared/Serialization/Manager/SerializationManager.TypeReaders.cs
  Robust.Shared/Serialization/Manager/SerializationManager.TypeSerializers.cs
  Robust.Shared/Serialization/Manager/SerializationManager.TypeValidators.cs
  Robust.Shared/Serialization/Manager/SerializationManager.TypeWriters.cs
  Robust.Shared/Serialization/Manager/SerializationManager.cs
  Robust.Shared/Serialization/Markdown/MappingDataNode.cs
  Robust.Shared/Serialization/Markdown/Validation/ErrorNode.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/ComponentRegistrySerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/EntitySerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
  Robust.Shared/Utility/AbstractFieldInfo.cs
  Robust.Shared/Utility/SpecificFieldInfo.cs
  Robust.Shared/Utility/SpecificPropertyInfo.cs
  Robust.Shared/Utility/TypeHelpers.cs
  Robust.UnitTesting/Shared/Serialization/InheritanceSerializationTest.cs
  Robust.UnitTesting/Shared/Serialization/PropertyAndFieldDefinitionTest.cs
Labels: Area: Serialization, Type: Cleanup

#1739 Add serialization writing benchmark, optimize writing
  Robust.Benchmarks/Serialization/Copy/SerializationCopyBenchmark.cs
  Robust.Benchmarks/Serialization/Definitions/SeedDataDefinition.cs
  Robust.Benchmarks/Serialization/Write/SerializationWriteBenchmark.cs
  Robust.Client/Input/InputManager.cs
  Robust.Client/Serialization/AppearanceVisualizerSerializer.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Shared/Serialization/Manager/DataDefinition/DataDefinition.Emitters.cs
  Robust.Shared/Serialization/Manager/SerializationManager.TypeReaders.cs
  Robust.Shared/Serialization/Manager/SerializationManager.TypeWriters.cs
  Robust.Shared/Serialization/Manager/SerializationManager.cs
  Robust.Shared/Serialization/Markdown/Mapping/MappingDataNodeExtensions.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/ComponentRegistrySerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
  Robust.UnitTesting/Shared/Serialization/PropertyAndFieldDefinitionTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/DictionarySerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/YamlObjectSerializerTests/ImmutableListSerializationTest.cs
Labels: Area: Serialization, Type: Performance

#1747 Improves the Filter API.
  Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Shared/GameObjects/EntitySystem.cs
  Robust.Shared/Player/Filter.cs
Labels: Area: Networking, Misc: Quality of Life, Type: Cleanup, Type: Feature

#1752 Remove IActorComponent, rename BasicActorComponent to ActorComponent.
  Robust.Server/GameObjects/Components/Actor/ActorComponent.cs
  Robust.Server/GameObjects/Components/Actor/IActorComponent.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Server/GameStates/EntityViewCulling.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Server/Player/PlayerHelpers.cs
  Robust.Server/Player/PlayerSession.cs
Labels: Type: Cleanup

#1756 MIDI improvements
  Robust.Client/Audio/Midi/MidiManager.cs
  Robust.Client/Audio/Midi/MidiRenderer.cs
  Robust.Shared/Utility/StreamExt.cs
Labels: Area: Audio, Type: Cleanup

#1757 QueueDelete method for entities
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/IEntity.cs
  Robust.Shared/GameObjects/IEntityManager.cs
Labels: Area: ECS

#1761 Directed event improvements
  Robust.Shared/GameObjects/ComponentManager.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameObjects/IComponentManager.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.ComponentEvent.cs
Labels: Area: ECS, Type: Feature

#1773 Add test for YAML hot reloading
  Robust.Shared/Prototypes/PrototypeManager.cs
  Robust.UnitTesting/Shared/Prototypes/HotReloadTest.cs
  Robust.UnitTesting/Shared/Prototypes/PrototypeManager_Test.cs
Labels: Area: Serialization, Project: Tests

#1774 Adds ActorSystem to handle Attaching/Detaching players to/from entities sanely.
  Robust.Server/GameObjects/Components/Actor/ActorComponent.cs
  Robust.Server/GameObjects/EntitySystems/ActorSystem.cs
  Robust.Server/Player/IPlayerSession.cs
  Robust.Server/Player/PlayerSession.cs
Labels: Area: ECS, Type: Refactor

#1777 Add container helper for entity storage interaction
  Robust.Shared/Containers/ContainerHelpers.cs
Labels: Difficulty: 2 - Medium, Size: 2 - Small, Type: Feature

#1785 Make awake dispatch local events
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponent.Physics.cs
Labels: Area: Physics, Size: 1 - Tiny, Type: Bug

#1769 Add loglevel command line arg
  Robust.Client/CommandLineArgs.cs
  Robust.Client/GameController/GameController.cs
  Robust.Server/BaseServer.cs
  Robust.Server/CommandLineArgs.cs
Labels: Difficulty: 2 - Medium, Priority: 2-medium, Size: 2 - Small, Type: Feature

#1770 Make NetMessage name and group virtual to remove required boilerplate
  Robust.Client/Console/ClientConsoleHost.cs
  Robust.Client/Console/ScriptClient.cs
  Robust.Client/Debugging/DebugDrawingManager.cs
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/Placement/PlacementManager.cs
  Robust.Client/Player/PlayerManager.cs
  Robust.Client/Prototypes/ClientPrototypeManager.cs
  Robust.Client/ViewVariables/ViewVariablesManager.cs
  Robust.Server/Console/ServerConsoleHost.cs
  Robust.Server/Debugging/DebugDrawingManager.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Server/Player/PlayerManager.cs
  Robust.Server/Prototypes/ServerPrototypeManager.cs
  Robust.Server/Scripting/ScriptHost.cs
  Robust.Server/ViewVariables/ViewVariablesHost.cs
  Robust.Shared/Configuration/NetConfigurationManager.cs
  Robust.Shared/Network/INetManager.cs
  Robust.Shared/Network/Messages/Handshake/MsgEncryptionRequest.cs
  Robust.Shared/Network/Messages/Handshake/MsgEncryptionResponse.cs
  Robust.Shared/Network/Messages/Handshake/MsgLoginStart.cs
  Robust.Shared/Network/Messages/Handshake/MsgLoginSuccess.cs
  Robust.Shared/Network/Messages/MsgConCmd.cs
  Robust.Shared/Network/Messages/MsgConCmdAck.cs
  Robust.Shared/Network/Messages/MsgConCmdReg.cs
  Robust.Shared/Network/Messages/MsgConVars.cs
  Robust.Shared/Network/Messages/MsgEntity.cs
  Robust.Shared/Network/Messages/MsgMapStrClientHandshake.cs
  Robust.Shared/Network/Messages/MsgMapStrServerHandshake.cs
  Robust.Shared/Network/Messages/MsgMapStrStrings.cs
  Robust.Shared/Network/Messages/MsgPlacement.cs
  Robust.Shared/Network/Messages/MsgPlayerList.cs
  Robust.Shared/Network/Messages/MsgPlayerListReq.cs
  Robust.Shared/Network/Messages/MsgRay.cs
  Robust.Shared/Network/Messages/MsgReloadPrototypes.cs
  Robust.Shared/Network/Messages/MsgScriptEval.cs
  Robust.Shared/Network/Messages/MsgScriptResponse.cs
  Robust.Shared/Network/Messages/MsgScriptStart.cs
  Robust.Shared/Network/Messages/MsgScriptStartAck.cs
  Robust.Shared/Network/Messages/MsgScriptStop.cs
  Robust.Shared/Network/Messages/MsgState.cs
  Robust.Shared/Network/Messages/MsgStateAck.cs
  Robust.Shared/Network/Messages/MsgViewVariablesCloseSession.cs
  Robust.Shared/Network/Messages/MsgViewVariablesDenySession.cs
  Robust.Shared/Network/Messages/MsgViewVariablesModifyRemote.cs
  Robust.Shared/Network/Messages/MsgViewVariablesOpenSession.cs
  Robust.Shared/Network/Messages/MsgViewVariablesRemoteData.cs
  Robust.Shared/Network/Messages/MsgViewVariablesReqData.cs
  Robust.Shared/Network/Messages/MsgViewVariablesReqSession.cs
  Robust.Shared/Network/NetManager.cs
  Robust.Shared/Network/NetMessage.cs
  Robust.Shared/Network/StringTable.cs
  Robust.UnitTesting/RobustIntegrationTest.NetManager.cs
  Robust.UnitTesting/Server/GameObjects/ServerEntityNetworkManagerTest.cs
Labels: Area: Networking, Type: Refactor

#1687 Immediate broadphase updates
  Robust.Client/Debugging/DebugDrawing.cs
  Robust.Client/GameObjects/EntitySystems/DebugGridTileLookupSystem.cs
  Robust.Server/GameObjects/EntitySystems/TileLookup/GridTileLookupSystem.cs
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponent.Physics.cs
  Robust.Shared/GameObjects/Systems/EntityLookup.cs
  Robust.Shared/GameObjects/Systems/SharedGridTileLookupSystem.cs
  Robust.Shared/Physics/BroadPhase/SharedBroadPhaseSystem.cs
  Robust.Shared/Physics/DynamicTree.cs
  Robust.Shared/Physics/Dynamics/Fixture.cs
  Robust.Shared/Physics/Dynamics/PhysicsMap.cs
  Robust.Shared/Physics/IPhysBody.cs
Labels: Status: Help Wanted
