Repository space-wizards/RobustToolbox, pull requests merged in 2021-11, with the labels that each got.

#2146 Add test pooling
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Shared/Configuration/ConfigurationManager.cs
  Robust.Shared/Prototypes/PrototypeManager.cs
  Robust.UnitTesting/IocExt.cs
  Robust.UnitTesting/RTCVars.cs
  Robust.UnitTesting/RobustIntegrationTest.NetManager.cs
  Robust.UnitTesting/RobustIntegrationTest.cs
  Robust.UnitTesting/RobustIntegrationTestSetup.cs
  Robust.UnitTesting/RobustUnitTest.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
  Robust.UnitTesting/TestLogHandler.cs
Labels: Type: Performance, Project: Tests

#2209 Move LastModifiedTick out of Entity and into MetaDataComponent.
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/EntityManager.cs
Labels: Area: ECS

#2216 adds required check to the yamllinter
  Robust.Shared/Serialization/Manager/Definition/DataDefinition.cs
Labels: Status: Help Wanted

#2233 Fix FormattedMessage serialization and add tests
  Robust.Shared/Serialization/TypeSerializers/Implementations/FormattedMessageSerializer.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/FormattedMessageSerializerTest.cs
Labels: Type: Bug, Area: Serialization

#2238 Misc Engine Tweaks
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/ComponentProtoNameAttribute.cs
  Robust.Shared/GameObjects/EntitySystem.cs
  Robust.Shared/IoC/DependencyCollection.cs
Labels: Type: Feature, Area: ECS

#2244 Marked PlayerSession find methods on PlayerManager Obsolete
  Robust.Server/Console/Commands/PlayerCommands.cs
  Robust.Server/GameObjects/EntitySystems/EffectSystem.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Player/IPlayerManager.cs
  Robust.Server/Player/PlayerManager.cs
  Robust.Server/Player/PlayerSession.cs
  Robust.UnitTesting/Shared/EngineIntegrationTest_Test.cs
  Robust.UnitTesting/Shared/GameObjects/ContainerTests.cs
Labels: Type: Cleanup, Type: Refactor

#1978 Change Button Pressed to work with non-focus keybinds
  Robust.Client/UserInterface/Controls/BaseButton.cs
  Robust.Client/UserInterface/IUserInterfaceManager.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
Labels: Type: Feature, Area: UI

#2253 AppearanceComponent Cleanup
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Client/GameObjects/Components/Appearance/AppearanceComponent.cs
  Robust.Client/GameObjects/Components/Appearance/AppearanceVisualizer.cs
  Robust.Client/GameObjects/Components/Appearance/ClientAppearanceComponent.cs
  Robust.Client/GameObjects/EntitySystems/AppearanceSystem.cs
  Robust.Server/GameObjects/Components/Appearance/AppearanceComponent.cs
  Robust.Server/GameObjects/Components/Appearance/ServerAppearanceComponent.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Shared/GameObjects/Components/Appearance/AppearanceComponent.cs
  Robust.Shared/GameObjects/Components/Appearance/SharedAppearanceComponent.cs
Labels: Type: Cleanup, Area: Rendering, Status: Requires Content PR, Area: ECS

#2257 Add ToPrettyString method to EntityManager
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/IEntityManager.cs
Labels: Area: ECS
