Repository space-wizards/RobustToolbox, pull requests merged in 2021-04, with the labels that each got.

#1676 Add sprite path log
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
Labels: Priority: 3-low, Size: 1 - Tiny

#1675 Remove NetId requirement for local event subscriptions
  Robust.Shared/GameObjects/ComponentManager.cs
Labels: Area: ECS, Size: 1 - Tiny

#1681 Adds directed event for when an entity's BodyType changes.
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponent.Physics.cs
Labels: Area: ECS, Area: Physics

#1682 Makes a bunch of TransformComponent events directed.
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
Labels: Area: ECS

#1688 Adds abstract class for entity events that can be cancelled.
  Robust.Shared/GameObjects/EntityEvents.cs
Labels: Area: ECS

#1660 Component Lifetime Events
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.UnitTesting/Shared/GameObjects/ComponentManager_Tests.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.ComponentEvent.cs
Labels: Area: ECS, Type: Feature

#1696 Refactors MapManager to not do any networking.
  Robust.Client/ClientIoC.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/Map/ClientMapManager.cs
  Robust.Client/Map/IClientMapManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Map/IServerMapManager.cs
  Robust.Server/Map/ServerMapManager.cs
  Robust.Server/ServerIoC.cs
  Robust.Shared/Map/IMapManager.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/SharedIoC.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
Labels: Area: Networking

#1695 Refactors EntityManager to not do any networking.
  Robust.Client/ClientIoC.cs
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameObjects/ClientEntityNetworkManager.cs
  Robust.Client/GameObjects/EntityManagerExt.cs
  Robust.Client/GameObjects/EntitySystems/InputSystem.cs
  Robust.Client/GameObjects/IClientEntityManager.cs
  Robust.Client/GameObjects/IClientEntityManagerInternal.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Server/GameObjects/IServerEntityManager.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/GameObjects/ServerEntityNetworkManager.cs
  Robust.Server/ServerIoC.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/EntitySystem.cs
  Robust.Shared/GameObjects/IEntityManager.cs
  Robust.Shared/GameObjects/IEntityNetworkManager.cs
  Robust.UnitTesting/Server/GameObjects/ServerEntityNetworkManagerTest.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
Labels: Area: ECS, Area: Networking

#1697 Shared GameTiming no longer depends on INetManager
  Robust.Client/ClientIoC.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/Timing/ClientGameTiming.cs
  Robust.Client/Timing/IClientGameTiming.cs
  Robust.Client/Timing/PredictionGuard.cs
  Robust.Server/ServerIoC.cs
  Robust.Shared/SharedIoC.cs
  Robust.Shared/Timing/GameTiming.cs
  Robust.Shared/Timing/IGameTiming.cs
Labels: Area: Networking

#1705 ClydeTileDefinitionManager no longer throws when uninitialized, or when there are no tile definitions.
  Robust.Client/Map/ClydeTileDefinitionManager.cs
Labels: Misc: Quality of Life

#1704 Adds singleplayer support
  Robust.Client/BaseClient.cs
  Robust.Client/IBaseClient.cs
  Robust.Client/Player/IPlayerManager.cs
  Robust.Client/Player/LocalPlayer.cs
  Robust.Client/Player/PlayerManager.cs
Labels: Misc: Quality of Life, Priority: 5-bikeshed, Project: Client

#1710 Add directed start/end collision events.
  Robust.Shared/Physics/Dynamics/ContactManager.cs
Labels: Area: ECS, Area: Physics, Misc: Quality of Life

#1708 Use System.Numerics in a few Box2 methods to speed them up
  Robust.Shared.Maths/Box2.cs
Labels: Type: Performance

#1701 RSIs fail to load if they have duplicate states defined in their JSON.
  Robust.Client/ResourceManagement/ResourceTypes/RSIResource.cs
Labels: Area: Rendering, Type: Feature

#1711 Adds GameController options for games using RobustToolbox as a library.
  Robust.Client/ContentStart.cs
  Robust.Client/GameController.cs
  Robust.Client/GameController/GameController.Standalone.cs
  Robust.Client/GameControllerOptions.cs
  Robust.Client/IGameControllerInternal.cs
  Robust.Client/Utility/UserDataDir.cs
  Robust.Server/BaseServer.cs
  Robust.Server/IBaseServer.cs
  Robust.Server/Program.cs
  Robust.Shared/MountOptions.cs
  Robust.Shared/ProgramShared.cs
  Robust.UnitTesting/GameControllerDummy.cs
  Robust.UnitTesting/RobustIntegrationTest.cs
Labels: Misc: Quality of Life

#1724 Fix placement of grid tiles on the edge of a grid
  Robust.Shared/Map/CoordinatesExtensions.cs
Labels: Difficulty: 3 - Intermediate, Priority: 2-medium, Size: 1 - Tiny, Type: Bug

#1727 Make serialization work with backing fields automatically
  Robust.Client/Graphics/Shaders/ShaderPrototype.cs
  Robust.Shared/Containers/BaseContainer.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/Prototypes/EntityPrototype.cs
  Robust.Shared/Serialization/Manager/Attributes/NeverPushInheritanceAttribute.cs
  Robust.Shared/Serialization/Manager/SerializationDataDefinition.cs
  Robust.Shared/Serialization/Manager/SerializationManager.cs
  Robust.Shared/Utility/TypeHelpers.cs
  Robust.UnitTesting/Shared/Serialization/PropertyAndFieldDefinitionTest.cs
  Robust.UnitTesting/Shared/Serialization/SerializationPriorityTest.cs
  Robust.UnitTesting/Shared/Serialization/SerializationTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/AngleSerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/ArraySerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/Box2SerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/ColorSerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/ComponentRegistrySerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/Custom/Prototype/PrototypeIdListSerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/DictionarySerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/HashSetSerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/ListSerializerTest.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/RegexSerializerTest.cs
Labels: Area: Serialization, Type: Feature

#1720 SnapGridComponent Removal
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/GameObjects/Components/Light/ClientOccluderComponent.cs
  Robust.Client/GameObjects/EntitySystems/ClientOccluderSystem.cs
  Robust.Client/Map/ClientMapManager.cs
  Robust.Client/Placement/Modes/AlignSnapgridBorder.cs
  Robust.Client/Placement/Modes/AlignSnapgridCenter.cs
  Robust.Server/GameStates/EntityViewCulling.cs
  Robust.Server/Map/ServerMapManager.cs
  Robust.Server/Maps/YamlGridSerializer.cs
  Robust.Shared/GameObjects/Components/ITransformComponent.cs
  Robust.Shared/GameObjects/Components/Transform/SnapGridComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/Systems/SnapGridSystem.cs
  Robust.Shared/GameStates/GameStateMapData.cs
  Robust.Shared/Map/IMapChunk.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/IMapManager.cs
  Robust.Shared/Map/IMapManagerInternal.cs
  Robust.Shared/Map/MapChunk.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapManager.cs
  Robust.UnitTesting/Shared/GameObjects/Systems/AnchoredSystemTests.cs
  Robust.UnitTesting/Shared/GameObjects/Systems/TransformSystemTests.cs
  Robust.UnitTesting/Shared/Map/MapChunk_Tests.cs
  Robust.UnitTesting/Shared/Map/MapGrid_Tests.cs
Labels: Status: Requires Content PR, Type: Refactor
