Repository space-wizards/RobustToolbox, pull requests merged in 2021-03, with the labels that each got.

#1604 SoundSystem
  Robust.Client/Animations/AnimationTrackPlaySound.cs
  Robust.Client/ClientIoC.cs
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Client/Player/PlayerManager.cs
  Robust.Client/Player/PlayerSession.cs
  Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Server/Player/IPlayerSession.cs
  Robust.Server/ServerIoC.cs
  Robust.Shared/Audio/IAudioSystem.cs
  Robust.Shared/Audio/IPlayingAudioStream.cs
  Robust.Shared/Audio/SoundSystem.cs
  Robust.Shared/Players/ICommonSession.cs
Labels: Project: Shared, Status: Requires Content PR, Type: Feature

#1611 Fix buckling
  Robust.Shared/GameObjects/Systems/SharedGridTraversalSystem.cs
Labels: Area: Physics, Priority: 1-high, Size: 1 - Tiny, Type: Bug

#1636 adds custom typeserializers
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Server/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Shared/Physics/Dynamics/Fixture.cs
  Robust.Shared/Serialization/Manager/Attributes/DataFieldAttribute.cs
  Robust.Shared/Serialization/Manager/Attributes/DataFieldWithConstantAttribute.cs
  Robust.Shared/Serialization/Manager/Attributes/DataFieldWithFlagAttribute.cs
  Robust.Shared/Serialization/Manager/ISerializationManager.cs
  Robust.Shared/Serialization/Manager/SerializationDataDefinition.cs
  Robust.Shared/Serialization/Manager/SerializationManager.cs
  Robust.Shared/Serialization/Manager/SerializationManager_FlagsAndConstants.cs
  Robust.Shared/Serialization/Manager/SerializationManager_Typeserializers.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/Custom/ConstantSerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/Custom/FlagSerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/Custom/PrototypeIdSerializer.cs
  Robust.Shared/Utility/NullableHelper.cs
Labels: Area: Serialization, Type: Refactor

#1641 Add Enabled property to CollisionWake component.
  Robust.Shared/GameObjects/Components/CollisionWakeComponent.cs
  Robust.Shared/GameObjects/Components/NetIDs.cs
  Robust.Shared/GameObjects/Systems/CollisionWakeSystem.cs
Labels: Area: Physics

#1644 Entity Lifetime Levels
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityLifeState.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/IEntity.cs
  Robust.Shared/GameObjects/IMapInit.cs
  Robust.Shared/Map/MapManager.cs
Labels: Area: ECS, Type: Refactor

#1649 SoundSystem Improvements
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Shared/Player/Filter.cs
Labels: Area: Audio, Project: Shared, Status: Requires Content PR

#1651 Fix CopyWithTypeSerializer not copying when null
  Robust.Shared/Serialization/Manager/SerializationManager.cs
Labels: Area: Serialization, Priority: 2-medium, Size: 1 - Tiny, Type: Bug

#1656 Adds PrototypeIdHashSetSerializer for HashSet<string> prototype ID validation
  Robust.Shared/Serialization/TypeSerializers/Implementations/Custom/PrototypeIdHashSetSerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/Custom/PrototypeIdSerializer.cs
Labels: Area: Serialization

#1657 Visibility moved from session to EyeComponent
  Robust.Client/GameObjects/Components/Eye/EyeComponent.cs
  Robust.Server/GameObjects/Components/Eye/EyeComponent.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/Player/IPlayerSession.cs
  Robust.Shared/GameObjects/Components/Eye/SharedEyeComponent.cs
Labels: Area: Networking, Status: Requires Content PR, Type: Feature

#1653 Clear velocities on container insertion
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
Labels: Area: Physics, Type: Bug

#1662 Adds prototype "Variant" helper methods to IPrototypeManager
  Robust.Shared/Prototypes/PrototypeManager.cs
Labels: Misc: Quality of Life

#1629 Network View Bubble
  Robust.Client/GameStates/NetEntityOverlay.cs
  Robust.Client/GameStates/NetGraphOverlay.cs
  Robust.Client/Graphics/Overlays/OverlayManager.cs
  Robust.Server/GameObjects/IServerEntityManager.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/GameStates/EntityViewCulling.cs
  Robust.Server/GameStates/IServerGameStateManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Robust.Server.csproj
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/EntityState.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EntityDeletedMessage.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EntityTerminatingEvent.cs
  Robust.Shared/GameObjects/IEntityManager.cs
  Robust.Shared/Map/MapId.cs
  Robust.Shared/Physics/B2DynamicTree.cs
  Robust.Shared/Physics/DynamicTree.cs
  Robust.UnitTesting/Shared/Map/MapGrid_Tests.cs
Labels: Area: Networking, Status: Requires Content PR, Type: Feature, Type: Performance

#1652 Re-implement inertia
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponent.Physics.cs
  Robust.Shared/Physics/Collision/Collision.cs
  Robust.Shared/Physics/Collision/DistanceProxy.cs
  Robust.Shared/Physics/Collision/Shapes/EdgeShape.cs
  Robust.Shared/Physics/Collision/Shapes/IPhysShape.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeAabb.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeCircle.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeGrid.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeRect.cs
  Robust.Shared/Physics/Collision/Shapes/PolygonShape.cs
  Robust.Shared/Physics/Dynamics/Contacts/Contact.cs
  Robust.Shared/Physics/Dynamics/Fixture.cs
  Robust.Shared/Physics/IPhysBody.cs
  Robust.UnitTesting/Shared/Physics/Shape_Test.cs
Labels: Area: Physics, Status: Requires Content PR, Type: Feature

#1663 Adds a custom editor for Prototypes to ViewVariables.
  Robust.Client/ViewVariables/Editors/VVPropEditorIPrototype.cs
  Robust.Client/ViewVariables/Editors/VVPropEditorISelfSerializable.cs
  Robust.Client/ViewVariables/IViewVariablesManagerInternal.cs
  Robust.Client/ViewVariables/Instances/ViewVariablesInstanceEntity.cs
  Robust.Client/ViewVariables/Traits/ViewVariablesTraitMembers.cs
  Robust.Client/ViewVariables/VVPropEditor.cs
  Robust.Client/ViewVariables/ViewVariablesAddComponentWindow.xaml
  Robust.Client/ViewVariables/ViewVariablesAddWindow.xaml
  Robust.Client/ViewVariables/ViewVariablesAddWindow.xaml.cs
  Robust.Client/ViewVariables/ViewVariablesInstance.cs
  Robust.Client/ViewVariables/ViewVariablesManager.cs
  Robust.Client/ViewVariables/ViewVariablesPropertyControl.cs
  Robust.Server/ViewVariables/Traits/ViewVariablesTraitEntity.cs
  Robust.Server/ViewVariables/Traits/ViewVariablesTraitMembers.cs
  Robust.Server/ViewVariables/ViewVariablesHost.cs
  Robust.Server/ViewVariables/ViewVariablesSession.cs
  Robust.Server/ViewVariables/ViewVariablesTrait.cs
  Robust.Shared/Network/Messages/MsgViewVariablesModifyRemote.cs
  Robust.Shared/Prototypes/IPrototype.cs
  Robust.Shared/Reflection/ReflectionExtensions.cs
  Robust.Shared/Utility/PrettyPrint.cs
  Robust.Shared/ViewVariables/ViewVariablesBlob.cs
Labels: Misc: Quality of Life

#1671 PVS Bugfixes 1: The Debuggening
  Robust.Server/GameStates/EntityViewCulling.cs
  Robust.Server/GameStates/IServerGameStateManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Shared/Map/MapManager.cs
Labels: Area: Networking, Type: Bug
