Repository space-wizards/RobustToolbox, pull requests merged in 2021-12, with the labels that each got.

#2296 Remove Entity Transform/MetaData Component Cache
  Robust.Client/GameObjects/EntitySystems/RenderingTreeSystem.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/Systems/OccluderSystem.cs
  Robust.Shared/Physics/SharedBroadphaseSystem.cs
  Robust.UnitTesting/Server/GameObjects/Components/Container_Test.cs
  Robust.UnitTesting/Shared/Map/EntityCoordinates_Tests.cs
Labels: Area: ECS

#2295 The End of Entity (Komm, Süsser Todd: Part 1.0)
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/IComponentFactory.cs
  Robust.Shared/GameObjects/IEntity.cs
  Robust.Shared/GameObjects/IEntityManager.cs
  Robust.Shared/GameObjects/IEntitySerializer.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Prototypes/EntityPrototype.cs
  Robust.Shared/Prototypes/PrototypeManager.cs
  Robust.Shared/Serialization/RobustSerializer.cs
  Robust.Shared/ViewVariables/ViewVariablesBlob.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.ComponentEvent.cs
  Robust.UnitTesting/Shared/Map/MapManager_Tests.cs
Labels: Type: Cleanup, Type: Refactor, Area: ECS

#2310 Add new EntitySystem proxy methods.
  Robust.Shared/GameObjects/EntitySystem.Proxy.cs
  Robust.Shared/GameObjects/EntitySystem.Resolve.cs
  Robust.Shared/Physics/FixtureSystem.Shapes.cs
  Robust.UnitTesting/Server/Maps/MapLoaderTest.cs
Labels: Misc: Quality of Life, Area: ECS

#2324 Some minor PVS optimizations
  Robust.Server/GameStates/PVSSystem.cs
Labels: Type: Performance

#2213 Rich text redux
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/Console/Completions.cs
  Robust.Client/Console/ScriptClient.ScriptConsoleServer.cs
  Robust.Client/Console/ScriptConsoleClient.cs
  Robust.Client/Graphics/FontLibrary.cs
  Robust.Client/Log/DebugConsoleLogHandler.cs
  Robust.Client/UserInterface/Controls/ItemList.cs
  Robust.Client/UserInterface/Controls/Label.cs
  Robust.Client/UserInterface/Controls/LineEdit.cs
  Robust.Client/UserInterface/Controls/OutputPanel.cs
  Robust.Client/UserInterface/Controls/RichTextLabel.cs
  Robust.Client/UserInterface/Controls/TabContainer.cs
  Robust.Client/UserInterface/Controls/Tree.cs
  Robust.Client/UserInterface/CustomControls/DebugConsole.xaml.cs
  Robust.Client/UserInterface/RichTextEntry.cs
  Robust.Client/UserInterface/TextLayout.cs
  Robust.Client/UserInterface/UITheme.cs
  Robust.Server/Scripting/ScriptHost.cs
  Robust.Shared.Scripting/ScriptInstanceShared.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/FormattedMessageSerializer.cs
  Robust.Shared/Utility/CollectionExtensions.cs
  Robust.Shared/Utility/FormattedMessage.MarkupParser.cs
  Robust.Shared/Utility/FormattedMessage.cs
  Robust.Shared/Utility/Markup/Basic.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/FormattedMessageSerializerTest.cs
  Robust.UnitTesting/Shared/Utility/FormattedMessage_Test.cs
Labels: Type: Feature, Status: Requires Content PR

#2328 defer field DI for RegisterInstance
  Robust.Shared/IoC/DependencyCollection.cs
  Robust.Shared/IoC/IDependencyCollection.cs
  Robust.Shared/IoC/IoCManager.cs
  Robust.UnitTesting/Shared/IoC/IoCManager_Test.cs
Labels: Type: Feature

#2329 Fix CVars overridden by program arguments not replicating to the client
  Robust.Shared/Configuration/ConfigurationManager.cs
  Robust.Shared/Configuration/NetConfigurationManager.cs
Labels: Type: Bug, Size: Very Small

#2375 ByRefEvent attribute for events.
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Shared/GameObjects/ByRefEventAttribute.cs
  Robust.Shared/GameObjects/Components/Collidable/PhysicsInitializedEvent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EntParentChangedMessage.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EntityDirtyEvent.cs
  Robust.Shared/GameStates/ComponentStateEvents.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.RefDirectedEvents.cs
Labels: Misc: Quality of Life, Area: ECS

#2350 changes needed for inventory refactor
  Robust.Server/GameObjects/Components/Renderable/IRenderableComponent.cs
  Robust.Server/GameObjects/Components/Renderable/ISpriteRenderableComponent.cs
  Robust.Server/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Shared/Containers/BaseContainer.cs
  Robust.Shared/Containers/Container.cs
  Robust.Shared/Containers/ContainerHelpers.cs
  Robust.Shared/Containers/ContainerSlot.cs
  Robust.Shared/Containers/Events/ContainerAttemptEvents.cs
  Robust.Shared/Containers/Events/ContainerModifiedMessage.cs
  Robust.Shared/Containers/Events/EntInsertedIntoContainerMessage.cs
  Robust.Shared/Containers/Events/EntRemovedFromContainerMessage.cs
  Robust.Shared/Containers/IContainer.cs
  Robust.UnitTesting/Server/GameObjects/Components/Container_Test.cs
  Robust.UnitTesting/Shared/GameObjects/ContainerTests.cs
Labels: Type: Refactor
