Repository space-wizards/RobustToolbox, pull requests merged in 2021-02, with the labels that each got.

#1513 Console Unify
  Robust.Client/ClientIoC.cs
  Robust.Client/Console/ClientConsole.cs
  Robust.Client/Console/ClientConsoleHost.cs
  Robust.Client/Console/Commands/AddCompCommand.cs
  Robust.Client/Console/Commands/ClientSpawnCommand.cs
  Robust.Client/Console/Commands/ConfigurationCommands.cs
  Robust.Client/Console/Commands/ConsoleCommands.cs
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/Console/Commands/DumpMetadataMembersCommand.cs
  Robust.Client/Console/Commands/HelpCommands.cs
  Robust.Client/Console/Commands/LauncherAuthCommand.cs
  Robust.Client/Console/Commands/ListAssembliesCommand.cs
  Robust.Client/Console/Commands/LogCommands.cs
  Robust.Client/Console/Commands/QuitCommand.cs
  Robust.Client/Console/Commands/Scripting.cs
  Robust.Client/Console/Commands/SendGarbageCommand.cs
  Robust.Client/Console/Commands/SetInputContextCommand.cs
  Robust.Client/Console/IClientConsole.cs
  Robust.Client/Console/IClientConsoleHost.cs
  Robust.Client/GameController.cs
  Robust.Client/GameStates/NetGraphOverlay.cs
  Robust.Client/GameStates/NetInterpOverlay.cs
  Robust.Client/Input/InputManager.cs
  Robust.Client/Interfaces/Console/IConsoleCommand.cs
  Robust.Client/Interfaces/Console/IDebugConsole.cs
  Robust.Client/Log/DebugConsoleLogHandler.cs
  Robust.Client/UserInterface/CustomControls/DebugConsole.cs
  Robust.Client/UserInterface/UiCommands.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
  Robust.Client/ViewVariables/ViewVariablesCommand.cs
  Robust.Server/BaseServer.cs
  Robust.Server/Console/Commands/AddCompCommand.cs
  Robust.Server/Console/Commands/CVarCommand.cs
  Robust.Server/Console/Commands/DeleteCommand.cs
  Robust.Server/Console/Commands/ListAssembliesCommand.cs
  Robust.Server/Console/Commands/ListCommands.cs
  Robust.Server/Console/Commands/LogCommands.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/Console/Commands/PlayerCommands.cs
  Robust.Server/Console/Commands/SpawnCommand.cs
  Robust.Server/Console/Commands/SysCommands.cs
  Robust.Server/Console/ConsoleShell.cs
  Robust.Server/Console/IServerConsoleHost.cs
  Robust.Server/Console/ISystemConsoleManager.cs
  Robust.Server/Console/ServerConsoleHost.cs
  Robust.Server/Console/SystemConsoleManager.cs
  Robust.Server/Console/SystemConsoleManagerDummy.cs
  Robust.Server/Interfaces/Console/IClientCommand.cs
  Robust.Server/Interfaces/Console/IConsoleShell.cs
  Robust.Server/ServerIoC.cs
  Robust.Shared/Configuration/ConfigurationCommands.cs
  Robust.Shared/Console/ConsoleHost.cs
  Robust.Shared/Console/ConsoleShell.cs
  Robust.Shared/Console/ICommand.cs
  Robust.Shared/Console/IConsoleCommand.cs
  Robust.Shared/Console/IConsoleHost.cs
  Robust.Shared/Console/IConsoleShell.cs
  Robust.UnitTesting/RobustIntegrationTest.cs
Labels: Project: Shared, Type: Refactor

#1530 Makes sudo command show output to user.
  Robust.Server/Console/ServerConsoleHost.cs
Labels: Type: Feature

#1553 PauseManager moved to Shared
  Robust.Client/ClientIoC.cs
  Robust.Client/GameController.cs
  Robust.Client/GameObjects/Components/IgnorePauseComponent.cs
  Robust.Client/UserInterface/Controls/ItemList.cs
  Robust.Server/BaseServer.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Server/ServerIoC.cs
  Robust.Server/Timing/PauseManager.cs
  Robust.Server/Timing/PauseManagerExt.cs
  Robust.Shared/GameObjects/Components/IgnorePauseComponent.cs
  Robust.Shared/GameObjects/Components/SharedIgnorePauseComponent.cs
  Robust.Shared/GameObjects/Components/Timers/TimerComponent.cs
  Robust.Shared/GameObjects/Components/Timers/TimerExtensions.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/IMapInit.cs
  Robust.Shared/SharedIoC.cs
  Robust.Shared/Timing/IPauseManager.cs
  Robust.Shared/Timing/ITimerManager.cs
  Robust.Shared/Timing/PauseManager.cs
  Robust.Shared/Timing/Timer.cs
  Robust.Shared/Timing/TimerManager.cs
  Robust.UnitTesting/Shared/Timing/TimerTest.cs
Labels: Project: Shared, Type: Refactor

#1571 Add YAML hot reloading
  Robust.Client/ClientIoC.cs
  Robust.Client/GameController.cs
  Robust.Client/Graphics/Shaders/ShaderPrototype.cs
  Robust.Client/Prototypes/ClientPrototypeManager.cs
  Robust.Server/BaseServer.cs
  Robust.Server/Console/ConGroupController.cs
  Robust.Server/Console/IConGroupControllerImplementation.cs
  Robust.Server/Prototypes/ServerPrototypeManager.cs
  Robust.Shared/ContentPack/IResourceManager.cs
  Robust.Shared/ContentPack/ResourceManager.cs
  Robust.Shared/Network/Messages/MsgReloadPrototypes.cs
  Robust.Shared/Prototypes/EntityPrototype.cs
  Robust.Shared/Prototypes/IPrototype.cs
  Robust.Shared/Prototypes/PrototypeManager.cs
  Robust.Shared/Serialization/IRobustMappedStringSerializer.cs
  Robust.Shared/Serialization/RobustMappedStringSerializer.cs
Labels: Status: Requires Content PR, Type: Feature

#1568 Remove AiLogicProcessor
  Robust.Server/AI/AiLogicProcessor.cs
  Robust.Server/AI/AiLogicProcessorAttribute.cs
Labels: Status: Requires Content PR, Type: Feature

#1551 Sprite Rendering Bugfixes
  Resources/Prototypes/dbg_rotationMarker.yml
  Resources/Textures/debugRotation.rsi/direction1.png
  Resources/Textures/debugRotation.rsi/direction1.xcf
  Resources/Textures/debugRotation.rsi/direction4.png
  Resources/Textures/debugRotation.rsi/direction4.xcf
  Resources/Textures/debugRotation.rsi/meta.json
  Resources/Textures/debugRotation.rsi/uvmap.xcf
  Robust.Client/GameObjects/Components/Renderable/ISpriteComponent.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Client/Graphics/Clyde/Clyde.RenderHandle.cs
  Robust.Client/Graphics/Clyde/Clyde.Rendering.cs
  Robust.Client/Graphics/Drawing/DrawingHandleBase.cs
  Robust.Client/Graphics/Drawing/DrawingHandleWorld.cs
  Robust.Server/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Shared.Maths/Angle.cs
  Robust.Shared.Maths/Matrix3.cs
  Robust.Shared/GameObjects/Components/Renderable/SharedSpriteComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.UnitTesting/Shared/Maths/Angle_Test.cs
Labels: Area: Rendering, Project: Client, Type: Bug

#1582 Register Components Obsolete
  Robust.Shared/GameObjects/ComponentFactory.cs
  Robust.Shared/GameObjects/IComponentFactory.cs
Labels: Type: Cleanup

#1587 Fixes Overwriting a Deleted Component
  Robust.Shared/GameObjects/ComponentManager.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.UnitTesting/Shared/GameObjects/ComponentManager_Tests.cs
  Robust.UnitTesting/Shared/Physics/CollisionManager_Test.cs
Labels: Area: ECS, Type: Bug

#1583 Add individual layer offset
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
Labels: Area: Rendering, Type: Feature

#1536 Post shader will use real sprite bounding box
  Robust.Client/GameObjects/Components/Renderable/ISpriteComponent.cs
  Robust.Client/GameObjects/Components/Renderable/ISpriteLayer.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Client/Graphics/Clyde/Clyde.cs
  Robust.Shared.Maths/Box2.cs
Labels: Area: Rendering, Type: Feature

#1419 Implemented erasing rectangular areas
  Robust.Client/Placement/PlacementManager.cs
  Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Shared/Enums/NetworkEnums.cs
  Robust.Shared/Network/Messages/MsgPlacement.cs
Labels: Status: Stale

#1600 ICommonSession Improvements + Player Filter
  Robust.Client/Player/IPlayerManager.cs
  Robust.Client/Player/IPlayerSession.cs
  Robust.Client/Player/PlayerManager.cs
  Robust.Client/Player/PlayerSession.cs
  Robust.Server/Console/ServerConsoleHost.cs
  Robust.Server/Player/IPlayerManager.cs
  Robust.Server/Player/IPlayerSession.cs
  Robust.Server/Player/PlayerManager.cs
  Robust.Server/Player/PlayerSession.cs
  Robust.Shared/Player/Filter.cs
  Robust.Shared/Players/IBaseSession.cs
  Robust.Shared/Players/ICommonSession.cs
  Robust.Shared/Players/ISharedPlayerManager.cs
Labels: Type: Cleanup, Type: Feature
