Repository space-wizards/RobustToolbox, pull requests merged in 2021-08, with the labels that each got.

#1917 Clyde can now render multiple viewports with different maps.
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Server/GameStates/EntityViewCulling.cs
Labels: Area: Rendering, Type: Bug

#1892 Fix containers with entities that do not exist yet
  Robust.Client/GameObjects/EntitySystems/ClientContainerSystem.cs
  Robust.Client/GameObjects/EntitySystems/ContainerSystem.cs
  Robust.Server/Containers/ContainerSystem.cs
  Robust.Shared/Containers/BaseContainer.cs
  Robust.Shared/Containers/Container.cs
  Robust.Shared/Containers/ContainerManagerComponent.cs
  Robust.Shared/Containers/ContainerSlot.cs
  Robust.Shared/Containers/IContainer.cs
  Robust.Shared/Containers/SharedContainerSystem.cs
  Robust.UnitTesting/Server/GameObjects/Components/Container_Test.cs
  Robust.UnitTesting/Shared/GameObjects/ContainerTests.cs
Labels: Area: Networking, Difficulty: 3 - Intermediate, Priority: 1-high, Size: 2 - Small, Type: Bug

#1928 Add Friend classes to C# with the help of Analyzers and Attributes.
  Robust.Analyzers/FriendAnalyzer.cs
  Robust.Analyzers/Robust.Analyzers.csproj
  Robust.Shared/Analyzers/FriendAttribute.cs
Labels: Type: Feature, Misc: Quality of Life, Area: ECS

#1938 Add benchmarks for serializing flags
  Robust.Benchmarks/Serialization/Copy/SerializationCopyBenchmark.cs
  Robust.Benchmarks/Serialization/Definitions/BenchmarkFlags.cs
  Robust.Benchmarks/Serialization/Read/SerializationReadBenchmark.cs
  Robust.Benchmarks/Serialization/Write/SerializationWriteBenchmark.cs
Labels: Type: Performance, Area: Serialization

#1939 Add tests for serializing flags
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/Custom/FlagSerializerTest.cs
Labels: Project: Tests, Area: Serialization

#1940 Fix FlagSerializer not working with 1 << 31 and add test
  Robust.Shared/Serialization/Manager/ISerializationManager.cs
  Robust.Shared/Serialization/Manager/SerializationManager.FlagsAndConstants.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/Custom/FlagSerializer.cs
  Robust.UnitTesting/Shared/Serialization/TypeSerializers/Custom/FlagSerializerTest.cs
Labels: Type: Bug, Project: Shared, Area: Serialization

#1927 Make no rotation work when eye is rotated
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Client/Graphics/Clyde/Clyde.RenderHandle.cs
Labels: Project: Client, Area: Rendering, Size: 2 - Small, Status: Needs Review

#1845 PVS is now aware of entity anchoring.
  Robust.Server/GameStates/EntityViewCulling.cs
  Robust.Server/Map/ServerMapManager.cs
  Robust.Shared/GameObjects/Components/Map/MapGridComponent.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/Map/IMapChunk.cs
  Robust.Shared/Map/IMapChunkInternal.cs
  Robust.Shared/Map/IMapGridInternal.cs
  Robust.Shared/Map/MapChunk.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.UnitTesting/Shared/Map/MapChunk_Tests.cs
Labels: Type: Performance, Area: Networking

#1956 Cleans up EntityCoordinates, split coordinates into their own files.
  Robust.Shared/Map/EntityCoordinates.cs
  Robust.Shared/Map/MapCoordinates.cs
  Robust.Shared/Map/ScreenCoordinates.cs
  Robust.UnitTesting/Shared/Map/EntityCoordinates_Tests.cs
Labels: Type: Cleanup

#1931 Add support for struct directed events, add by-ref directed/broadcast events.
  Robust.Client/GameObjects/EntitySystems/ClientOccluderSystem.cs
  Robust.Client/GameObjects/EntitySystems/RenderingTreeSystem.cs
  Robust.Server/GameObjects/EntitySystems/TileLookup/GridTileLookupSystem.cs
  Robust.Shared/Containers/SharedContainerSystem.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameObjects/EntityEventBus.Ordering.cs
  Robust.Shared/GameObjects/EntityEvents.cs
  Robust.Shared/GameObjects/EntitySystem.Subscriptions.cs
  Robust.Shared/GameObjects/EntitySystem.cs
  Robust.Shared/GameObjects/Systems/EntityLookup.cs
  Robust.Shared/GameObjects/Systems/OccluderSystem.cs
  Robust.Shared/GameObjects/Systems/SharedGridTraversalSystem.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.cs
  Robust.Shared/Physics/SharedBroadphaseSystem.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.ComponentEvent.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.RefBroadcastEvents.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.RefDirectedEvents.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.RefSortedEvents.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.SystemEvent.cs
  Robust.UnitTesting/Shared/GameObjects/Systems/AnchoredSystemTests.cs
  Robust.UnitTesting/Shared/GameObjects/Systems/TransformSystemTests.cs
Labels: Area: ECS

#1962 Adds new helpful filter methods.
  Robust.Shared/Player/Filter.cs
Labels: Misc: Quality of Life

#1987 Adds by-ref and struct event support to ComponentEvents
  Robust.Client/GameObjects/EntitySystems/ContainerSystem.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameStates/ComponentStateEvents.cs
Labels: Area: ECS

#1988 Adds ComponentGetState ECS event
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Server/GameStates/EntityViewCulling.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/ComponentManager.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameObjects/IComponentManager.cs
  Robust.Shared/GameStates/ComponentStateEvents.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.ComponentEvent.cs
Labels: Misc: Quality of Life, Area: ECS
