Repository space-wizards/RobustToolbox, pull requests merged in 2021-06, with the labels that each got.

#1811 Remove Map & Grid Entity Pivoting
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/Map/ClientMapManager.cs
  Robust.Client/Map/IClientMapManager.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/IEntityManager.cs
  Robust.Shared/Map/MapManager.cs
Labels: Area: ECS, Area: Networking, Type: Cleanup

#1818 Add more tolerance for if player sessions are connected to dead entities
  Robust.Server/Player/PlayerSession.cs
Labels: Type: Bug

#1824 Adds public methods to ActorSystem.
  Robust.Server/GameObjects/EntitySystems/ActorSystem.cs
  Robust.Server/Player/PlayerSession.cs
Labels: Area: ECS

#1778 ComponentHandleState event
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameStates/ComponentStateEvents.cs
Labels: Area: ECS

#1823 Implement subscription ordering into EventBus.
  Robust.Shared/ContentPack/ModLoader.cs
  Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameObjects/EntityEventBus.Ordering.cs
  Robust.Shared/GameObjects/EntitySystem.Subscriptions.cs
  Robust.Shared/GameObjects/EntitySystemManager.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/Input/Binding/CommandBindRegistry.cs
  Robust.Shared/Utility/TopologicalSort.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.ComponentEvent.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.SystemEvent.cs
  Robust.UnitTesting/Shared/Input/Binding/CommandBindRegistry_Test.cs
Labels: Area: ECS, Type: Feature

#1832 Remove Engine Component Events
  Robust.Client/GameObjects/Components/Light/PointLightComponent.cs
  Robust.Client/GameObjects/PlayerMessages.cs
  Robust.Client/Player/LocalPlayer.cs
  Robust.Server/GameObjects/Components/Actor/ActorComponent.cs
  Robust.Server/GameObjects/EntitySystems/ActorSystem.cs
  Robust.Shared/Containers/BaseContainer.cs
  Robust.Shared/Containers/ContainerContentsModifiedMessage.cs
  Robust.Shared/GameObjects/ComponentMessages/Messages.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
Labels: Area: ECS, Type: Cleanup

#1829 Engine Entity Anchoring
  Robust.Client/GameObjects/Components/Appearance/AppearanceComponent.cs
  Robust.Client/GameObjects/Components/Eye/EyeComponent.cs
  Robust.Client/GameObjects/Components/Light/ClientOccluderComponent.cs
  Robust.Client/GameObjects/Components/Light/PointLightComponent.cs
  Robust.Client/GameObjects/EntitySystems/ClientOccluderSystem.cs
  Robust.Server/GameStates/EntityViewCulling.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Shared/Containers/BaseContainer.cs
  Robust.Shared/Containers/ContainerManagerComponent.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/ComponentManager.cs
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponent.Physics.cs
  Robust.Shared/GameObjects/Components/CollisionWakeComponent.cs
  Robust.Shared/GameObjects/Components/DebugExceptionComponents.cs
  Robust.Shared/GameObjects/Components/IgnorePauseComponent.cs
  Robust.Shared/GameObjects/Components/Map/MapGridComponent.cs
  Robust.Shared/GameObjects/Components/Transform/SnapGridComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Entity.cs
  Robust.Shared/GameObjects/EntityLifeState.cs
  Robust.Shared/GameObjects/IComponent.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.cs
  Robust.Shared/GameObjects/Systems/SnapGridSystem.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/MapChunk.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.UnitTesting/Client/GameObjects/Components/TransformComponentTests.cs
  Robust.UnitTesting/Client/GameObjects/Components/Transform_Test.cs
  Robust.UnitTesting/Server/GameObjects/ThrowingEntityDeletion_Test.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
  Robust.UnitTesting/Shared/GameObjects/IEntityManagerTests.cs
  Robust.UnitTesting/Shared/GameObjects/Systems/AnchoredSystemTests.cs
Labels: Status: Requires Content PR, Type: Feature

#1833 DependencyCollection Children
  Robust.Shared/IoC/DependencyCollection.cs
  Robust.Shared/IoC/IDependencyCollection.cs
Labels: Type: Feature

#1835 #1462 extracted MapGrid's HasGravity property to separate Content com…
  Robust.Shared/GameObjects/Components/Map/MapGridComponent.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
Labels: Status: Requires Content PR, Type: Refactor
