Repository space-wizards/RobustToolbox, pull requests merged in 2022-01, with the labels that each got.

#2384 TeleportTo upgrades
  Robust.Server/Console/Commands/PlayerCommands.cs
Labels: Type: Feature, Priority: 3-Low, Misc: Quality of Life

#2390 Tiles Name->Id DisplayName->Name
  Robust.Client/UserInterface/CustomControls/TileSpawnWindow.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Shared/Map/ITileDefinition.cs
  Robust.Shared/Map/TileDefinitionManager.cs
Labels: Status: Requires Content PR

#2412 Move popup above modal in `RootControl`
  Robust.Client/UserInterface/UserInterfaceManager.cs
Labels: Area: UI

#2423 removes componentdependencies
  Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyAttribute.cs
  Robust.Shared/GameObjects/ComponentDependencies/ComponentDependencyManager.cs
  Robust.Shared/GameObjects/Components/IComponentDependencyManager.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/Prototypes/EntityPrototype.cs
  Robust.Shared/SharedIoC.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
  Robust.UnitTesting/Shared/GameObjects/ComponentDependencies_Tests.cs
Labels: Status: Requires Content PR

#2426 Don't dirty entities when `NetSyncEnabled` is false
  Robust.Shared/GameObjects/Component.cs
Labels: Area: Networking, Status: Needs Review

#2424 Makes VirtualController an abstract class inheriting EntitySystem
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/Physics/Controllers/VirtualController.cs
  Robust.Shared/Physics/Dynamics/SharedPhysicsMapComponent.cs
Labels: Misc: Quality of Life, Area: Physics, Area: ECS

#2418 Prevent disembowelling on tile removal.
  Robust.Shared/GameObjects/Systems/EntityLookup.Queries.cs
  Robust.Shared/GameObjects/Systems/EntityLookup.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.cs
Labels: Type: Bug, Size: Very Small

#2432 Sprite offset rendering fix
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
Labels: Type: Bug, Area: Rendering

#2422 Stop updating entity tree on pre-delete un-anchor event
  Robust.Shared/GameObjects/Systems/EntityLookup.cs
Labels: Type: Performance

#2437 return -> continue
  Robust.Client/GameObjects/EntitySystems/AppearanceSystem.cs
Labels: Type: Bug, Size: Very Small

#2448 Prevent `CreateAudioSource()` from erroring/crashing in debug when hitting source limit
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Client/Graphics/Audio/ClydeAudio.cs
  Robust.Client/Graphics/Audio/ProxyClydeAudio.cs
  Robust.Client/Graphics/IClydeAudio.cs
Labels: Size: Very Small, Area: Audio

#2317 Fix maplinearvelocity?
  Robust.Shared/GameObjects/Components/Collidable/PhysicsComponent.Physics.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.Body.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
Labels: Status: Stale

#2470 Move some static helpers to container system
  Robust.Shared/Containers/ContainerHelpers.cs
  Robust.Shared/Containers/SharedContainerSystem.cs
Labels: Status: Requires Content PR
