Repository space-wizards/RobustToolbox, pull requests merged in 2022-03, with the labels that each got.

#2574 Fix lsmap and lsgrid
  Robust.Server/Console/Commands/MapCommands.cs
Labels: Size: Very Small

#2586 Mark C# events on MapManager as Obsolete
  Robust.Client/GameObjects/EntitySystems/GridRenderingSystem.cs
  Robust.Client/GameObjects/EntitySystems/RenderingTreeSystem.cs
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Graphics/Clyde/Clyde.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Graphics/IClydeInternal.cs
  Robust.Client/Physics/PhysicsSystem.cs
  Robust.Client/Placement/PlacementManager.cs
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs
  Robust.Shared/GameObjects/Systems/OccluderSystem.cs
  Robust.Shared/GameObjects/Systems/SharedMapSystem.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.cs
  Robust.Shared/Map/IMapManager.cs
  Robust.Shared/Map/MapManager.GridCollection.cs
  Robust.Shared/Map/NetworkedMapManager.cs
  Robust.Shared/Physics/SharedBroadphaseSystem.cs
Labels: Type: Feature, Type: Cleanup

#2590 Adds MemoryContentRoot.
  Robust.Shared/ContentPack/MemoryContentRoot.cs
Labels: Type: Feature

#2597 Grid Components Allocate Grids
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Server/Maps/YamlGridSerializer.cs
  Robust.Shared/GameObjects/Components/Map/MapComponent.cs
  Robust.Shared/GameObjects/Components/Map/MapGridComponent.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/IEntityManager.Components.cs
  Robust.Shared/GameStates/GameStateMapData.cs
  Robust.Shared/Map/IMapManager.cs
  Robust.Shared/Map/IMapManagerInternal.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapManager.GridCollection.cs
  Robust.Shared/Map/MapManager.MapCollection.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Map/NetworkedMapManager.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
  Robust.UnitTesting/Shared/GameObjects/Systems/AnchoredSystemTests.cs
Labels: Type: Feature, Area: ECS

#2610 fix sequence node Except()
  Robust.Shared/Physics/Dynamics/Fixture.cs
  Robust.Shared/Physics/FixtureSystem.cs
  Robust.Shared/Serialization/Markdown/DataNode.cs
  Robust.Shared/Serialization/Markdown/Sequence/SequenceDataNode.cs
Labels: Status: Requires Content PR

#2650 Add overload to IntersectRayWithPredicate.
  Robust.Shared/GameObjects/Systems/OccluderSystem.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.Queries.cs
Labels: Area: Physics, Status: Needs Review

#2656 ECS collision wake
  Robust.Shared/GameObjects/Components/CollisionWakeComponent.cs
  Robust.Shared/GameObjects/Systems/CollisionWakeSystem.cs
Labels: Area: Physics, Status: Requires Content PR

#2622 Cache Sprite AABBs
  Robust.Client/GameObjects/Components/Renderable/ISpriteComponent.cs
  Robust.Client/GameObjects/Components/Renderable/ISpriteLayer.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
Labels: Area: Rendering

#2585 Add a is-In-container metadata flag.
  Robust.Shared/Containers/BaseContainer.cs
  Robust.Shared/Containers/Container.cs
  Robust.Shared/Containers/ContainerHelpers.cs
  Robust.Shared/Containers/ContainerSlot.cs
  Robust.Shared/Containers/IContainer.cs
  Robust.Shared/Containers/SharedContainerSystem.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs
  Robust.Shared/GameObjects/Systems/MetaDataSystem.cs
  Robust.Shared/GameObjects/Systems/SharedGridTraversalSystem.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.Bodies.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.Velocities.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.UnitTesting/Server/GameObjects/Components/Container_Test.cs
Labels: Status: Requires Content PR
