Repository space-wizards/RobustToolbox, pull requests merged in 2022-11, with the labels that each got.

#3251 Clean up audiosystem
  Robust.Client/Audio/AudioStream.cs
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Shared/Audio/IPlayingAudioStream.cs
  Robust.Shared/GameObjects/EntitySystemMessages/AudioMessages.cs
  Robust.Shared/GameObjects/Systems/SharedAudioSystem.cs
Labels: Issue: Needs Cleanup, Area: Audio

#3436 TextEdit control & a bunch of other stuff
  OpenToolkit.GraphicsLibraryFramework/OpenToolkit.GraphicsLibraryFramework.csproj
  RELEASE-NOTES.md
  Resources/Locale/en-US/commands.ftl
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/Console/Commands/UITestCommand.cs
  Robust.Client/GameController/GameController.Input.cs
  Robust.Client/GameController/GameController.cs
  Robust.Client/Graphics/Clyde/Clyde.Events.cs
  Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Graphics/Clyde/Windowing/Glfw.Events.cs
  Robust.Client/Graphics/Clyde/Windowing/Glfw.Windows.cs
  Robust.Client/Graphics/Clyde/Windowing/Glfw.cs
  Robust.Client/Graphics/Clyde/Windowing/IWindowingImpl.cs
  Robust.Client/Graphics/Clyde/Windowing/SDL2Api.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.Events.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.RawEvents.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.WindowThread.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.Windows.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.cs
  Robust.Client/Graphics/IClyde.cs
  Robust.Client/Graphics/IClydeInternal.cs
  Robust.Client/IGameControllerInternal.cs
  Robust.Client/Input/EngineContexts.cs
  Robust.Client/Input/Events.cs
  Robust.Client/Input/InputManager.cs
  Robust.Client/UserInterface/Control.Input.cs
  Robust.Client/UserInterface/Controls/LineEdit.cs
  Robust.Client/UserInterface/Controls/OSWindow.cs
  Robust.Client/UserInterface/Controls/OutputPanel.cs
  Robust.Client/UserInterface/Controls/TextEdit.cs
  Robust.Client/UserInterface/Controls/TextEditShared.cs
  Robust.Client/UserInterface/Controls/UIRoot.cs
  Robust.Client/UserInterface/CustomControls/DebugConsole.xaml.Completions.cs
  Robust.Client/UserInterface/CustomControls/TextEditRopeViz.cs
  Robust.Client/UserInterface/IUserInterfaceManager.cs
  Robust.Client/UserInterface/IUserInterfaceManagerInternal.cs
  Robust.Client/UserInterface/RichTextEntry.cs
  Robust.Client/UserInterface/UserInterfaceManager.Input.cs
  Robust.Client/UserInterface/UserInterfaceManager.Layout.cs
  Robust.Client/UserInterface/UserInterfaceManager.Roots.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
  Robust.Client/UserInterface/WordWrap.cs
  Robust.Shared.Maths/Easings.cs
  Robust.Shared.Maths/Properties/AssemblyInfo.cs
  Robust.Shared/Input/BoundKeyEventArgs.cs
  Robust.Shared/Input/BoundKeyMap.cs
  Robust.Shared/Input/KeyFunctions.cs
  Robust.Shared/Utility/FormattedMessage.cs
  Robust.Shared/Utility/StringEnumerateHelpers.cs
  Robust.Shared/Utility/TextRope.cs
  Robust.UnitTesting/Client/UserInterface/Controls/LineEditTest.cs
  Robust.UnitTesting/Client/UserInterface/Controls/TextEditSharedTest.cs
  Robust.UnitTesting/GameControllerDummy.cs
  Robust.UnitTesting/Shared/Utility/FormattedMessage_Test.cs
  Robust.UnitTesting/Shared/Utility/TextRope_Test.cs
Labels: Area: UI, Size: Very Large

#3471 Audio and other misc replay related changes
  Robust.Client/ClientIoC.cs
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Client/Player/PlayerManager.cs
  Robust.Client/Replays/ReplayRecordingManager.cs
  Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/Player/PlayerManager.cs
  Robust.Server/Replays/IInternalReplayManager.cs
  Robust.Server/Replays/IServerReplayRecordingManager.cs
  Robust.Server/Replays/ReplayRecordingManager.cs
  Robust.Server/ServerIoC.cs
  Robust.Shared/Audio/SoundSystem.cs
  Robust.Shared/GameObjects/EntitySystem.cs
  Robust.Shared/GameObjects/IEntityNetworkManager.cs
  Robust.Shared/GameObjects/Systems/SharedAudioSystem.cs
  Robust.Shared/Players/ISharedPlayerManager.cs
  Robust.Shared/Replays/IReplayRecordingManager.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
Labels: Status: Requires Content PR
