Repository space-wizards/RobustToolbox, pull requests merged in 2022-04, with the labels that each got.

#2666 Cleans up and improves MIDI code significantly.
  Robust.Client/Audio/Midi/IMidiManager.cs
  Robust.Client/Audio/Midi/IMidiRenderer.cs
  Robust.Client/Audio/Midi/MidiManager.Conversion.cs
  Robust.Client/Audio/Midi/MidiManager.cs
  Robust.Client/Audio/Midi/MidiRenderer.cs
  Robust.Shared/Audio/Midi/MidiEvent.cs
  Robust.Shared/Audio/Midi/RobustMidiCommand.cs
  Robust.Shared/Audio/Midi/RobustMidiEvent.cs
  Robust.Shared/Robust.Shared.csproj
Labels: Area: Audio

#2701 Add "midipanic" command.
  Resources/Locale/en-US/midi-commands.ftl
  Robust.Client/Audio/Midi/Commands/MidiPanicCommand.cs
  Robust.Client/Audio/Midi/IMidiManager.cs
  Robust.Client/Audio/Midi/MidiManager.cs
  Robust.Client/Audio/Midi/MidiRenderer.cs
Labels: Area: Audio

#2727 Make MappingDataNode.Except() not recursive
  Robust.Server/Maps/MapLoader.cs
  Robust.Shared/Serialization/Markdown/DataNode.cs
  Robust.Shared/Serialization/Markdown/Mapping/MappingDataNode.cs
  Robust.Shared/Serialization/Markdown/Sequence/SequenceDataNode.cs
Labels: Area: Serialization

#2737 ZSTD game states + other improvements
  Robust.Client/GameController/GameController.cs
  Robust.Server/BaseServer.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Shared/CVars.cs
  Robust.Shared/Network/Messages/MsgEntity.cs
  Robust.Shared/Network/Messages/MsgScriptResponse.cs
  Robust.Shared/Network/Messages/MsgState.cs
  Robust.Shared/Network/Messages/MsgViewVariablesModifyRemote.cs
  Robust.Shared/Network/Messages/MsgViewVariablesRemoteData.cs
  Robust.Shared/Network/Messages/MsgViewVariablesReqData.cs
  Robust.Shared/Network/Messages/MsgViewVariablesReqSession.cs
  Robust.Shared/SharedIoC.cs
  Robust.Shared/Threading/ParallelManager.cs
  Robust.Shared/Utility/StreamExt.cs
  Robust.Shared/Utility/ZStd.cs
Labels: Issue: Performance, Area: Networking

#2752 Change LineEdit to keep cursor position
  Robust.Client/UserInterface/Controls/LineEdit.cs
Labels: Issue: Feature Request, Area: UI, Size: Very Small

#2768 Add null check to VV string parsing
  Robust.Client/ViewVariables/Editors/VVPropEditorString.cs
Labels: Issue: Bug, Size: Very Small

#2779 Allow int uniforms to specify precision
  Robust.Client/Graphics/Shaders/ParsedShader.cs
Labels: Size: Very Small
