Repository space-wizards/RobustToolbox, pull requests merged in 2022-10, with the labels that each got.

#3298 Add build property to use system SQLite3
  MSBuild/Robust.DefineConstants.targets
  MSBuild/Robust.Properties.targets
  Robust.Client/Console/Commands/LauncherAuthCommand.cs
  Robust.Client/Robust.Client.csproj
  Robust.Server/Robust.Server.csproj
Labels: Platform: Other

#3279 Remove obsolete GridId and all references to it
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/Debugging/DebugAnchoringSystem.cs
  Robust.Client/GameObjects/Components/Light/ClientOccluderComponent.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/GameObjects/EntitySystems/ClientOccluderSystem.cs
  Robust.Client/GameObjects/EntitySystems/EffectSystem.cs
  Robust.Client/GameObjects/EntitySystems/GridRenderingSystem.cs
  Robust.Client/GameObjects/EntitySystems/RenderingTreeSystem.cs
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.Windows.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.cs
  Robust.Client/Placement/Modes/AlignSnapgridBorder.cs
  Robust.Client/Placement/Modes/AlignSnapgridCenter.cs
  Robust.Client/Placement/Modes/AlignTileAny.cs
  Robust.Client/Placement/Modes/AlignTileDense.cs
  Robust.Client/Placement/Modes/AlignTileEmpty.cs
  Robust.Client/Placement/Modes/AlignTileNonDense.cs
  Robust.Client/Placement/PlacementManager.cs
  Robust.Client/Placement/PlacementMode.cs
  Robust.Client/UserInterface/CustomControls/DebugCoordsPanel.cs
  Robust.Client/ViewVariables/Editors/VVPropEditorEntityCoordinates.cs
  Robust.Server/Bql/BqlQuerySelector.Builtin.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/GameObjects/EntitySystems/MapSystem.cs
  Robust.Server/GameStates/PVSCollection.cs
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Server/Physics/GridFixtureSystem.cs
  Robust.Shared/GameObjects/Components/Map/MapGridComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Systems/EntityLookup.Queries.cs
  Robust.Shared/GameObjects/Systems/SharedMapSystem.cs
  Robust.Shared/Map/CoordinatesExtensions.cs
  Robust.Shared/Map/EntityCoordinates.cs
  Robust.Shared/Map/GridEnumerator.cs
  Robust.Shared/Map/GridEventHandler.cs
  Robust.Shared/Map/GridId.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/IMapManager.cs
  Robust.Shared/Map/IMapManagerInternal.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapManager.GridCollection.cs
  Robust.Shared/Map/MapManager.MapCollection.cs
  Robust.Shared/Map/MapManager.Pause.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Map/NetworkedMapManager.cs
  Robust.Shared/Map/TileRef.cs
  Robust.Shared/Prototypes/PrototypeManager.cs
  Robust.UnitTesting/Server/GameObjects/Components/Transform_Test.cs
  Robust.UnitTesting/Shared/EntityLookup_Test.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
  Robust.UnitTesting/Shared/Map/EntityCoordinates_Tests.cs
  Robust.UnitTesting/Shared/Map/GridSplit_Tests.cs
  Robust.UnitTesting/Shared/Map/MapGrid_Tests.cs
  Robust.UnitTesting/Shared/Map/MapManager_Tests.cs
Labels: Status: Requires Content PR

#3313 Unrevert "Remove obsolete GridId and all references to it" (#3279)
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/Debugging/DebugAnchoringSystem.cs
  Robust.Client/GameObjects/Components/Light/ClientOccluderComponent.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/GameObjects/EntitySystems/ClientOccluderSystem.cs
  Robust.Client/GameObjects/EntitySystems/EffectSystem.cs
  Robust.Client/GameObjects/EntitySystems/GridRenderingSystem.cs
  Robust.Client/GameObjects/EntitySystems/RenderingTreeSystem.cs
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.Windows.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.cs
  Robust.Client/Placement/Modes/AlignSnapgridBorder.cs
  Robust.Client/Placement/Modes/AlignSnapgridCenter.cs
  Robust.Client/Placement/Modes/AlignTileAny.cs
  Robust.Client/Placement/Modes/AlignTileDense.cs
  Robust.Client/Placement/Modes/AlignTileEmpty.cs
  Robust.Client/Placement/Modes/AlignTileNonDense.cs
  Robust.Client/Placement/PlacementManager.cs
  Robust.Client/Placement/PlacementMode.cs
  Robust.Client/UserInterface/CustomControls/DebugCoordsPanel.cs
  Robust.Client/ViewVariables/Editors/VVPropEditorEntityCoordinates.cs
  Robust.Server/Bql/BqlQuerySelector.Builtin.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/GameObjects/EntitySystems/MapSystem.cs
  Robust.Server/GameStates/PVSCollection.cs
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Server/Maps/GridSerializer.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Server/Physics/GridFixtureSystem.cs
  Robust.Shared/GameObjects/Components/Map/MapGridComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Systems/EntityLookup.Queries.cs
  Robust.Shared/GameObjects/Systems/SharedMapSystem.cs
  Robust.Shared/Map/CoordinatesExtensions.cs
  Robust.Shared/Map/EntityCoordinates.cs
  Robust.Shared/Map/GridEnumerator.cs
  Robust.Shared/Map/GridEventHandler.cs
  Robust.Shared/Map/GridId.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/IMapManager.cs
  Robust.Shared/Map/IMapManagerInternal.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapManager.GridCollection.cs
  Robust.Shared/Map/MapManager.MapCollection.cs
  Robust.Shared/Map/MapManager.Pause.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Map/NetworkedMapManager.cs
  Robust.Shared/Map/TileRef.cs
  Robust.Shared/Prototypes/PrototypeManager.cs
  Robust.UnitTesting/Server/GameObjects/Components/Transform_Test.cs
  Robust.UnitTesting/Shared/EntityLookup_Test.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
  Robust.UnitTesting/Shared/Map/EntityCoordinates_Tests.cs
  Robust.UnitTesting/Shared/Map/GridSplit_Tests.cs
  Robust.UnitTesting/Shared/Map/MapGrid_Tests.cs
  Robust.UnitTesting/Shared/Map/MapManager_Tests.cs
Labels: Status: Requires Content PR

#3340 Fix obsolete warnings in tests
  Robust.UnitTesting/Shared/GameObjects/ContainerTests.cs
  Robust.UnitTesting/Shared/GameObjects/Systems/AnchoredSystemTests.cs
  Robust.UnitTesting/Shared/Map/GridCollision_Test.cs
  Robust.UnitTesting/Shared/Map/GridFixtures_Tests.cs
  Robust.UnitTesting/Shared/Physics/Broadphase_Test.cs
  Robust.UnitTesting/Shared/Physics/Fixtures_Test.cs
  Robust.UnitTesting/Shared/Physics/GridDeletion_Test.cs
  Robust.UnitTesting/Shared/Physics/GridMovement_Test.cs
  Robust.UnitTesting/Shared/Physics/JointDeletion_Test.cs
  Robust.UnitTesting/Shared/Physics/Joints_Test.cs
  Robust.UnitTesting/Shared/Physics/MapVelocity_Test.cs
  Robust.UnitTesting/Shared/Physics/PhysicsComponent_Test.cs
  Robust.UnitTesting/Shared/Physics/PhysicsMap_Test.cs
  Robust.UnitTesting/Shared/Physics/Stack_Test.cs
Labels: Size: Very Small, Difficulty: 1-Easy

#3407 Cache broadphases and container rejig
  Robust.Client/GameObjects/EntitySystems/ContainerSystem.cs
  Robust.Client/GameObjects/EntitySystems/MapSystem.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/Physics/PhysicsSystem.cs
  Robust.Server/Containers/ContainerSystem.cs
  Robust.Server/GameObjects/EntitySystems/MapSystem.cs
  Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Shared/Containers/BaseContainer.cs
  Robust.Shared/Containers/Container.cs
  Robust.Shared/Containers/ContainerManagerComponent.cs
  Robust.Shared/Containers/ContainerSlot.cs
  Robust.Shared/Containers/IContainer.cs
  Robust.Shared/Containers/IContainerManager.cs
  Robust.Shared/Containers/SharedContainerSystem.Validation.cs
  Robust.Shared/Containers/SharedContainerSystem.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Systems/CollideOnAnchorSystem.cs
  Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs
  Robust.Shared/GameObjects/Systems/SharedMapSystem.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs
  Robust.Shared/Map/MapManager.MapCollection.cs
  Robust.Shared/Physics/Dynamics/ContactManager.cs
  Robust.Shared/Physics/Events/CollisionChangeEvent.cs
  Robust.Shared/Physics/Systems/FixtureSystem.cs
  Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs
  Robust.Shared/Physics/Systems/SharedPhysicsSystem.Queries.cs
  Robust.Shared/Physics/Systems/SharedPhysicsSystem.cs
  Robust.UnitTesting/Server/GameObjects/Components/Container_Test.cs
  Robust.UnitTesting/Shared/Map/MapManager_Tests.cs
  Robust.UnitTesting/Shared/Physics/Broadphase_Test.cs
  Robust.UnitTesting/Shared/Prototypes/HotReloadTest.cs
Labels: Issue: Bug, Area: Physics, Status: Requires Content PR
