Repository space-wizards/RobustToolbox, pull requests merged in 2022-07, with the labels that each got.

#2973 Add enum and custom hash set serializers
  Robust.Shared/Reflection/IReflectionManager.cs
  Robust.Shared/Reflection/ReflectionManager.cs
  Robust.Shared/Serialization/Manager/ISerializationManager.cs
  Robust.Shared/Serialization/Manager/SerializationManager.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/Custom/AppearanceKeySerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/Generic/CustomHashSetSerializer.cs
Labels: Area: Serialization

#3008 Make recursive delete detach parents before children
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.Components.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.Velocities.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs
  Robust.Shared/Map/MapManager.GridTrees.cs
  Robust.Shared/Physics/FixtureSystem.cs
  Robust.Shared/Physics/SharedBroadphaseSystem.cs
  Robust.Shared/Physics/SharedJointSystem.cs
Labels: Status: Needs Review

#2974 Misc Shader changes
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/GameObjects/EntitySystems/SpriteSystem.cs
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Client/Graphics/Clyde/Clyde.Helpers.cs
  Robust.Client/Graphics/Clyde/Clyde.RenderHandle.cs
  Robust.Client/Graphics/Clyde/Clyde.Rendering.cs
  Robust.Client/Graphics/Clyde/Clyde.Shaders.cs
  Robust.Client/Graphics/Clyde/Clyde.cs
Labels: Area: Rendering, Status: Requires Content PR

#2776 Audio occlusion parallelization
  Robust.Client/Debugging/DebugRayDrawingSystem.cs
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Server/BaseServer.cs
  Robust.Server/Debugging/DebugDrawingManager.cs
  Robust.Server/Debugging/DebugRayDrawingSystem.cs
  Robust.Server/Debugging/IDebugDrawingManager.cs
  Robust.Server/ServerIoC.cs
  Robust.Shared/Debugging/SharedDebugRayDrawingSystem.cs
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.Queries.cs
  Robust.Shared/Physics/DebugDrawRayMessage.cs
  Robust.Shared/Physics/DebugRayData.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
Labels: Status: Needs Review

#3015 MIDI refactor part 1: MidiRendererState
  Robust.Client/Audio/Midi/IMidiRenderer.cs
  Robust.Client/Audio/Midi/MidiManager.cs
  Robust.Client/Audio/Midi/MidiRenderer.cs
  Robust.Client/Audio/Midi/MidiRendererState.cs
  Robust.Shared/Audio/Midi/RobustMidiEvent.cs
Labels: Area: Audio

#3073 More window open overrides
  Robust.Client/UserInterface/CustomControls/BaseWindow.cs
Labels: Area: UI

#3075 Validate sprite specifier states
  Robust.Client/Serialization/ClientSpriteSpecifierSerializer.cs
  Robust.Server/Serialization/ServerSpriteSpecifierSerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
Labels: Area: Serialization, Status: Requires Content PR

#3038 AudioSystem Rejig
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Server/GameObjects/EntitySystems/AudioSystem.cs
  Robust.Shared/Audio/AudioParams.cs
  Robust.Shared/Audio/IAudioSystem.cs
  Robust.Shared/Audio/SoundCollectionPrototype.cs
  Robust.Shared/Audio/SoundSpecifier.cs
  Robust.Shared/Audio/SoundSpecifierTypeSerializer.cs
  Robust.Shared/Audio/SoundSystem.cs
  Robust.Shared/GameObjects/Systems/SharedAudioSystem.cs
Labels: Status: Requires Content PR, Area: Audio

#3068 Joint changes
  Robust.Client/Physics/JointSystem.cs
  Robust.Shared/Physics/Dynamics/Joints/DistanceJoint.cs
  Robust.Shared/Physics/Dynamics/Joints/FrictionJoint.cs
  Robust.Shared/Physics/Dynamics/Joints/Joint.cs
  Robust.Shared/Physics/Dynamics/Joints/MouseJoint.cs
  Robust.Shared/Physics/Dynamics/Joints/PrismaticJoint.cs
  Robust.Shared/Physics/Dynamics/Joints/RevoluteJoint.cs
  Robust.Shared/Physics/Dynamics/Joints/WeldJoint.cs
  Robust.Shared/Physics/Dynamics/PhysicsIsland.cs
  Robust.Shared/Physics/Dynamics/SharedPhysicsMapComponent.cs
  Robust.Shared/Physics/JointComponent.cs
  Robust.Shared/Physics/SharedJointSystem.cs
Labels: Status: Requires Content PR

#3018 Toggle button updates
  Robust.Client/UserInterface/Controls/BaseButton.cs
  Robust.UnitTesting/Client/UserInterface/Controls/BaseButtonTest.cs
Labels: Area: UI

#3072 Adds a check to HandleContainerRemoved to handle different canCollide states.
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.cs
Labels: Status: Awaiting Changes
