Repository space-wizards/RobustToolbox, pull requests merged in 2022-02, with the labels that each got.

#2491 remove GetBus()
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/EntityManager.cs
Labels: Type: Performance

#2430 Move MapGrid data from MapManager to MapGridComponent
  Robust.Client/ClientIoC.cs
  Robust.Client/GameObjects/EntitySystems/ClientOccluderSystem.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Map/ClientMapManager.cs
  Robust.Client/Map/IClientMapManager.cs
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Server/Map/IServerMapManager.cs
  Robust.Server/Map/ServerMapManager.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Server/Maps/YamlGridSerializer.cs
  Robust.Server/ServerIoC.cs
  Robust.Shared/GameObjects/Components/Map/MapGridComponent.cs
  Robust.Shared/GameObjects/Systems/SharedMapSystem.cs
  Robust.Shared/Map/FindGridsEnumerator.cs
  Robust.Shared/Map/GridEventHandler.cs
  Robust.Shared/Map/IMapGrid.cs
  Robust.Shared/Map/IMapManager.cs
  Robust.Shared/Map/IMapManagerInternal.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapManager.GridCollection.cs
  Robust.Shared/Map/MapManager.GridTrees.cs
  Robust.Shared/Map/MapManager.MapCollection.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/Map/NetworkedMapManager.cs
Labels: Type: Cleanup, Type: Performance, Area: ECS

#2495 Replace `EntityDirtyEvent` with C# event.
  Robust.Server/GameStates/PVSSystem.Dirty.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EntityDirtyEvent.cs
  Robust.Shared/GameObjects/IEntityManager.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.cs
  Robust.Shared/Map/IMapChunkInternal.cs
  Robust.Shared/Map/IMapGridInternal.cs
  Robust.Shared/Map/MapGrid.cs
Labels: Type: Performance

#2522 Abstract VisualizerSystem
  Robust.Client/GameObjects/EntitySystems/AppearanceSystem.cs
  Robust.Client/GameObjects/EntitySystems/VisualizerSystem.cs
Labels: Status: Requires Content PR, Area: ECS

#2464 Hopefully fix container occlusion bug?
  Robust.Client/GameObjects/EntitySystems/ContainerSystem.cs
  Robust.Shared/Containers/SharedContainerSystem.cs
Labels: Type: Bug

#2520 Map Pausing Fixes
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/Console/Commands/TestbedCommand.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Shared/GameObjects/Components/IgnorePauseComponent.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/Map/GridId.cs
  Robust.Shared/Map/IMapManager.cs
  Robust.Shared/Map/MapManager.Pause.cs
  Robust.Shared/Map/MapManager.cs
  Robust.Shared/SharedIoC.cs
  Robust.Shared/Timing/IPauseManager.cs
  Robust.UnitTesting/Server/RobustServerSimulation.cs
  Robust.UnitTesting/Shared/Map/MapGrid_Tests.cs
  Robust.UnitTesting/Shared/Map/MapPauseTests.cs
Labels: Type: Bug, Type: Cleanup, Project: Server, Area: ECS

#2534 Draw effects below FOV
  Robust.Client/GameObjects/EntitySystems/EffectSystem.cs
Labels: Type: Discussion, Size: Very Small

#2511 Fix InteractionOutline 2: Electric boogaloo
  Robust.Client/GameObjects/Components/Renderable/ISpriteComponent.cs
  Robust.Client/GameObjects/Components/Renderable/ISpriteLayer.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteBoundsOverlay.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/GameObjects/EntitySystems/RenderingTreeSystem.cs
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Client/Graphics/Clyde/Clyde.Rendering.cs
Labels: Area: Rendering

#2442 Allow sprite layer data to be set using `PrototypeLayerData`.
  Robust.Client/GameObjects/Components/Renderable/ISpriteComponent.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Shared/GameObjects/Components/Renderable/SharedSpriteComponent.cs
Labels: Type: Feature

#2460 Hopefully fix appearance component mispredict reconciliation
  Robust.Client/GameObjects/EntitySystems/AppearanceSystem.cs
  Robust.Shared/GameObjects/Components/Appearance/AppearanceComponent.cs
Labels: Type: Bug

#2538 Adds command buffer to client, and input command injection
  Robust.Client/Console/ClientConsoleHost.cs
  Robust.Client/GameController/GameController.cs
  Robust.Client/GameObjects/EntitySystems/InputSystem.cs
  Robust.Server/BaseServer.cs
  Robust.Shared/Console/CommandBuffer.cs
  Robust.Shared/Console/Commands/ExecCommand.cs
  Robust.Shared/Console/ConsoleHost.cs
  Robust.Shared/Console/IConsoleHost.cs
Labels: Type: Feature

#2543 Move Map Pause data from MapManager to MapComponent.
  Robust.Shared/GameObjects/Components/Map/MapComponent.cs
  Robust.Shared/Map/MapManager.Pause.cs
  Robust.UnitTesting/Shared/Map/MapManager_Tests.cs
  Robust.UnitTesting/Shared/Map/MapPauseTests.cs
Labels: Type: Cleanup

#2555 MapChunk Cleanup
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/Graphics/Clyde/Clyde.GridRendering.cs
  Robust.Client/Map/ClydeTileDefinitionManager.cs
  Robust.Client/Map/IClydeTileDefinitionManager.cs
  Robust.Server/Maps/YamlGridSerializer.cs
  Robust.Shared.Maths/Box2i.cs
  Robust.Shared/GameObjects/Systems/SharedGridFixtureSystem.cs
  Robust.Shared/Map/GridChunkPartition.cs
  Robust.Shared/Map/IMapChunk.cs
  Robust.Shared/Map/IMapChunkInternal.cs
  Robust.Shared/Map/IMapGridInternal.cs
  Robust.Shared/Map/IMapManagerInternal.cs
  Robust.Shared/Map/MapChunk.cs
  Robust.Shared/Map/MapGrid.cs
  Robust.Shared/Map/MapManager.GridCollection.cs
  Robust.Shared/Map/MapManager.Queries.cs
  Robust.Shared/Map/NetworkedMapManager.cs
  Robust.Shared/Physics/Collision/Shapes/EdgeShape.cs
  Robust.Shared/Physics/Collision/Shapes/IPhysShape.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeAabb.cs
  Robust.Shared/Physics/Collision/Shapes/PhysShapeCircle.cs
  Robust.Shared/Physics/Collision/Shapes/PolygonShape.cs
  Robust.UnitTesting/Shared/Map/GridChunkPartition_Tests.cs
  Robust.UnitTesting/Shared/Map/GridRotation_Tests.cs
  Robust.UnitTesting/Shared/Map/MapChunk_Tests.cs
Labels: Type: Cleanup

#2565 Allow SpriteSpecifier to deserialize with entity prototype ids.
  Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
Labels: Size: Very Small

#2572 loadmap command tweak
  Robust.Server/Console/Commands/MapCommands.cs
Labels: Size: Very Small
