Repository space-wizards/RobustToolbox, pull requests merged in 2022-09, with the labels that each got.

#3208 Make AudioSystem.PlayingStream public
  Robust.Client/GameObjects/EntitySystems/AudioSystem.cs
Labels: Size: Very Small, Area: Audio

#2876 Predict component adding and removal
  Robust.Client/GameStates/ClientDirtySystem.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/IEntityManager.Components.cs
Labels: Area: Networking, Status: Needs Review

#2712 UI refactor and UITheme implementations
  Resources/EnginePrototypes/UserInterface/uiThemes.yml
  Robust.Client/ClientIoC.cs
  Robust.Client/GameController/GameController.cs
  Robust.Client/Player/LocalPlayer.cs
  Robust.Client/Player/PlayerManager.cs
  Robust.Client/State/DefaultState.cs
  Robust.Client/State/State.cs
  Robust.Client/State/StateManager.cs
  Robust.Client/UserInterface/Control.cs
  Robust.Client/UserInterface/Controllers/IOnStateChanged.cs
  Robust.Client/UserInterface/Controllers/IOnStateEntered.cs
  Robust.Client/UserInterface/Controllers/IOnStateExited.cs
  Robust.Client/UserInterface/Controllers/IOnSystemChanged.cs
  Robust.Client/UserInterface/Controllers/IOnSystemLoaded.cs
  Robust.Client/UserInterface/Controllers/IOnSystemUnloaded.cs
  Robust.Client/UserInterface/Controllers/IUserInterfaceManager.Controllers.cs
  Robust.Client/UserInterface/Controllers/Implementations/EntitySpawningUIController.cs
  Robust.Client/UserInterface/Controllers/Implementations/TileSpawningUIController.cs
  Robust.Client/UserInterface/Controllers/UIController.cs
  Robust.Client/UserInterface/Controllers/UserInterfaceManager.Controllers.cs
  Robust.Client/UserInterface/Controls/Popup.cs
  Robust.Client/UserInterface/Controls/ScrollContainer.cs
  Robust.Client/UserInterface/Controls/SpriteView.cs
  Robust.Client/UserInterface/Controls/TextureButton.cs
  Robust.Client/UserInterface/Controls/TextureRect.cs
  Robust.Client/UserInterface/Controls/UIWidget.cs
  Robust.Client/UserInterface/Controls/WindowRoot.cs
  Robust.Client/UserInterface/CustomControls/BaseWindow.cs
  Robust.Client/UserInterface/CustomControls/DoNotMeasure.cs
  Robust.Client/UserInterface/CustomControls/EntitySpawnButton.cs
  Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.cs
  Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.xaml
  Robust.Client/UserInterface/CustomControls/EntitySpawnWindow.xaml.cs
  Robust.Client/UserInterface/CustomControls/PrototypeListContainer.cs
  Robust.Client/UserInterface/CustomControls/TileSpawnWindow.cs
  Robust.Client/UserInterface/CustomControls/TileSpawnWindow.xaml
  Robust.Client/UserInterface/CustomControls/TileSpawnWindow.xaml.cs
  Robust.Client/UserInterface/IUserInterfaceManager.Screens.cs
  Robust.Client/UserInterface/IUserInterfaceManager.Themes.cs
  Robust.Client/UserInterface/IUserInterfaceManager.Windows.cs
  Robust.Client/UserInterface/IUserInterfaceManager.cs
  Robust.Client/UserInterface/InterfaceThemeLegacy.cs
  Robust.Client/UserInterface/Themes/UiTheme.cs
  Robust.Client/UserInterface/UIScreen.cs
  Robust.Client/UserInterface/UISystemDependencyAttribute.cs
  Robust.Client/UserInterface/UserInterfaceManager.Input.cs
  Robust.Client/UserInterface/UserInterfaceManager.Layout.cs
  Robust.Client/UserInterface/UserInterfaceManager.Scaling.cs
  Robust.Client/UserInterface/UserInterfaceManager.Themes.cs
  Robust.Client/UserInterface/UserInterfaceManager.UIScreens.cs
  Robust.Client/UserInterface/UserInterfaceManager.Windows.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
  Robust.Client/UserInterface/XAML/UiTextureExtension.cs
  Robust.Server/Prototypes/ServerPrototypeManager.cs
  Robust.Shared/CVars.cs
  Robust.Shared/Serialization/Manager/Definition/DataDefinition.Delegates.cs
  Robust.Shared/Serialization/Manager/Definition/DataDefinition.Emitters.cs
  Robust.Shared/Serialization/Manager/Definition/DataDefinition.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/ResourcePathSerializer.cs
Labels: Area: UI, Status: Awaiting Content Changes

#3206 Fix construction ghost rotation on entities without directional sprites
  Robust.Client/Placement/PlacementManager.cs
Labels: Size: Very Small

#3241 Fix non-map or grid coordinate returns for most cases
  Robust.Shared/Map/CoordinatesExtensions.cs
Labels: Issue: Bug

#3220 Pass IRobustSerializer to NetMessage
  Robust.Shared/Network/Messages/Handshake/MsgEncryptionRequest.cs
  Robust.Shared/Network/Messages/Handshake/MsgEncryptionResponse.cs
  Robust.Shared/Network/Messages/Handshake/MsgLoginStart.cs
  Robust.Shared/Network/Messages/Handshake/MsgLoginSuccess.cs
  Robust.Shared/Network/Messages/MsgConCmd.cs
  Robust.Shared/Network/Messages/MsgConCmdAck.cs
  Robust.Shared/Network/Messages/MsgConCmdReg.cs
  Robust.Shared/Network/Messages/MsgConCompletion.cs
  Robust.Shared/Network/Messages/MsgConCompletionResp.cs
  Robust.Shared/Network/Messages/MsgConVars.cs
  Robust.Shared/Network/Messages/MsgEntity.cs
  Robust.Shared/Network/Messages/MsgMapStrClientHandshake.cs
  Robust.Shared/Network/Messages/MsgMapStrServerHandshake.cs
  Robust.Shared/Network/Messages/MsgMapStrStrings.cs
  Robust.Shared/Network/Messages/MsgPlacement.cs
  Robust.Shared/Network/Messages/MsgPlayerList.cs
  Robust.Shared/Network/Messages/MsgPlayerListReq.cs
  Robust.Shared/Network/Messages/MsgReloadPrototypes.cs
  Robust.Shared/Network/Messages/MsgScriptCompletion.cs
  Robust.Shared/Network/Messages/MsgScriptCompletionResponse.cs
  Robust.Shared/Network/Messages/MsgScriptEval.cs
  Robust.Shared/Network/Messages/MsgScriptResponse.cs
  Robust.Shared/Network/Messages/MsgScriptStart.cs
  Robust.Shared/Network/Messages/MsgScriptStartAck.cs
  Robust.Shared/Network/Messages/MsgScriptStop.cs
  Robust.Shared/Network/Messages/MsgState.cs
  Robust.Shared/Network/Messages/MsgStateAck.cs
  Robust.Shared/Network/Messages/MsgStateLeavePvs.cs
  Robust.Shared/Network/Messages/MsgStateRequestFull.cs
  Robust.Shared/Network/Messages/MsgSyncTimeBase.cs
  Robust.Shared/Network/Messages/MsgViewVariablesCloseSession.cs
  Robust.Shared/Network/Messages/MsgViewVariablesDenySession.cs
  Robust.Shared/Network/Messages/MsgViewVariablesModifyRemote.cs
  Robust.Shared/Network/Messages/MsgViewVariablesOpenSession.cs
  Robust.Shared/Network/Messages/MsgViewVariablesRemoteData.cs
  Robust.Shared/Network/Messages/MsgViewVariablesReqData.cs
  Robust.Shared/Network/Messages/MsgViewVariablesReqSession.cs
  Robust.Shared/Network/NetManager.ClientConnect.cs
  Robust.Shared/Network/NetManager.ServerAuth.cs
  Robust.Shared/Network/NetManager.cs
  Robust.Shared/Network/NetMessage.cs
  Robust.Shared/Network/StringTable.cs
Labels: Area: Networking, Status: Requires Content PR

#3249 Session specific state support
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Server/GameObjects/EntitySystems/ServerMetaDataSystem.cs
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/IEntityManager.Components.cs
  Robust.Shared/GameStates/ComponentStateEvents.cs
Labels: Status: Requires Content PR

#3016 Robust.Packaging system
  Robust.Client/ResourceManagement/ResourceTypes/RSIResource.cs
  Robust.Client/Utility/ImageSharpExt.cs
  Robust.Packaging/AssetProcessing/AssetFiles.cs
  Robust.Packaging/AssetProcessing/AssetGraph.cs
  Robust.Packaging/AssetProcessing/AssetPass.cs
  Robust.Packaging/AssetProcessing/Passes/AssetPassNormalizeText.cs
  Robust.Packaging/AssetProcessing/Passes/AssetPassPackRsis.cs
  Robust.Packaging/AssetProcessing/Passes/AssetPassPipe.cs
  Robust.Packaging/AssetProcessing/Passes/AssetPassZipWriter.cs
  Robust.Packaging/IPackageLogger.cs
  Robust.Packaging/PackageLoggerConsole.cs
  Robust.Packaging/PackageLoggerSawmill.cs
  Robust.Packaging/Program.cs
  Robust.Packaging/Robust.Packaging.csproj
  Robust.Packaging/RobustClientAssetGraph.cs
  Robust.Packaging/RobustClientPackaging.cs
  Robust.Packaging/RobustSharedPackaging.cs
  Robust.Packaging/Utility/ProcessHelpers.cs
  Robust.Server/Robust.Server.csproj
  Robust.Server/ServerStatus/DefaultMagicAczProvider.cs
  Robust.Server/ServerStatus/IMagicAczProvider.cs
  Robust.Server/ServerStatus/IStatusHost.cs
  Robust.Server/ServerStatus/StatusHost.Acz.Sources.cs
  Robust.Server/ServerStatus/StatusHost.Acz.cs
  Robust.Server/ServerStatus/StatusHost.cs
  Robust.Shared/Log/ConsoleLogHandler.cs
  Robust.Shared/Properties/AssemblyInfo.cs
  Robust.Shared/Resources/RsiLoading.cs
  Robust.Shared/Robust.Shared.csproj
  Robust.Shared/Utility/ImageOps.cs
  Robust.Shared/Utility/SequenceMemoryStream.cs
  Tools/download_manifest_file.py
Labels: Status: Stale

#3019 Allow Content to use InitializeTesting
  Robust.Client/UserInterface/IUserInterfaceManager.cs
  Robust.Client/UserInterface/IUserInterfaceManagerInternal.cs
Labels: Area: UI

#3264 Add get-matrix functions to IViewportControl
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Client/Graphics/Clyde/Clyde.Viewport.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Graphics/IClydeViewport.cs
  Robust.Client/UserInterface/CustomControls/IViewportControl.cs
  Robust.Client/UserInterface/CustomControls/ViewportContainer.cs
Labels: Status: Requires Content PR

#3270 Remove RotateEvent
  Robust.Client/GameObjects/EntitySystems/TransformSystem.Component.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs
  Robust.Shared/Map/MapManager.GridTrees.cs
  Robust.Shared/Physics/Dynamics/PhysicsIsland.cs
  Robust.Shared/Physics/Systems/SharedBroadphaseSystem.cs
Labels: Area: Physics, Status: Requires Content PR
