Repository space-wizards/RobustToolbox, pull requests merged in 2022-08, with the labels that each got.

#3104 More BUI changes
  Robust.Client/GameObjects/Components/UserInterface/ClientUserInterfaceComponent.cs
  Robust.Client/GameObjects/EntitySystems/UserInterfaceSystem.cs
  Robust.Server/GameObjects/Components/UserInterface/ServerUserInterfaceComponent.cs
  Robust.Server/GameObjects/EntitySystems/UserInterfaceSystem.cs
  Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/EnumSerializer.cs
Labels: Area: UI, Status: Requires Content PR

#3000 PVS & client state handling changes
  Robust.Client/GameController/GameController.Standalone.cs
  Robust.Client/GameController/GameController.cs
  Robust.Client/GameObjects/ClientEntityManager.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/GameObjects/EntitySystems/AppearanceSystem.cs
  Robust.Client/GameStates/ClientDirtySystem.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/GameStates/GameStateProcessor.cs
  Robust.Client/GameStates/IClientGameStateManager.cs
  Robust.Client/GameStates/IGameStateProcessor.cs
  Robust.Client/GameStates/NetEntityOverlay.cs
  Robust.Client/GameStates/NetGraphOverlay.cs
  Robust.Client/Graphics/Overlays/IOverlayManager.cs
  Robust.Client/Timing/ClientGameTiming.cs
  Robust.Client/Timing/IClientGameTiming.cs
  Robust.Client/UserInterface/CustomControls/DebugMonitors.cs
  Robust.Client/UserInterface/CustomControls/DebugTimePanel.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
  Robust.Server/BaseServer.cs
  Robust.Server/GameStates/IServerGameStateManager.cs
  Robust.Server/GameStates/PVSEntityVisiblity.cs
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Server/GameStates/ServerGameStateManager.cs
  Robust.Shared/CVars.cs
  Robust.Shared/Collections/OverflowDictionary.cs
  Robust.Shared/Configuration/NetConfigurationManager.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/EntityState.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs
  Robust.Shared/GameStates/GameState.cs
  Robust.Shared/Network/Messages/MsgState.cs
  Robust.Shared/Network/Messages/MsgStateLeavePvs.cs
  Robust.Shared/Network/Messages/MsgStateRequestFull.cs
  Robust.Shared/Physics/FixtureSystem.cs
  Robust.Shared/Timing/GameLoop.cs
  Robust.Shared/Timing/GameTiming.cs
  Robust.Shared/Timing/IGameTiming.cs
  Robust.UnitTesting/Client/GameStates/GameStateProcessor_Tests.cs
  Robust.UnitTesting/RobustIntegrationTest.NetManager.cs
  Robust.UnitTesting/Shared/GameObjects/EntityState_Tests.cs
Labels: Area: Networking, Status: Requires Content PR

#3139 Un-revert BUI PRs
  Robust.Client/GameObjects/Components/UserInterface/ClientUserInterfaceComponent.cs
  Robust.Client/GameObjects/EntitySystems/UserInterfaceSystem.cs
  Robust.Server/GameObjects/Components/UserInterface/ServerUserInterfaceComponent.cs
  Robust.Server/GameObjects/EntitySystems/UserInterfaceSystem.cs
  Robust.Shared/GameObjects/Components/UserInterface/SharedUserInterfaceComponent.cs
Labels: Area: UI, Status: Requires Content PR

#3165 Map serialization postmapinit bugfix
  Robust.Server/Maps/MapLoader.cs
  Robust.Shared/GameObjects/Components/Map/MapComponent.cs
  Robust.UnitTesting/Shared/GameObjects/ContainerTests.cs
Labels: Area: Serialization

#3174 Hopefully fix container issues?
  Robust.Client/GameObjects/EntitySystems/ContainerSystem.cs
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Shared/Containers/BaseContainer.cs
  Robust.Shared/Containers/Container.cs
  Robust.Shared/Containers/ContainerManagerComponent.cs
  Robust.Shared/GameObjects/Components/MetaDataComponent.cs
Labels: Status: Requires Content PR

#3181 Fix load grid errors
  Robust.Client/Player/LocalPlayer.cs
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/Maps/IMapLoader.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Shared/GameObjects/Components/Map/MapGridComponent.cs
  Robust.Shared/Map/MapManager.MapCollection.cs
  Robust.UnitTesting/Server/Maps/MapLoaderTest.cs
Labels: Status: Requires Content PR

#3183 Physics get-colliding tweaks
  Robust.Shared/GameObjects/Systems/SharedPhysicsSystem.Queries.cs
Labels: Area: Physics, Status: Requires Content PR

#3191 Fix AudioParams deserialization
  Robust.Shared/Audio/AudioParams.cs
  Robust.Shared/Containers/ContainerManagerComponent.cs
Labels: Area: Serialization

#3082 YamlDotNet update
  Robust.Shared/Robust.Shared.csproj
  Robust.Shared/Serialization/Markdown/Mapping/MappingDataNode.cs
  Robust.Shared/Serialization/Markdown/Sequence/SequenceDataNode.cs
  Robust.Shared/Serialization/Markdown/Value/ValueDataNode.cs
  Robust.Shared/Serialization/RobustMappedStringSerializer.MappedStringDict.cs
Labels: Area: Serialization

#3182 Fixes MIDI bank selection not working.
  Robust.Client/Audio/Midi/MidiManager.cs
  Robust.Client/Audio/Midi/MidiRenderer.cs
Labels: Area: Audio
