Repository space-wizards/RobustToolbox, pull requests merged in 2022-05, with the labels that each got.

#2874 Change SplitContainer.MeasureOverride()
  Robust.Client/UserInterface/Controls/SplitContainer.cs
Labels: Area: UI

#2858 Sync CurTime base.
  Robust.Client/BaseClient.cs
  Robust.Server/BaseServer.cs
  Robust.Server/Player/PlayerManager.cs
  Robust.Shared/CVars.cs
  Robust.Shared/Collections/InvokeList.cs
  Robust.Shared/Configuration/ConfigurationManager.cs
  Robust.Shared/Configuration/IConfigurationManager.cs
  Robust.Shared/Configuration/NetConfigurationManager.cs
  Robust.Shared/Network/Messages/MsgSyncTimeBase.cs
  Robust.Shared/Timing/GameTiming.cs
  Robust.Shared/Timing/IGameTiming.cs
  Robust.Shared/Utility/TimeSpanExt.cs
  Robust.UnitTesting/Shared/Configuration/ConfigurationManagerTest.cs
  Robust.UnitTesting/Shared/GameObjects/EntitySystemManagerOrderTest.cs
Labels: Issue: Bug, Priority: 2-Important, Area: Networking

#2878 Fix WorldSpace overlay drawing
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Shared/Enums/OverlaySpaces.cs
Labels: Area: Rendering

#2860 Minor performance improvements
  Robust.Benchmarks/EntityManager/ComponentIndexBenchmark.cs
  Robust.Client/GameStates/ClientDirtySystem.cs
  Robust.Server/GameObjects/EntitySystems/VisibilitySystem.cs
  Robust.Server/GameObjects/ServerEntityManager.cs
  Robust.Server/GameStates/PVSSystem.Dirty.cs
  Robust.Server/GameStates/PVSSystem.cs
  Robust.Shared/GameObjects/CompIdx.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/GameObjects/ComponentEventArgs.cs
  Robust.Shared/GameObjects/ComponentFactory.cs
  Robust.Shared/GameObjects/ComponentRegistration.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/EntitySystemMessages/EntityInitializedMessage.cs
  Robust.Shared/GameObjects/IComponentFactory.cs
  Robust.Shared/GameObjects/IEntityManager.Components.cs
  Robust.Shared/GameObjects/IEntityManager.cs
  Robust.Shared/GameObjects/Systems/EntityLookupSystem.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/ComponentRegistrySerializer.cs
  Robust.Shared/Utility/IUniqueIndex.cs
  Robust.Shared/Utility/UniqueIndex.cs
  Robust.Shared/Utility/UniqueIndexHkm.cs
  Robust.UnitTesting/RobustUnitTest.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.ComponentEvent.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.SystemEvent.cs
Labels: Issue: Performance

#2882 Re-use PostShader render target
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
Labels: Area: Rendering
