Repository space-wizards/RobustToolbox, pull requests merged in 2022-06, with the labels that each got.

#2896 Remove allocations from physics ComputeDistance()
  Robust.Shared/Physics/Collision/DistanceInput.cs
  Robust.Shared/Physics/Collision/DistanceManager.cs
  Robust.Shared/Physics/Collision/DistanceProxy.cs
  Robust.Shared/Utility/FixedArray.cs
Labels: Issue: Performance

#2905 Make TryGetComponent output nullable
  Robust.Server/Console/Commands/PlayerCommands.cs
  Robust.Server/Console/Commands/SpinCommand.cs
  Robust.Server/GameObjects/EntitySystems/ActorSystem.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/IEntityManager.Components.cs
  Robust.Shared/Map/MapManager.GridCollection.cs
  Robust.Shared/Physics/SharedJointSystem.cs
  Robust.UnitTesting/Shared/Map/GridFixtures_Tests.cs
  Robust.UnitTesting/Shared/Physics/MapVelocity_Test.cs
Labels: Status: Requires Content PR

#2902 Ordered EventBus optimizations
  Resources/Locale/en-US/commands.ftl
  Robust.Client/GameObjects/ClientComponentFactory.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Shared/Console/Commands/DumpNetComponentsCommand.cs
  Robust.Shared/GameObjects/ComponentFactory.cs
  Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs
  Robust.Shared/GameObjects/EntityEventBus.Common.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/GameObjects/EntityEventBus.Ordering.cs
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/EntityManager.cs
  Robust.Shared/GameObjects/EntitySystem.cs
  Robust.Shared/Physics/Dynamics/ContactManager.cs
  Robust.Shared/Physics/SharedBroadphaseSystem.cs
  Robust.Shared/Utility/CollectionExtensions.cs
  Robust.Shared/Utility/HashCodeHelpers.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.ComponentEvent.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.OrderedEvents.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.SystemEvent.cs
Labels: Issue: Performance, Area: ECS

#2947 Cache layer RSI state
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
Labels: Area: Rendering

#2948 Misc rendering changes
  Robust.Client/GameObjects/Components/Renderable/SpriteBoundsOverlay.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/GameObjects/EntitySystems/DebugLightTreeSystem.cs
  Robust.Client/GameStates/NetInterpOverlay.cs
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Client/Graphics/Clyde/Clyde.Viewport.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Graphics/ClydeHandle.cs
  Robust.Client/Graphics/IClydeViewport.cs
Labels: Area: Rendering

#2958 Add Overlay.BeforeDraw()
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Client/Graphics/Overlays/Overlay.cs
Labels: Area: Rendering

#2968 Remove implicit grid conversion
  Robust.Server/Console/Commands/MapCommands.cs
  Robust.Server/Maps/IMapLoader.cs
  Robust.Server/Maps/MapLoader.cs
  Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs
  Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs
  Robust.Shared/Map/GridId.cs
  Robust.UnitTesting/Server/Maps/MapLoaderTest.cs
Labels: Status: Requires Content PR
