Repository space-wizards/RobustToolbox, pull requests merged in 2023-04, with the labels that each got.

#3684 Auto-componentstate source generator
  MSBuild/Robust.CompNetworkGenerator.targets
  Robust.Analyzers/AccessAnalyzer.cs
  Robust.Shared.CompNetworkGenerator/ComponentNetworkGenerator.cs
  Robust.Shared.CompNetworkGenerator/NameReferenceSyntaxReceiver.cs
  Robust.Shared.CompNetworkGenerator/Robust.Shared.CompNetworkGenerator.csproj
  Robust.Shared/Analyzers/ComponentNetworkGeneratorAuxiliary.cs
  Robust.Shared/Analyzers/RobustAutoGeneratedAttribute.cs
  Robust.Shared/GameObjects/EntityEventBus.Directed.cs
  Robust.Shared/Robust.Shared.csproj
Labels: Area: Networking

#3663 Adds a new `ResPath` struct that will replace `ResourcePath`
  Robust.Benchmarks/Utility/ResourcePathBench.cs
  Robust.Shared/GameObjects/Components/Renderable/SharedSpriteComponent.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/ResPathSerializer.cs
  Robust.Shared/Utility/ResPath.cs
  Robust.Shared/Utility/ResourcePath.cs
  Robust.UnitTesting/Shared/Utility/ResPathTest.cs
  Robust.UnitTesting/Shared/Utility/ResourcePath_Test.cs
Labels: Status: Needs Discussion, Status: Needs Review

#3978 Generalize sprite view
  Resources/EnginePrototypes/Debug/rotation.yml
  Robust.Client/Console/Commands/UITestCommand.TabSpriteView.cs
  Robust.Client/Console/Commands/UITestCommand.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/Graphics/Clyde/Clyde.RenderHandle.cs
  Robust.Client/Graphics/Drawing/DrawingHandleScreen.cs
  Robust.Client/Graphics/IRenderHandle.cs
  Robust.Client/UserInterface/Controls/SpriteView.cs
Labels: Status: Requires Content PR

#3981 Remove server and shared sprite component
  Robust.Client/GameObjects/Components/Appearance/GenericVisualizerComponent.cs
  Robust.Client/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Client/GameObjects/EntitySystems/SpriteSystem.Specifier.cs
  Robust.Client/Serialization/ClientSpriteSpecifierSerializer.cs
  Robust.Client/Utility/SpriteSpecifierExt.cs
  Robust.Server/GameObjects/Components/Renderable/SpriteComponent.cs
  Robust.Server/GameObjects/EntitySystems/MapLoaderSystem.cs
  Robust.Server/GameObjects/ServerComponentFactory.cs
  Robust.Server/Serialization/ServerSpriteSpecifierSerializer.cs
  Robust.Shared/GameObjects/ComponentFactory.cs
  Robust.Shared/GameObjects/Components/Renderable/SharedSpriteComponent.cs
  Robust.Shared/GameObjects/Components/Renderable/SpriteLayerData.cs
  Robust.Shared/GameObjects/IComponentFactory.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/EnumSerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/ResPathSerializer.cs
  Robust.Shared/Serialization/TypeSerializers/Implementations/SpriteSpecifierSerializer.cs
  Robust.UnitTesting/Shared/Prototypes/PrototypeManager_Test.cs
Labels: Status: Requires Content PR, Holy Shit
