Repository space-wizards/RobustToolbox, pull requests merged in 2023-08, with the labels that each got.

#4231 Error on duplicate broadcast subscriptions
  Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs
  Robust.UnitTesting/Shared/GameObjects/EntityEventBusTests.SystemEvent.cs
Labels: Status: Requires Content PR

#4253 Rename a Dirty() proxy method to DirtyEntity()
  Robust.Shared/GameObjects/EntitySystem.Proxy.cs
  Robust.Shared/GameObjects/Systems/MetaDataSystem.cs
Labels: Status: Requires Content PR

#4262 Add recursive PVS overrides and remove IsOverride()
  Robust.Server/GameStates/PvsCollection.cs
  Robust.Server/GameStates/PvsOverrideSystem.cs
  Robust.Server/GameStates/PvsSystem.cs
Labels: Status: Requires Content PR

#4295 Fix serialization sharing instances when copying data definitions and not assigning null when the source is null
  Robust.Serialization.Generator/Generator.cs
  Robust.Shared/GameObjects/Component.cs
  Robust.Shared/Serialization/Manager/SerializationManager.SerializerProvider.cs
  Robust.Shared/Utility/SpriteSpecifier.cs
  Robust.UnitTesting/Shared/Serialization/PropertyAndFieldDefinitionTest.cs
  Robust.UnitTesting/Shared/Serialization/SerializationTests/CommunitaryLungTest.cs
Labels: Holy Shit

#4307 Convert `Tile.TypeId` to an int
  Robust.Client/Map/ClydeTileDefinitionManager.cs
  Robust.Client/Map/IClydeTileDefinitionManager.cs
  Robust.Server/GameObjects/EntitySystems/MapLoaderSystem.cs
  Robust.Server/Maps/MapChunkSerializer.cs
  Robust.Server/Placement/PlacementManager.cs
  Robust.Shared/Enums/PlacementInformation.cs
  Robust.Shared/Map/MapSerializationContext.cs
  Robust.Shared/Map/Tile.cs
  Robust.Shared/Network/Messages/MsgPlacement.cs
  Robust.Shared/Placement/PlacementEvent.cs
Labels: Status: Awaiting Changes
