Repository space-wizards/RobustToolbox, pull requests merged in 2024-03, with the labels that each got.

#4959 Add collection parsing to the dev window for UI
  Robust.Client/Console/Commands/Debug.cs
  Robust.Client/UserInterface/DevWindow/DevWindowTabUI.xaml
  Robust.Client/UserInterface/DevWindow/DevWindowTabUI.xaml.cs
  Robust.Client/UserInterface/DevWindow/DevWindowTabUIPopup.xaml
  Robust.Client/UserInterface/DevWindow/DevWindowTabUIPopup.xaml.cs
Labels: Issue: Feature Request, Area: UI, Status: Needs Review

#4883 Making possible to QueueDeleteEntity on EndCollideEvent
  RELEASE-NOTES.md
  Robust.Shared/Physics/Dynamics/Contacts/Contact.cs
  Robust.Shared/Physics/Systems/SharedPhysicsSystem.Components.cs
  Robust.Shared/Physics/Systems/SharedPhysicsSystem.Contacts.cs
Labels: Status: Awaiting Changes

#4966 Implement sound VV
  RELEASE-NOTES.md
  Resources/Locale/en-US/vv.ftl
  Robust.Client/Audio/AudioSystem.cs
  Robust.Client/ViewVariables/ClientViewVariablesManager.cs
  Robust.Client/ViewVariables/Editors/VVPropEditorSoundSpecifier.cs
  Robust.Server/Audio/AudioSystem.cs
  Robust.Server/ViewVariables/ServerViewVariablesManager.cs
  Robust.Server/ViewVariables/ViewVariablesTrait.cs
  Robust.Shared/Audio/Systems/SharedAudioSystem.cs
Labels: Area: UI

#5005 Fix first measure of ScrollContainer scroll bars
  Robust.Client/UserInterface/Controls/ScrollContainer.cs
Labels: Issue: Bug, Area: UI
