Repository space-wizards/RobustToolbox, pull requests merged in 2025-02, with the labels that each got.

#5598 Make PVS overrides respect vismasks
  RELEASE-NOTES.md
  Robust.Server/Audio/AudioSystem.cs
  Robust.Server/GameStates/PvsData.cs
  Robust.Server/GameStates/PvsOverrideSystem.cs
  Robust.Server/GameStates/PvsSystem.Overrides.cs
  Robust.Server/GameStates/PvsSystem.ToSendSet.cs
  Robust.Server/GameStates/PvsSystem.cs
Labels: Area: Networking

#5573 Add support for optional and `params T[]` toolshed command arguments.
  RELEASE-NOTES.md
  Resources/Locale/en-US/toolshed-commands.ftl
  Robust.Shared/Prototypes/EntProtoId.cs
  Robust.Shared/Toolshed/Commands/Generic/CountCommand.cs
  Robust.Shared/Toolshed/Commands/Generic/EmplaceCommand.cs
  Robust.Shared/Toolshed/Commands/Generic/ReduceCommand.cs
  Robust.Shared/Toolshed/Commands/Generic/Variables/VarsCommand.cs
  Robust.Shared/Toolshed/Commands/Math/ArithmeticCommands.cs
  Robust.Shared/Toolshed/Commands/Misc/ExplainCommand.cs
  Robust.Shared/Toolshed/ReflectionExtensions.cs
  Robust.Shared/Toolshed/Syntax/Expression.cs
  Robust.Shared/Toolshed/Syntax/ParsedCommand.cs
  Robust.Shared/Toolshed/Syntax/ParserContext.Config.cs
  Robust.Shared/Toolshed/Syntax/ParserContext.cs
  Robust.Shared/Toolshed/Syntax/ValueRef.cs
  Robust.Shared/Toolshed/ToolshedCommand.Help.cs
  Robust.Shared/Toolshed/ToolshedCommand.cs
  Robust.Shared/Toolshed/ToolshedCommandImplementor.cs
  Robust.Shared/Toolshed/ToolshedManager.Parsing.cs
  Robust.Shared/Toolshed/ToolshedManager.PrettyPrint.cs
  Robust.Shared/Toolshed/ToolshedManager.cs
  Robust.Shared/Toolshed/TypeParsers/BlockType.cs
  Robust.Shared/Toolshed/TypeParsers/BlockTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/BoolTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/CommandRunTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/CommandSpecTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/ComponentTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/EntityTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/EnumTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/InstanceIdTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/Math/AngleTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/Math/ColorTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/Math/NumberBaseTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/Math/SpanLikeTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/PrototypeTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/QuantityTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/ResPathTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/SessionTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/StringTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/Tuples/BaseTupleTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/TypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/TypeTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/ValueRefTypeParser.cs
  Robust.Shared/Toolshed/TypeParsers/VarRefType.cs
  Robust.Shared/Toolshed/TypeParsers/VarRefTypeParser.cs
  Robust.UnitTesting/Shared/Toolshed/TestCommands.cs
  Robust.UnitTesting/Shared/Toolshed/ToolshedTests.cs
Labels: Status: Requires Content PR, Status: Needs Review, Toolshed

#5654 add a method for copying components
  Robust.Shared/GameObjects/EntityManager.Components.cs
  Robust.Shared/GameObjects/EntitySystem.Proxy.cs
  Robust.Shared/GameObjects/IEntityManager.Components.cs
  Robust.UnitTesting/Shared/GameObjects/EntityManagerCopyTests.cs
  Robust.UnitTesting/Shared/GameObjects/IEntityManagerTests.cs
Labels: Status: Awaiting Changes

#5696 Fix issue regarding Tilemaps not saving when modified
  Robust.Shared/EntitySerialization/EntitySerializer.cs
Labels: Priority: 1-Urgent, Area: Serialization, Status: Needs Review

#5694 Move VisibilitySystem to shared
  Robust.Client/GameObjects/EntitySystems/VisibilitySystem.cs
  Robust.Server/GameObjects/EntitySystems/VisibilitySystem.cs
  Robust.Shared/GameObjects/Components/Eye/VisibilityComponent.cs
  Robust.Shared/GameObjects/Systems/SharedVisibilitySystem.cs
  Robust.UnitTesting/Shared/GameObjects/ContainerTests.cs
Labels: Status: Awaiting Changes, Area: PVS
