Repository space-wizards/RobustToolbox, pull requests merged in 2025-01, with the labels that each got.

#5583 SDL3
  Robust.Client.WebView/Cef/WebViewManagerCef.Control.cs
  Robust.Client/GameController/GameController.Standalone.cs
  Robust.Client/Graphics/Clyde/Clyde.Windowing.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Graphics/Clyde/Windowing/Glfw.Events.cs
  Robust.Client/Graphics/Clyde/Windowing/Glfw.Windows.cs
  Robust.Client/Graphics/Clyde/Windowing/Glfw.cs
  Robust.Client/Graphics/Clyde/Windowing/IWindowingImpl.cs
  Robust.Client/Graphics/Clyde/Windowing/SDL2Api.cs
  Robust.Client/Graphics/Clyde/Windowing/SDL3-CS/LICENSE
  Robust.Client/Graphics/Clyde/Windowing/SDL3-CS/SDL3.Core.Ext.cs
  Robust.Client/Graphics/Clyde/Windowing/SDL3-CS/SDL3.Core.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.Keys.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.Monitors.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.RawEvents.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.Windows.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl2.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.Cursor.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.Event.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.FileDialog.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.Key.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.Monitor.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.RawEvent.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.Window.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.WindowIcons.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.WindowThread.cs
  Robust.Client/Graphics/Clyde/Windowing/Sdl3.cs
  Robust.Client/Graphics/Clyde/Windowing/WsiShared.cs
  Robust.Client/Graphics/IClyde.cs
  Robust.Client/Graphics/IClydeInternal.cs
  Robust.Client/Graphics/IClydeWindow.cs
  Robust.Client/UserInterface/Controls/LineEdit.cs
  Robust.Client/UserInterface/Controls/TextEdit.cs
  Robust.Client/UserInterface/FileDialogManager.cs
  Robust.Shared/ContentPack/Sandbox.yml
Labels: Area: Platform Integration

#5604 Fix replay playback bugs
  RELEASE-NOTES.md
  Robust.Client/GameStates/ClientGameStateManager.cs
  Robust.Client/GameStates/IClientGameStateManager.cs
  Robust.Client/Replays/Loading/ReplayLoadManager.Start.cs
  Robust.Client/Replays/Playback/ReplayPlaybackManager.Update.cs
  Robust.Shared/GameObjects/ComponentState.cs
Labels: Issue: Bug

#5584 Fix autocompletion hint for toolshed strings
  RELEASE-NOTES.md
  Robust.Client/UserInterface/CustomControls/DebugConsole.xaml.Completions.cs
  Robust.Shared/Console/CompletionResult.cs
  Robust.Shared/Toolshed/TypeParsers/StringTypeParser.cs
Labels: Toolshed

#5223 Add support for overlays to draw controls
  RELEASE-NOTES.md
  Robust.Client/Graphics/Clyde/Clyde.HLR.cs
  Robust.Client/Graphics/Clyde/Clyde.Viewport.cs
  Robust.Client/Graphics/Clyde/ClydeHeadless.cs
  Robust.Client/Graphics/IClydeViewport.cs
  Robust.Client/Graphics/Overlays/OverlayDrawArgs.cs
  Robust.Client/UserInterface/Control.Styling.cs
  Robust.Client/UserInterface/Control.cs
  Robust.Client/UserInterface/Controls/SpriteView.cs
  Robust.Client/UserInterface/CustomControls/ViewportContainer.cs
  Robust.Client/UserInterface/IUserInterfaceManager.cs
  Robust.Client/UserInterface/UserInterfaceManager.Roots.cs
  Robust.Client/UserInterface/UserInterfaceManager.cs
Labels: Status: Requires Content PR

#5612 Fix reloading prototypes with AlwaysPushInheritance
  RELEASE-NOTES.md
  Robust.Client/Replays/Loading/ReplayLoadManager.Checkpoints.cs
  Robust.Shared/Prototypes/IPrototypeManager.cs
  Robust.Shared/Prototypes/PrototypeManager.YamlLoad.cs
  Robust.Shared/Prototypes/PrototypeManager.cs
  Robust.Shared/Serialization/Manager/SerializationManager.Composition.cs
  Robust.Shared/Serialization/Markdown/Mapping/MappingDataNode.cs
  Robust.Shared/Upload/SharedPrototypeLoadManager.cs
Labels: Area: Serialization
