Repository space-wizards/RobustToolbox, pull requests merged in 2025-06, with the labels that each got.

#6015 Add PvsResetTest
  Robust.UnitTesting/Server/GameStates/PvsResetTest.cs
Labels: Area: Testing

#6038 Adds typeselector to ColorSelectorSlider.cs
  Robust.Client/UserInterface/Controls/ColorSelectorSliders.cs
Labels: T: Bugfix, A: UI

#6034 Add tests for remaining `DataDefinitionAnalyzer` diagnostics
  Robust.Analyzers.Tests/DataDefinitionAnalyzerTest.cs
  Robust.Analyzers/DataDefinitionAnalyzer.cs
Labels: A: Serialization, A: Roslyn Components, T: Tests

#6035 Optimize `DataDefinitionAnalyzer` a bit
  Robust.Analyzers/DataDefinitionAnalyzer.cs
Labels: T: Performance, Priority: 3-Not Required, A: Serialization, A: Roslyn Components

#6029 Add API to load maps from byte stream
  Robust.Shared/EntitySerialization/Systems/MapLoaderSystem.Load.cs
  Robust.Shared/EntitySerialization/Systems/MapLoaderSystem.cs
Labels: T: New Feature, A: Mapping

#5989 Fix rich text entry measure
  Robust.Client/UserInterface/RichTextEntry.cs
Labels: A: UI

#5956 Add GetMessage and SetMessage methods to OutputPanel
  Robust.Client/UserInterface/Controls/OutputPanel.cs
Labels: T: New Feature, A: UI

#6045 genetive case
  Resources/Locale/en-US/_engine_lib.ftl
  Robust.Shared/Localization/LocalizationManager.Functions.cs
Labels: T: New Feature, A: Localization

#6044 Make some `PlacementManager` dependency fields public
  Robust.Client/Placement/IPlacementManager.cs
  Robust.Client/Placement/PlacementManager.cs
Labels: T: New Feature, A: Mapping

#6047 Add `AlwaysActive` to WebViewControl
  Robust.Client.WebView/Cef/WebViewManagerCef.Control.cs
  Robust.Client.WebView/Headless/WebViewManagerHeadless.cs
  Robust.Client.WebView/IWebViewControlImpl.cs
  Robust.Client.WebView/WebViewControl.cs
Labels: T: New Feature, A: WebView

#6048 Add analyzers to detect some prototype misuse
  Robust.Analyzers.Tests/PrototypeInstantiationAnalyzerTest.cs
  Robust.Analyzers.Tests/PrototypeNetSerializableAnalyzerTest.cs
  Robust.Analyzers.Tests/RTAnalyzerTest.cs
  Robust.Analyzers.Tests/Robust.Analyzers.Tests.csproj
  Robust.Analyzers/PrototypeInstantiationAnalyzer.cs
  Robust.Analyzers/PrototypeNetSerializableAnalyzer.cs
  Robust.Roslyn.Shared/AttributeHelper.cs
  Robust.Roslyn.Shared/Diagnostics.cs
  Robust.Roslyn.Shared/TypeSymbolHelper.cs
  Robust.Shared/Prototypes/Attributes.cs
  Robust.Shared/Prototypes/IPrototype.cs
  Robust.Shared/Serialization/Manager/Attributes/DataFieldAttribute.cs
Labels: T: New Feature, A: Roslyn Components

#5692 IRobustCloneable and generator support
  Robust.Shared.CompNetworkGenerator/ComponentNetworkGenerator.cs
  Robust.Shared/Serialization/IRobustCloneable.cs
  Robust.UnitTesting/Shared/EntitySerialization/RobustCloneableTest.cs
Labels: T: New Feature, Priority: 1-Urgent, A: Roslyn Components, A: PVS / GameState Networking
