Repository space-wizards/RobustToolbox, pull requests merged in 2025-08, with the labels that each got.

#6118 fix: use the actual top anchor in SetMarginsPreset
  RELEASE-NOTES.md
  Robust.Client/UserInterface/Controls/LayoutContainer.cs
Labels: T: Bugfix, A: UI

#6119 add: Dictionary<T, TimeSpan> OnUnpaused generator
  Robust.Analyzers.Tests/ComponentPauseGeneratorTest.cs
  Robust.Serialization.Generator/ComponentPauseGenerator.cs
Labels: T: New Feature, S: Awaiting Changes, A: Roslyn Components

#6115 Better unsubscription for multiple ConfigurationManager subscriptions
  RELEASE-NOTES.md
  Robust.Shared/Collections/InvokeList.cs
  Robust.Shared/Configuration/ConfigurationManagerExtensions.cs
  Robust.UnitTesting/Shared/Configuration/ConfigurationManagerTest.cs
Labels: T: Bugfix, T: New Feature, S: Awaiting Changes, A: Configuration

#6082 feat: added generic method for getting component from ComponentRegistry
  RELEASE-NOTES.md
  Robust.Shared/GameObjects/ComponentFactory.cs
  Robust.Shared/GameObjects/IEntityLoadContext.cs
  Robust.Shared/Prototypes/EntityPrototype.cs
Labels: S: Awaiting Changes

#6125 Add the ability to scale ItemList icons
  Robust.Client/UserInterface/Controls/ItemList.cs
Labels: T: New Feature, A: UI

#6126 Mark `AutoGenerateComponentStateAttribute` fields as `readonly`
  Robust.Shared/Analyzers/ComponentNetworkGeneratorAuxiliary.cs
Labels: T: Bugfix, Size: Very Small, A: PVS / GameState Networking

#6127 Minimum MIDI note volume
  Robust.Client/Audio/Midi/IMidiRenderer.cs
  Robust.Client/Audio/Midi/MidiRenderer.cs
Labels: T: New Feature, A: MIDI

#6106 Update MidiRenderer to use TryNoteOn and TryNoteOff
  Robust.Client/Audio/Midi/MidiRenderer.cs
Labels: A: MIDI

#6113 Fix instrument pausing when outside PVS range
  Robust.Client/Audio/Midi/MidiManager.cs
Labels: A: MIDI

#6096 Move ScaleVisuals to Content (and improve it)
  Resources/Locale/en-US/commands.ftl
  Robust.Client/GameObjects/EntitySystems/ScaleVisualsSystem.cs
  Robust.Server/Console/Commands/ScaleCommand.cs
  Robust.Shared/GameObjects/Components/Appearance/ScaleVisualsComponent.cs
  Robust.Shared/GameObjects/Systems/ScaleVisualsSystem.cs
  Robust.Shared/Physics/Systems/SharedPhysicsSystem.Fixtures.cs
Labels: S: Awaiting Changes
